### ISSUE TITLE
Evergreen self-update while WebView2 is being used

### ISSUE THREAD

**Issue by e-osw** [MicrosoftEdge/WebView2Feedback#1024]
How does WebView2 behave, when there is a new update available for the Evergreen version while it it used by a running application? Is the update postponed until no application is using it anymore or is there some other mechanism?

Unfortunately I could not find any detailled information about the self-update process. For example, is it distributed via Windows Update and if not, are there any plans to include it to Windows Update in the future? 

I would appreciate some information on this. Thanks.

**Comment by champnic** [comment]
Hey @e-osw - great question! New versions of the runtime can install side-by-side. Existing apps using WebView2 are unaffected when this happens, but will receive a [NewBrowserVersionAvailable](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment?view=webview2-1.0.774.44#add_newbrowserversionavailable) event if subscribed, to be able to close down the WebView2 and recreate it to pickup the new version. Otherwise, when the app is restarted it will automatically pickup the new runtime. We recommend all apps listen to the event and update when available, and we are going to add that to a "Best Practices" doc we are working on.

WebView2 Runtime updates are driven by the same installer the browser uses, not by Windows Update. We don't currently have plans to use Windows Update.
