### ISSUE TITLE
Which folder do I point BrowserExecutableFolder for pre-release version?

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#1032]
Below is the text of my original question. I have now worked out that the reason for the error was that I was pointing BrowserExecutableFolder to the path C:\Program Files (x86)\Microsoft\Edge Dev\Application\90.0.803.0. Edge Dev updated and the last folder updated to 90.0.810.1.

Comment: Is it possible that there is some kind of error message when the BrowserExecutableFolder path does not exist?

Question: For pre-releases am I pointing to the right path and I simply need to update it, or is there a better way?

**  Original Question Below **
I am using the current pre-release version 1.0.790 in a WPF project. BrowserExecutableFolder points to the Dev Edge 90.0.803.0 folder.

WebView2's source is being set in Xaml.

In the CoreWebView2InitializationCompleted event I use CoreWebView2 however it is still nothing.

Are there some cases where CoreWebView2 is not ready after this event?

[AB#32076732](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32076732)

**Comment by cgeier** [comment]
@darbid:  You may consider not setting  the value for BrowserExecutableFolder or set it to null.

See [here ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.705.50#Microsoft_Web_WebView2_Core_CoreWebView2Environment_CreateAsync_System_String_System_String_Microsoft_Web_WebView2_Core_CoreWebView2EnvironmentOptions_)for more information on browserExecutableFolder

**Comment by champnic** [comment]
Hey @darbid - I'm opening a bug on us to improve the experience here - we should be throwing a clearer error when BrowserExectutableFolder doesn't exist.

For pre-releases, you are right you will need to update the path if it changes. The other option is to set the WEBVIEW2_RELEASE_CHANNEL_PREFERENCE environment variable to "1", which will reverse the search order and start with Canary > Dev > Beta > WebView2 Runtime. We are already working on improving this documentation to make this easier to find.
`Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");`

**Comment by darbid** [comment]
Yes maybe a bug is the right way forward.

I was going to right a follow up comment here as I did  not understand the documentation, so a little update here would also be good.

Thank you.

**Comment by champnic** [comment]
Hey @darbid - We are taking a look at this bug. It looks like we are correctly including the initialization failure information in the event args of the CoreWebView2InitializationCompleted event:
![image](https://user-images.githubusercontent.com/45700886/115471429-d30b0280-a1ec-11eb-8d80-fbef7f80e723.png)

I ma have misunderstood the original question. Yes, there are cases where CoreWebView2InitializationCompleted fires but the WebView2 failed to initialize. If so, this information is captured in the event args:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2initializationcompletedeventargs?view=webview2-dotnet-1.0.774.44

You can check that CoreWebView2 is null, or args.IsSuccess is false, and args.InitializationException will contain info about the failure.

Can you verify you get that same behavior when it fails? This behavior is By Design and outlined in[ our docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.corewebview2initializationcompleted?view=webview2-dotnet-1.0.774.44), so I'm going to close out this issue, but please let me know if that doesn't work or you have other questions. Thanks!

**Comment by darbid** [comment]
Thank you. Confirmed.
