### ISSUE TITLE
WebView2 displays white screen only

### ISSUE THREAD

**Issue by radekvit** [MicrosoftEdge/WebView2Feedback#1042]
**Description**
WebView2 displays a white screen instead of bing.com or the create-react-app default app.

When running the WebWiew2 sample app in Debug, I get no exceptions.

**Version**
SDK: 1.0.705.50 (NuGet Microsoft.Web.WebView2 package)
Runtime: Microsoft Edge Version 89.0.774.45 
Toolset: Visual Studio 2019 (v142)
Framework: Win32 
OS: Win10

**Repro Steps**
Follow https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32 to Step 3

Expeced: The Bing website is displayed
Actual: A blank screen is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/25612317/110219568-6055fa00-7ec0-11eb-8490-60a590d5bfa6.png)

**Additional context**
I tried displaying the [create-react-app](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app) default app with https://github.com/Boscop/web-view and I get the same issue: only a blank white screen is displayed.
When I run the same index.html file with Chrome or Edge, it works as expected.

[AB#32079372](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32079372)

**Comment by cgeier** [comment]
@radekvit: Check if your are affected by issue #1044.

**Comment by dominicletz** [comment]
I'm having the same issue and it's not related to #1044. What I was able to find so far is that the issue seems to happen when I created the WebView in a window that is not shown. 

![Selection_480](https://user-images.githubusercontent.com/2987674/110359237-8bb22380-803d-11eb-9e4a-10b69c1b0ef1.png)

The fun thing is that even on the bug side Edge is running in the background and I can interact with the API. E.g. fetch the page source code, even eval a script but it won't ever render anything on the screen nor react to right mouse clicks. 

My current workaround is to re-create the WebView once my application is shown and visible on-screen with a 500ms delay. That seems to do it. So I think there is something wrong with creating a webview in the background.

**Comment by champnic** [comment]
Thanks for the report - I've added it to our backlog to take a look.

**Comment by aojianwu** [comment]
I also encountered the same problem

**Comment by radekvit** [comment]
**Fix:**
I managed to get WebView2 working in the Win32 example by installing WebView2 with the [evergreen bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section).
Then, the example started working and showing Edge.

In Rust, web-view still fails, but that must be due to library error and shouldn't be connected with this.

**Comment by champnic** [comment]
Yes, the WebView2 Runtime (or Microsoft Edge Canary/Dev/Beta) are required to run WebView2. More info: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

I'm going to close this issue for now. @dominicletz I've opened your issue separately:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1077
