### ISSUE TITLE
ICoreWebView2ExperimentalCompositionController - key board input

### ISSUE THREAD

**Issue by mediabuff** [MicrosoftEdge/WebView2Feedback#1054]
The new visual hosting api's provide capability to feed mouse/pointer events. 
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalcompositioncontroller?view=webview2-1.0.721-prerelease#sendmouseinput

1)How about keyboard events ?
2) when use use DirectComposition - does it completely obviate the need for a hosting child window for the WebView2 ? how does the Webview2 visual gets it's key board input

**Comment by bradp0721** [comment]
There isn't an API for keyboard input when using DirectComposition, because the WebView2 is able to get keyboard input directly from Windows. The app does not need to create a child HWND to host the WebView2. The WebView2 does need the parent window that is connected to the root of the DComp tree. Spatial input (mouse/pointer/pen events) are delivered to the HWND, which is why the app needs to receive these events and call the matching API on ICoreWebView2CompositionController. The WebView2 will take focus (either when received a pressed event or through the MoveFocus API) and by having focus, the OS will route keyboard events directly to WebView2. That is why there isn't a keyboard API.
