### ISSUE TITLE
How to install WebView2 without escalate administrator privilege?

### ISSUE THREAD

**Issue by zhongyzh** [MicrosoftEdge/WebView2Feedback#1062]
How to install WebView2 without escalate administrator privilege?
We want to dynamic to install WebView2 if it doesn't exist. And most of time no Administrator privilege. We just want to use user folder, no need for all users.

**Comment by champnic** [comment]
Right now you can't install the evergreen runtime without elevation because it is a system wide install. We are tracking user installs to enable installing without elevation in #490.

If this is a blocker for you, you can consider using the Fixed Version Runtime, or we also have plans to ship WebView2 inbox in the next version of Windows and downlevel later.
