### ISSUE TITLE
[DMC]: How to deploy WebView2 using GPO? #1152

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#1109]
Please review the customer issue here: https://github.com/MicrosoftDocs/edge-developer/issues/1152
Thanks!

**Comment by Reezaali** [comment]
@designchris I've opened this issue here for the Engineering team to review.

**Comment by liminzhu** [comment]
> We need to deploy WebView2 company-wide using GPO. How can we do that? Repackaging the .exe as .msi any deploying it using GPO did not work (while the msi can be installed fine manually).

@designchris thanks for opening the issue. There isn't a GPO to install deploy the runtime today, but your managing software will likely have the capability to deploy exe. Are you using Intune or SCCM? We can help find relevant info if needed.

**Comment by TigranGabrielyan** [comment]
Dear @liminzhu, we have the same problem with GPO deployment. We are distributing our software to different customers, and we are not sure what managing software they are using. Is there any generic solutions to deploy WebView2 using GPO? Is there a way to get standalone MSI instead of EXE?
As currently EXE having some issues with silent installation (issue #555), and it requires admin elevation (issue #490) it makes even harder harder to come up with some working approach.

**Comment by designchris** [comment]
Our solution was to deploy Edge using GPO and to allow the Edge Updater to install WebView2. There a GPO setting for that.

WebView2 now appears to be available an all PCs.

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
