### ISSUE TITLE
[DMC] Failed to find WebView2Loader.dll #1154

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#1110]
Please review the customer issue here: https://github.com/MicrosoftDocs/edge-developer/issues/1154
Thanks!

**Comment by Reezaali** [comment]
Hi @vvx-public - I've opened an issue here for the engineering team to review. Thanks.

**Comment by champnic** [comment]
Hey @vvx-public - would you mind adding some details on your setup? The <PlatformTarget> currently needs to be set in the project file for WebView2 to deploy and launch properly. For some project types, this happens automatically when you create the project, but for some other project types (for example, WPF Libraries/Assemblies) this info is missing and the default "AnyCPU" gets interpreted as "x86". The fix is to build specifically Platform="x64" as you noted working, or to manually add <PlatformTarget>AnyCPU</PlatformTarget> to your project file.

**Comment by vvx-public** [comment]
Wow! this is the first time **30 years**, _anyone_ from MSFT has bothered to reply to my questions/feedback/suggestions! My test app is a rather basic WinForm app built using VS2019 (Version 16.8.4), .NET Framework 4.7.2 and (now) Platform target = x64 running on Windows 10 Pro (version 10.0.19042) desktop with Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz with 128 GB RAM 64-bit operating system, x64-based processor. Hope that helps.  However, my main suggestion is you provide more details on what someone must do to use WebView2 in a WinForms app.

**Comment by champnic** [comment]
Thanks for the added info, and apologies for the less-than-stellar response rate in the past!

We have a "Getting Started" guide for Winforms app:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms

Does that sound like what you had in mind? Is there something specific you think is missing? For the basic "Windows Forms App (.NET Framework)" project type in visual studio it should work with Platform="AnyCPU" by default.

**Comment by vvx-public** [comment]
Apologies accepted. THANK YOU. 
I have to head home now, and will at it tomorrow.
Cheers!
