### ISSUE TITLE
WPF Popup does not acquire keyboard focus if focus was on WebView2

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#1134]
**Description**

If we create a popup without losing focus of the WebView2 element (e.g. by using a context menu, rather than clicking a focusable button), the popup looks and feels as if it has keyboard focus, but all keyboard inputs go to the WebView2 instead.

This does not happen if focus is lost by WebView by clicking some focusable WPF element first (e.g. clicking the button, rather than right-clicking it).

Are there any workarounds for this? E.g. to manually remove keyboard focus from the WebView2 element?

**Version**
SDK: 1.0.824-prerelease
Runtime: 91.0.842.0 Canary
Framework: WPF + .NET 5
OS: Windows 10 x64, Build 19041

**Repro Steps**

```
<Window x:Class="WebView2KeyboardFocusRepro.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WebView2KeyboardFocusRepro"
        xmlns:wpf="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="32"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <StackPanel>
            <Button Content="Right click me" Click="MenuItem_OnClick">
                <Button.ContextMenu>
                    <ContextMenu>
                        <MenuItem Click="MenuItem_OnClick" Header="Popup"></MenuItem>
                    </ContextMenu>
                </Button.ContextMenu>
            </Button>
        </StackPanel>
        <wpf:WebView2 Grid.Row="1" Source="https://www.bing.com/" />
        <Popup Placement="Center" Name="myPopup" IsOpen="False" Width="400" Height="200">
            <TextBox>Enter text</TextBox>
        </Popup>
    </Grid>
</Window>
```

Code-behind for the menu item click:
```
        private void MenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            this.myPopup.IsOpen = true;
        }
```

Steps:
* Select the bing search box
* Right-click the button, select Popup
* Click into the popup's text box if it doesn't already have a cursor in it
* Try typing

Expected:
Popup's text box receives the input

Actual:
The text appears in bing's search box

**Screenshots**

![ezgif-7-647cc8d3ef89](https://user-images.githubusercontent.com/4180387/113127395-60c48500-9221-11eb-9e3c-0045391239dc.gif)

[AB#36775741](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36775741)

**Comment by RendijsSmukulis** [comment]
In case somebody else hits this issue: I've found a(n ugly) workaround: 
* add an invisible "focus sink" button to the window, `<Button  Grid.Row="1" Name="FocusSinkButton" Opacity="0" Width="0" Height="0"/>`,
* In popup, handle `Opened` event, and first set focus to the focus sink button, then to the textbox.

**Comment by champnic** [comment]
Thanks for the bug report, I've added this as a bug on our backlog. I'm glad you managed to find a workaround for this in the meantime!

**Comment by champnic** [comment]
@RendijsSmukulis We've tracked this down to a bug in WPF. Because WebView2 is in a separate HwndHost, when focus moves somewhere else WPF also needs to move Win32 keyboard focus so that WebView2 can lose focus. However, in the case of a popup there's a check for the WS_EX_NOACTIVATE window style and that makes WPF not move Win32 keyboard focus. We're following up with WPF team now.

In the meantime, another workaround is to move Win32 keyboard focus yourself:
```cs
        [DllImport("user32.dll", SetLastError = true)]
        static extern IntPtr SetFocus(IntPtr hWnd);

        private void myPopup_Opened(object sender, EventArgs e)
        {
            HwndSource source = (HwndSource)HwndSource.FromVisual(myPopup.Child);
            IntPtr hwnd = source.Handle;
            SetFocus(hwnd);
            myTextBox.Focus();
        }
```

**Comment by blakeanator** [comment]
This is a slightly different issue (not WebView2). Having this exact issue with a WPF textbox in Excel. In this case, the Excel cells do not lose focus. Did the WPF team ever get back on this?

**Comment by darbid** [comment]
I have a feeling that this might be more of a WPF issue than directly related to Webview2.  Trying to open popup from context items or repeatbuttons causes an issue with mouse capture in the popup.

I believe that the solution is upon opening the popup give something on it like a text box mouse capture.

A simple example is just subclass popup and have something like the following. Please note my FindsChild finds a TextBox which I have hidden as the first child. I found that a Textbox was the best to give mouse capture to.

```
protected override void OnOpened(EventArgs e)
{
	base.OnOpened(e);
	Control ctl = FindChild<Control>(this.GetChildObjects().First());
	Mouse.Capture(ctl, CaptureMode.SubTree)
}

public static T FindChild<T>(DependencyObject depObj) where T : DependencyObject
{
	if (depObj == null) return null;
	if (depObj is T)
		return depObj as T;

	for (int i = 0; i < VisualTreeHelper.GetChildrenCount(depObj); i++)
	{
		DependencyObject child = VisualTreeHelper.GetChild(depObj, i);

		//DFS
		T obj = FindChild<T>(child);

		if (obj != null)
			return obj;
	}
	return null;
}

```

**Comment by zhuhaichao518** [comment]
Hi, @RendijsSmukulis, we have released a new experimental hosting mode in the recent SDK. Focus and Inputs will be on native apps in this mode. You can enable this mode by enabling the feature flag ("--enable-features=msWebView2BrowserHitTransparent") in
[CoreWebView2CreationProperties.AdditionalBrowserArguments](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.corewebview2creationproperties.additionalbrowserarguments?view=webview2-dotnet-1.0.1462.37) or
[CoreWebView2EnvironmentOptions.AdditionalBrowserArguments](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1462.37).
I think enabling this feature should be helpful to this bug. 
Because this is a big change, there may be new bugs in the new mode. Please notify us if you find new issue related to the new mode.

**Comment by zhuhaichao518** [comment]
Hi, @RendijsSmukulis, the new feature is available in the recent release (109). This feature may be helpful to this bug. Please try out if possible and tell us if there are related bugs. Thanks!
