### ISSUE TITLE
Receive mouse events in C# code

### ISSUE THREAD

**Issue by hugoam** [MicrosoftEdge/WebView2Feedback#1135]
Hello,

I'd like to know how we could listen to a bunch of mouse events (MouseDown, MouseUp and MouseMove) in addition or on top of how the Webview handles those events. Ideally, we want to listen to those events directly on the Window, or on the Webview itself (since it spans the entire window that should be fine too).
Currently we are doing this by having the events captured in Javascript and sent back to the C# code, but this causes issues because the resulting events have already gone through the whole browser specification, and we would need to instead get the native WPF events directly.
I've tried listening to the MouseDown event on the Window and on the Webview, but with neither do I receive any events.

Any help would be greatly appreciated

**Comment by RickStrahl** [comment]
Some events bubble through - for example, various key events will trigger on the WebView in WPF **after** they've passed through JavaScript handlers. 

Not sure for mouse events - I think that would be weird if that did work since WPF in general doesn't pass mouse events up the control tree.  If you click into a textbox for example, the Window doesn't get a MouseDown event either.

What you can do though is to listen to the events in JavaScript and marshall them back to WPF via the Interop features. I've had good luck doing this but this is a lot more work and... requires that you control the page to have script code inside of it (or inject inside of it). I have a [blog post that goes into some detail with this](https://weblog.west-wind.com/posts/2021/Jan/26/Chromium-WebView2-Control-and-NET-to-JavaScript-Interop-Part-2).

**Comment by darbid** [comment]
The WPF WebView inherits from WPF base classes so you can see a few properties and methods which are currently not hooked up.

I think drop events are on the way and I really hope mouse events will come too, but right now they are not available.

If you only want to listen to mouse clicks (not mouse move) then you can subclass the WebView child windows (for example with win forms NativeWindow) to get these events.

Before you think about going down this track there are a few things to know. Microsoft has chosen to run the main Chrome window where all window events take place like mouse move in a seperate process meaning it is out of touch with managed code like C# or VB. You would need to inject a dll into the process with C++. This window does notify its parents of a few things which includes clicks but not moves. As these are notifications from a parent you can see but for example not block mouse click events.

I would have an example or could help you if you would like to see click events.

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
