### ISSUE TITLE
Distribution Suggestion: Have fixed distribution package that only ships the Runtime not the full browser

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#1141]
I'm still stuck on the suckiness of the WebView2 runtime distribution story. This once again is biting me in the ass as new releases seem to have broken existing functionality and downright fail to execute basic initialization (in 774+).

Current distribution options are basically to install:

* Downloadable Runtime Packages (small installers, huge installs)
* Local fixed version install (huge distribution requirements 80mb+)

The downloadables and size are not unreasonable, but for most applications the only way to make that work is to link it into the installation process - which doesn't work for a portable install for example.

The Fixed runtime solves that but it's prohibitively large as it essentially installs a side by side Edge install plus the runtime.

### Suggestion: Install Fixed Version of Runtime Only
Is there any chance that there could be another installation option that **only provides the WebView2 specific runtime libraries** and not all of the rest of what constitutes edge? Is that even possible? 

My thinking here is this: 

I'd be OK with **requiring users to already have Edge installed on their system** - perhaps a specific version or newer if needed. But then I could ship a relatively small fixed version of the Runtime (that includes only the WebView2 SDK interfaces which presumably are much smaller) with my application without incurring a massive distribution size hit.

Is this something that can be explored?

**Comment by Symbai** [comment]
In one of my portable applications I check on start if there is a runtime Webview2 can use (which can be the runtime via installer but also an already installed Edge beta/canary). And if its not installed the portable application downloads the installer, installs it and then restarts. This way the portable application remains small and portable and its easy to share.

I think that instead of introducing a third package, the devs should either:

- Find a way to reduce the size of existing packages. Perhaps more stuff can be stripped out
- Allow WebView2 to run on installing of stable Edge. Currently it needs the unstable version so we have to either distribute it or install it even if the user has Edge (Chromium) installed. But if it uses the stable Edge it would just work for most people on Windows 10. The old IE integration for example used the installed IE and devs weren't forced to ship something additionally to make it work.

**Comment by champnic** [comment]
Hey @RickStrahl - I think this is an interesting thought, but this is very likely impossible. The challenge here is in the versioning of the binaries, because the "runtime only" portion of the binaries would need to exactly match the installed Edge browser binaries or it would break often in interesting ways. Different users can have different versions of Edge from machine to machine, and Edge updates around once a week (with large updates every 6). There's simply no way to have the "Fixed Version Runtime" be able to match all these constraints. The layer of interface that is backwards/forwards compatible with multiple versions is already what we ship separately in the SDK packages.

We are currently working on making this better (and yes it's slow, I'm sorry about that!) with being included inbox in the next version of Windows, as well as pushing downlevel to existing machines.

**Comment by RickStrahl** [comment]
@Symbai - yup that's what I currently also do in [Markdown Monster](https://markdowmonster.west-wind.com), but currently the Chromium/Edge support is optional as an addin with IE rendering by default. So app works, and if they switch to Chromium then they'll likely have to download the Edge (evergreen) runtime. 

You have a good point though: For a full admin install that uses an installer the runtime can be installed explicitly. For the portable install (or just for general app check in case the runtime gets uninstalled) the runtime check could be a back up to force install as needed. Maybe that is a good way to go in the future.

For now I'm stuck with this dual mode, as I still do not have a good solution to my key forwarding (to the WPF menu) problem.

**Comment by RickStrahl** [comment]
@champnic I've said this before but I ask again: How does including in Windows solve this problem exactly? Windows updates much less frequently than Edge does, so the runtimes that ship in the box may also get out of date very quickly. 

So far I see way to many breaking API changes in the runtime for this to be sustainable going forward. If I use an older version of the runtime with an newer .NET WebView2 library I don't think that would work, right?

This is frustrating as heck to hear because we never had to worry about this crap with the WebBrowser control. The control was always there and the COM interfaces worked. End of story. None of this make sure you have this or that runtime. It worked with the core APIs and there was no separate runtime. 

Assuming Edge is installed we should be able to 'just work' with the interface handlers dealing with the runtime mismatches if necessary. Assuming you're not using new features (which hopefully after the APIs stabalize more won't be as much of a problem as it has been up to now?) this should just work, regardless of what runtime is installed as long as there is one and you don't explicitly hit a new feature.

**Comment by champnic** [comment]
@RickStrahl Once the runtime is included inbox it will update at the current regular 6-week cadence, separate from the Windows updates. Once you choose a version of the release SDK, which is supported by the corresponding stable WV2 runtime, you mostly shouldn't need to worry about compatibility. There is the potential for an enterprise to turn off WebView2 runtime updates for their users through group policy though, which could result in an older than expected runtime. I don't believe we've had many breaking changes in the runtime - are you talking about when you update the SDK or do you have a specific issue you ran into in mind?

I understand and apologize for the frustration this has caused. It's frustrating for me too, and it's by far the top feedback we've received from all of you. I have and will keep pushing for fixes and improvements in this area as hard as I can. It's also important to note that while WebBrowser "just works", it has it's own set of limitations, often tied with it's inability to update separately from big Windows releases (and of course, it's lack of web standards compatibility).

**Comment by RickStrahl** [comment]
There were recent changes to the Folder To WebUrl mapping, removal of one of the events just in the last couple of updates... I'm talking about the .NET package interfaces. Not sure if that maps to changes in the underlying SDK or not but effectively that shouldn't make a difference.

Thanks for clarifying the release cadence - that does sound more promising if the releases go out more frequently. Maybe I should hold off with my cynicism :smile: until we can see some of the OS installed runtimes and how that works if there are version mismatches. Frankly I'm not sure I totally understand what effect the Nuget->Sdk->Runtime will have given that the application only knows about what it sees in the NuGet package.

**Comment by champnic** [comment]
Ah - yes the Nuget SDK package will change (especially around the prerelease packages/experimental APIs) but upgrading the SDK is optional and at your convenience. The runtime will automatically update, but should never break an already deployed app, and will keep working with whatever SDK version you are using.

> Maybe I should hold off with my cynicism 😄

I appreciate it! But please keep the feedback coming :)

Speaking of which, ideally this document explains the versioning and interaction between SDK + runtime. If you have time, please let me know if there's anything confusing or missing or that we could improve on:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning

**Comment by Symbai** [comment]
> being included inbox in the next version of Windows

Hopefully this is something default and not opt-in (like the .NET Core Windows Update announcement). Only then we/developers can rely on it being present on end user machines.

**Comment by champnic** [comment]
Yes, it will be there by default, not opt-in.
