### ISSUE TITLE
Getting InvalidCastException error while initializing the webView2 

### ISSUE THREAD

**Issue by aks1008** [MicrosoftEdge/WebView2Feedback#1148]
![image](https://user-images.githubusercontent.com/40770553/113515935-129ee100-9595-11eb-91ee-0d90d128ddae.png)

**Comment by lungareakshay** [comment]
WebView2 Version: 1.0.774.44
Application Type: WPF application

**Comment by lungareakshay** [comment]
Hi,

I got it working, but not sure whether it is the correct way to do it...

Instead of calling function InitializeAsync() in the MainWindow() function, I have written code like below:

`public MainWindow()
{
InitializeComponent();
this.Loaded += InitWebView;
}

public void InitWebView (Object Sender, EventArgs e)
{
InitializeAsync();
}
`

And this works properly. I have just called initialization using event after the main WPF application has been loaded.
This could be due to before initializing of WPF application, we were trying to initialize the WebView.

Can you please correct me? Also please suggest why directly calling function from MainWindow causes problem.

**Comment by champnic** [comment]
Hey @aks1008 - This type of error can happen when accessing the WebView2 control from a thread besides the one it was created on (typically the UI thread). So it might have been a threading issue, or you are right that it may not have finished loading the application first. Glad you found the solution to the issue!
