### ISSUE TITLE
Equivalent to DocumentComplete event

### ISSUE THREAD

**Issue by alf17000** [MicrosoftEdge/WebView2Feedback#1159]
Hello

My company had developped a component Win32 based on ActiveX IEFrame (**Microsoft Web Browser**).
Our clients could insert any web page into the component.
We used  event **DocumentComplete** to handle any changes in the web pages, and it worked  with web pages containing Angular.

Now, we replaced our old component with one based on WebView2.
Our probleme is that when a change happens in Angular pages,  NAVIGATIONCOMPLETED or DOMCONTENTLOADED do not fire.

Is there any equivalent to DocumentComplete event in WebView2 ?

Thank you (Sorry for my english)

**Comment by darbid** [comment]
>Our problem is that when a change happens in Angular pages, NAVIGATIONCOMPLETED or DOMCONTENTLOADED do not fire.

Does this mean you had changes to the page where DocumentComplete fired and that same page now does not fire NAVIGATIONCOMPLETED or DOMCONTENTLOADED?

In my opinion DomContentLoaded should be "better" than the old WebBrowser DocumentComplete event.  However neither are going to help with additions made to elements through for example AJAX (js, angular or jquery).

You need to either check and wait for the elements to be on the page (through javascript) or use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).

**Comment by alf17000** [comment]
Yes exactly
Our client has changes to the page where DocumentComplete fired and that same page now does not fire NAVIGATIONCOMPLETED or DOMCONTENTLOADED
Something seems missing with WebView2.

The problem is that we cannot modify page content because it is client code.

We can only use AddScriptToExecuteOnDocumentCreated  + document.addEventListener to simulate  DocumentComplete

**Comment by champnic** [comment]
Hey @alf17000 - thanks for the feedback! This behavior is currently By Design - as @darbid mentions we won't fire navigation events when the page is updated dynamically. However, you have correctly noted a possible workaround of using script to detect changes, and then using [postMessage/WebMessageReceived](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.774.44#add_webmessagereceived) to tell the app that the content has changed.
