### ISSUE TITLE
Feature Request: WinForm TransparencyKey Support

### ISSUE THREAD

**Issue by dexit2k** [MicrosoftEdge/WebView2Feedback#118]
The Old IE Control was able to Key out a certain color. The Webview1 control dosnt support it. It would be nice to have this feat again at the upcomming WinForm WebView2 control.

[AB#27226168](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27226168)

**Comment by david-risney** [comment]
Thanks for the feedback! We'll look into this.

**Comment by inlife** [comment]
Hey @david-risney 

As an alternative approach, I tried setting the extended style of the window to `WS_EX_LAYERED` and setting `LWA_COLORKEY` to a specific color for the `HWND` that is used to embed webview2 in to. That did not work (works fine however on the window before webivew2 is embedded).

Any ideas on why the `LWA_COLORKEY` is not working, am I missing something?

Later on, I also decided to try to enum all children recursively as well, just to test if some "virtual" webview window somehow placed on top and at the same time it is registered as a child or something like that, so I tried executing this code:
```cpp
BOOL CALLBACK fn(HWND hwnd, LPARAM lParam) {
	SetWindowLong(hwnd, GWL_EXSTYLE, GetWindowLong(hwnd, GWL_EXSTYLE) | WS_EX_LAYERED);
	SetLayeredWindowAttributes(hwnd, 0xFFFFFFFF, 0, LWA_COLORKEY);
	EnumChildWindows(hwnd, fn, NULL);
}

// main context
SetWindowLong(mainWindow, GWL_EXSTYLE, GetWindowLong(mainWindow, GWL_EXSTYLE) | WS_EX_LAYERED);
SetLayeredWindowAttributes(mainWindow, 0xFFFFFFFF, 0, LWA_COLORKEY);
EnumChildWindows(mainWindow, fn, NULL);
```

And unfortunately, that did not give any results as well.

Any kind of feedback is appreciated,
Thanks!

**Comment by darbid** [comment]
I too would like to see such a feature promoted. Given that the WPF control is the winforms control it may be possible to make part of the browser transparent which should then show WPF controls below it. Such WPF controls would then appear to be on top.

**Comment by champnic** [comment]
We added support for transparency available through the [DefaultBackgroundColor ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller2?view=webview2-1.0.790-prerelease&viewFallbackFrom=webview2-1.0.781-prerelease#get_defaultbackgroundcolor)API in 1.0.790-prerelease SDK. You can choose which parts of the webpage are transparent by giving them a transparent background. We are tracking clickthrough support in #1004. We don't currently have plans to further support keying out a specific color. If you have a specific scenario that you think can only be accomplished with a key color key rather than a transparent background please let me know. Thanks!
