### ISSUE TITLE
ProcessCmdKey not triggered

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#1215]
**Description**
When we overridde ProcessCmdKey in our customs WinForms Form it does not get triggered when for example F8 is pressed in the browser.

**Version**
SDK: 1.0.824-prerelease
Runtime: Stable Edge 90
Framework: WinForms
OS: Win10, 20H2

**Repro Steps**
Take the following project as example:

```
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

using Microsoft.Web.WebView2.WinForms;

namespace WebView2BugKeys
{
    static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(CreateNewForm());
        }

        private static Form CreateNewForm()
        {
            var form = new TestForm
            {
                Size = new Size(800, 600),
                KeyPreview = true
            };

            var url = @"https://github.com/MicrosoftEdge/WebView2Feedback/";

            var webView2 = new WebView2
            {
                Dock = DockStyle.Fill,
                Source = new Uri(url)
            };
            webView2.EnsureCoreWebView2Async();

            form.Controls.Add(webView2);

            var webControl = new WebBrowser
            { 
                Dock = DockStyle.Top,
                Url = new Uri(url)
            };

            form.Controls.Add(webControl);

            return form;
        }

        private class TestForm : Form 
        {

            protected override bool ProcessCmdKey(ref Message msg, Keys keyData)
            {
                return base.ProcessCmdKey(ref msg, keyData);
            }
        }
    }
}
```

Here we have the old IE-based WebControl on top and the WebView2 on the bottom, when you set a breakpoint in the ProcessCmdKey override and focus the top (IE) browser you will notice that the breakpoint is triggered, however when you do the same for the bottom (new) browser you will notice that the breakpoint is not triggered.

We expect ProcessCmdKey to also work for the new WebView2 browser.

[AB#32802472](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32802472)

**Comment by champnic** [comment]
Thanks for the bug report @fvanheeswijk - we don't currently support ProcessCmdKey, and all our exposed keypresses go through the KeyDown/KeyUp events. I've added this to our backlog to look at adding support for ProcessCmdKey.

**Comment by zhuhaichao518** [comment]
Hi, @fvanheeswijk, we have released a new experimental hosting mode in the recent SDK. Focus and Inputs will be on native apps in this mode. You can enable this mode by enabling the feature flag ("--enable-features=msWebView2BrowserHitTransparent") in
[CoreWebView2CreationProperties.AdditionalBrowserArguments](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.corewebview2creationproperties.additionalbrowserarguments?view=webview2-dotnet-1.0.1462.37) or
[CoreWebView2EnvironmentOptions.AdditionalBrowserArguments](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1462.37).
I think enabling this feature should fix this bug.
Because this is a big change, there may be new bugs in the new mode. Please notify us if you find new issue related to the new mode.

**Comment by zhuhaichao518** [comment]
Hi, @fvanheeswijk, the new feature is available in the recent release (109). This feature may be helpful to this bug. Please try out if possible and tell us if there are related new bugs. Thanks!
