### ISSUE TITLE
How to send correct post data when navigation?

### ISSUE THREAD

**Issue by xiedongweo** [MicrosoftEdge/WebView2Feedback#1238]
We are using the following code to navigate to the specific page with the form data. But our backend  cannot get the correct form data. It always is null.

Please help me check if there are some issues in my code.

`    
    string formData ="&name=abc&age=10"; 
    byte[] pramByte = Encoding.ASCII.GetBytes(formData); 
    using(Stream stream = new MemoryStream(pramByte))
    {
	    CoreWebView2WebResourceRequest request = 
    this.browser.CoreWebView2.Environment.CreateWebResourceRequest("http://localhost:8080/test", "POST", stream, "Content- 
   Type: application/x-www-form-urlencoded");

	this.browser.CoreWebView2.NavigateWithWebResourceRequest(request);
}
`

**Comment by yildirimcagri** [comment]
Sorry, this got lost in the backlog :( ... We had fixed some bugs around this code, please let me know if you still need help with this. Also, if this is a UWP app, I'd recommend using InMemoryRandomAccessStream instead of MemoryStream as the WinRT MemoryStream has a [known issue](https://github.com/microsoft/CsWinRT/issues/670).

**Comment by lamposu** [comment]
This still have problem in WPF.
