### ISSUE TITLE
In VM, WebView2 showing as blank after minimizing and maximizing the window or when the focus is moved out

### ISSUE THREAD

**Issue by littyjoseph** [MicrosoftEdge/WebView2Feedback#1252]
**Description**

In the WPF application with a **WebView2** , when the window is minimized and then maximized I am seeing it as blank.
Also when I clicked on the link from WebView to open an external window as well, it shows as blank.

 I tried the same code in my physical system this issue is not there. I have added my VM and physical system configurations.

Can you please look into this issue as this is very annoying to the user.

**Version**
Microsoft Edge WebView2 Runtime :90.0.818.46
Nuget - Microsoft.Web.WebView2 => 1.0.818.41
Framework: .Net framework 4.8
OS:  Win10

**Repro Steps**
Add a wpf window with WebView2 and set source to some url. 
Run the application. Confirm the WebView is showing the content of the url.
Minimize the window
Maximize the window.

Actual result
    Blank Window

Expected Result
   It should show the WebView content

**Screenshots**

**Additional context**
Physical System Configuration
----------------------------------
![image](https://user-images.githubusercontent.com/83632807/117008329-3b3b0780-ad08-11eb-872b-d415636f5917.png)

VM Configuration
--------------------

![image](https://user-images.githubusercontent.com/83632807/117008786-b6042280-ad08-11eb-984c-bb818573fcc0.png)

**Comment by Florin-blz** [comment]
I'm having the same issue . Working on local computer, and when connected to a VM or WVD via Remote Desktop connection , after minimise the app and maximise (back to normal state) , the whole view in the controller is blank , until I click the view. 
It seems to be a RDP thing and have nothing to do with the system specs. The RDP handles the view different . 

The only solution I got it to not go blank is subscribing to event when the Window State  changed to normal ( from minimise to maximise) and force a reload of the content , which is not recommended because you'll loose the session if you have one, or take's up loading slow if it's a document , and involves data traffic also and so on.  Basically what the refresh button does on the browser. 

Another solution would be something to trigger redrawing the content, or re-render , not reload all the way. Tried all sorts of methods, like force scrolling , change focus from an element to another and back, resizing automatically, but no luck. nothing works , until you click somewhere random in the app, or even outside the app ( it's not a pattern ) . But again, this would be a solution fixing the effect , not the cause. 

It should not behave different in RDP  . It's very annoying for the user to have to figure out that he has to click random .

**Comment by champnic** [comment]
Thanks for the bug reports and details! This looks like the same issue as #1130 and we are currently working on a fix. The root cause seems to be when we use software rendering rather than hardware accelerated rendering, which is why you often see it on VM and RDP scenarios, and also for some specific graphics driver versions.

**Comment by littyjoseph** [comment]
Thanks for the update.
