### ISSUE TITLE
incognito feature for webView

### ISSUE THREAD

**Issue by gongalili** [MicrosoftEdge/WebView2Feedback#1253]
I need incognito support in order to avoid the IIS Windows Authentication with the credentials of the logged on user. Do you have any idea how can I do so?

**Comment by champnic** [comment]
We currently have a bug where credentials are being used from the logged on user even if the [AllowSingleSignOnUsingOSPrimaryAccount ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount?view=webview2-dotnet-1.0.818.41#Microsoft_Web_WebView2_Core_CoreWebView2EnvironmentOptions_AllowSingleSignOnUsingOSPrimaryAccount)property is not set, which is probably why you are seeing this (see #1125). By default we shouldn't be providing credentials. We recently fixed this in runtimes 91.0.864.0+ - can you give the latest Microsoft Edge Canary/Dev runtimes a try and see if your issue is resolved?

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
