### ISSUE TITLE
ICoreWebView2WebResourceRequestedEventArgs get_Response always null

### ISSUE THREAD

**Issue by omegakode** [MicrosoftEdge/WebView2Feedback#127]
It is supposed to be the server response?

[AB#25412716](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/25412716)

**Comment by david-risney** [comment]
Apologies, the documentation doesn't talk about this and needs to be updated. WebResourceRequested fires when the WebView is going to make an HTTP request before making that request. If the Response property is left null then the WebView will make the request and process the response as normal. Or you can fill in your own response via the Response property on the event args and the WebView will use that as the response instead of actually going to the network.

**Comment by omegakode** [comment]
I understand, thanks.

**Comment by champnic** [comment]
We have documentation that should cover WebResourceRequested in much more detail now:
Link to documentation: [Custom management of network requests - Microsoft Edge Development | Microsoft Docs](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webresourcerequested?tabs=dotnet)
Response: https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webresourcerequested?tabs=dotnet#what-you-can-do-with-headers
Diagram describes timeline of events: https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webresourcerequested?tabs=dotnet#sequence-for-modifying-requests

Thanks!
