### ISSUE TITLE
WebGPU support in Webview2?

### ISSUE THREAD

**Issue by geolehmann** [MicrosoftEdge/WebView2Feedback#1285]
Hello,
I wanted to ask if there are any plans for WebGPU support in WebView2? 

Thanks in advance!

**Comment by champnic** [comment]
We generally support what the Microsoft Edge Chromium platform supports. It looks like WebGPU is still in developer trials, but I would expect we probably would support this by default when it gets enabled:
https://www.chromestatus.com/feature/6213121689518080

If you can find a command line arg that turns this on for Chromium, that same arg will likely work for WebView2. You can pass in args using the AdditionalBrowserArguments:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.818.41#get_additionalbrowserarguments

If you do find a flag and give this a try, let me know how it goes!

**Comment by geolehmann** [comment]
Thanks for the answer, I´ll try that!

**Comment by champnic** [comment]
You could try downloading and running against Microsoft Edge Canary (Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1"); will tell WebView2 to use the least stable runtime) if it's a relatively new flag/feature. You may also want to try ` --enable-experimental-web-platform-features` and/or `--enable-unsafe-webgpu-service` (though I don't know specifically what those do). Otherwise, yes if you wait then that flag support should ship in a future stable runtime.
