### ISSUE TITLE
Missing Navigation Events in WebView2 for certain elements

### ISSUE THREAD

**Issue by bhe-gtk** [MicrosoftEdge/WebView2Feedback#1305]
For the image links at the bottom of this page no NavigationStarting/-Completed events are generated:

[https://contract.rolf-benz.com/index.php?id=81&L=0&tx_rbproductmanager_pi1%5Bproduct%5D=1141&tx_rbproductmanager_pi1%5Baction%5D=show&tx_rbproductmanager_pi1%5Bcontroller%5D=Product&cHash=337eb3ef87dc43162796bbdcb31fc66d](https://contract.rolf-benz.com/index.php?id=81&L=0&tx_rbproductmanager_pi1%5Bproduct%5D=1141&tx_rbproductmanager_pi1%5Baction%5D=show&tx_rbproductmanager_pi1%5Bcontroller%5D=Product&cHash=337eb3ef87dc43162796bbdcb31fc66d)

I seems to be related to the relative-path references used:

`<a href="uploads/tx_rbassetarchive/large/RolfBenz_009_CARA_005_large.jpg" download="RolfBenz_009_CARA_005 (print).jpg">`

It works with absolute URI:

`<a href="https://contract.rolf-benz.com/uploads/tx_rbassetarchive/large/RolfBenz_009_CARA_005_large.jpg" download="RolfBenz_009_CARA_005 (print).jpg">`

SDK: 1.0.664.37
Runtime: Stable 90.0.818.62
Framework: Win32
OS: Win10

[AB#33612801](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33612801)

**Comment by champnic** [comment]
@bhe-gtk Thanks for the bug report - I've added it to our backlog.

**Comment by yildirimcagri** [comment]
Hello @bhe-gtk, I'd like to investigate this issue now. Could you provide some updated repro steps, it seems the link is forwarding to the main page. Which image link would I click for this?

Thanks,
Cagri

**Comment by bhe-gtk** [comment]
Unfortunately the site changed. I could only find a similar situation here:
http://portal.rolf-benz.matrix.de/index.php?id=3&tx_rb_asset_archive_pi1%5Bmore%5D=1&tx_rb_asset_archive_pi1%5Btheme%5D=17&tx_rb_asset_archive_pi1%5Btype%5D=2&tx_rb_asset_archive_pi1%5Baction%5D=search&tx_rb_asset_archive_pi1%5Bcontroller%5D=Asset&cHash=43834969318afda07e48ca91319b0844
But these image are covered by the download event. Could only test it with the current version. It seems to work so far.

**Comment by yildirimcagri** [comment]
On the latest Edge Canary runtime, when I click the download icon under the images, I see that the WebView2 navigates to the full size version of the image and a full set of navigation events fire as expected since the WebView2 navigated to the image element. If the image was instead downloaded and WebView remained in the old page, we wouldn't expect to see the navigation events, but we should see the download events in that case. Let me know the version of your runtime if you are still not seeing the navigation events. I'll close this for now.

![image](https://user-images.githubusercontent.com/1124751/143332667-7b8346da-01b4-439c-9802-0b4ef4ab30a7.png)
