### ISSUE TITLE
The touch action does not work correctly on Windows 7 using a capacitive touchscreen

### ISSUE THREAD

**Issue by neidantaslopez** [MicrosoftEdge/WebView2Feedback#1313]
**Description**
The touch action does not work properly on Windows 7 using a capacitive touchscreen.
When clicking on a common button on an html page loaded in WebView2, the click event is only triggered after several random touch actions.
If we open the same page directly in the Microsoft Edge browser, the touch works correctly and the button responds to the touch every time.

Using the same computer and touchscreen but with Windows 10, the touchscreen works correctly.
The problem does not occur in Windows 7 if we use a resistive touchscreen.

**Version**
SDK: either 1.0.865-prerelease or 1.0.818.41 reproduce the same issue
Runtime: either Canary (92.0.894.0) or Fixed Version WebView2 Runtime 90.0.818.66 reproduce the same issue
Framework: WPF, .NET Framework 4.6.2
OS: Windows 7 Enterprise, Version 6.1 (Build 7601: Service Pack 1)
Computer: Dell Precision 5510 with capacitive touchscreen

**Repro Steps**
1. Load in WebView2 a simple HTML page with a button and in the onclick event call a javascript method that implements a counter and increases the value in a label on that same HTML page.
2. Perform the touch action on this button and note that the click event is not triggered;
3. Perform the touch action on this button many times and note that at some point the click event will be triggered and the counter will be increased.

[AB#33544639](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33544639)

**Comment by champnic** [comment]
Thanks for the bug report - I've added this bug to our backlog.

**Comment by Simon4638** [comment]
Hi Champnic:

Is there any update for this issue? Thanks a lot.

**Comment by champnic** [comment]
@Simon4638 No update yet. We haven't had a chance to look into this bug yet, sorry!

**Comment by Simon4638** [comment]
Hi Champnic,

Understood. Please look into this issue when you have a chance. I know you were busy. Thanks a lot.

**Comment by champnic** [comment]
@Simon4638 We've so far been unable to reproduce this issue. We don't have the specific hardware you mentioned, but have tried using Win7 VMs. Are you able to spin up a VM and see whether your sample app reproduces the issue there? If it does reproduce the issue, then it might be specific to something in the sample app. Otherwise, that would indicate we need actual hardware to reproduce the issue rather than a VM.

**Comment by fantasy0v0** [comment]
have same problem. reproduce requires a capacitive touch screen.

**Comment by neidantaslopez** [comment]
> @Simon4638 We've so far been unable to reproduce this issue. We don't have the specific hardware you mentioned, but have tried using Win7 VMs. Are you able to spin up a VM and see whether your sample app reproduces the issue there? If it does reproduce the issue, then it might be specific to something in the sample app. Otherwise, that would indicate we need actual hardware to reproduce the issue rather than a VM.

@champnic I've tested it both in VM and in hardware with a capacitive screen and Windows 7. The issue was only reproduced in the hardware.

**Comment by champnic** [comment]
Thanks both for confirming! We'll work on getting hardware setup to repro this.

**Comment by Simon4638** [comment]
@champnic  @neidantaslopez @fantasy0v0 Thanks a lot for all your help.

**Comment by jamesoli** [comment]
@neidantaslopez @fantasy0v0 @Simon4638 I took a look and this seems like an issue with WPF and windows 7. In Windows 7, WPF by default uses stylus input which is mutually exclusive to WM_TOUCH events. Have a look at the following documentation:

https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/dd901337(v=vs.90)

To get multi-touch to work with for WebView2 in a WPF application, you would need to put code in the linked documentation into your app to disable stylus input.

I suspect that touch seems to work with resistive screens because it might not be a generating WM_TOUCH events for resistive screens.

**Comment by neidantaslopez** [comment]
> @neidantaslopez @fantasy0v0 @Simon4638 I took a look and this seems like an issue with WPF and windows 7. In Windows 7, WPF by default uses stylus input which is mutually exclusive to WM_TOUCH events. Have a look at the following documentation:
> 
> https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/dd901337(v=vs.90)
> 
> To get multi-touch to work with for WebView2 in a WPF application, you would need to put code in the linked documentation into your app to disable stylus input.
> 
> I suspect that touch seems to work with resistive screens because it might not be a generating WM_TOUCH events for resistive screens.

It worked! Thank you!
