### ISSUE TITLE
Is Compatibility mode an option in WebView2

### ISSUE THREAD

**Issue by KarlaFranke** [MicrosoftEdge/WebView2Feedback#1371]
We have some webpages that need to be open in Edge using Microsoft Edge Compatibility.  Is there an option within WebView2 or do I need to use WebBrowser to display those webpages?

**Comment by KarlaFranke** [comment]
I did read similar threads about this such as #67, #440 and #818.   We have window applications that have automation with third party websites that will only work in IE Mode.  
If I use the WebBrowser control, will MS continue to updated until the EOF for IE Mode in Edge?

**Comment by champnic** [comment]
Correct - the WebBrowser control will continue to work after the IE Desktop Browser end of life in 2022, until about 2029. We do have #440 tracking adding IE mode support, but I don't anticipate we will get to that work anytime soon, and our recommendation is to switch between using WebView2 and WebBrowser if you still need IE support. Thanks!

**Comment by gg1975developer** [comment]
Hi,
could you help me to understand if the internet explorer application activex (  (https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752084(v=vs.85) ) will be supported after the deadline of june 2022?. The WebBrowser control has some limitations about the internet explorer mode used to render web pages as far as I have understoof from the documentation: it cannot render some pages as ie8 mode and some others as ie11 mode. Is it correct? There is a way with sitelist.xml or some API to switch the rendering mode dinamically inside the WebBrowser control in order to render web pages as ie8 and ie11? I've seen that using the registry you could setup the mode that webcontrol will use but it's a global configuration: you cannot manage a mix of the two ie modes. 
Thanks in advance
Best regards
