### ISSUE TITLE
Inline images using Navigate2 remain blank (about:blank#blocked)

### ISSUE THREAD

**Issue by ic2ic2** [MicrosoftEdge/WebView2Feedback#1379]
We are showing e-mails in the Webview2 by reading the HTML content and showing it with:

webView.NavigateToString(cHTML);
However, inline pictures (images which are part of the email itself) do not show despite they are being extracted in the %temp% directory. Copying the URL of the "broken image" symbol shows _about:blank#blocked._

I have added these 2 lines before the above line, but that doesn't change the situation:

string cTempPath = System.IO.Path.GetTempPath();
webView.CoreWebView2.SetVirtualHostNameToFolderMapping("test.editor", cTempPath,CoreWebView2HostResourceAccessKind.Allow);

How can I make the Webview2 display the images from the temp directory?

Dick

**Comment by ic2ic2** [comment]
One additional remark. If I save the HTML in the temp directory first and use webView.Source = new Uri(cTempHTML); I can display the image. But I rather use NavigateToString. 

The other solution is described in 
https://github.com/MicrosoftEdge/WebView2Feedback/blob/2f527d46ed31dc1928d64281b2b6dd6227b2140f/specs/HostResourceMapping.md

I was wondering why "assets" is used as 2nd parameter for SetVirtualHostNameToFolderMapping instead of a path. Using the exact code as in the example there you will get a Path not found exception...

Hopefully there's a solution to my question above, using NavigateToString.
Dick

**Comment by champnic** [comment]
How are the images being accessed in the email html? My guess is that this is a mixed-content limitation where the about:blank page can't load assets from disk in the manner you are currently using.

In the example usage, "assets" is the name of a folder whose path is relative to the app exe (so there's a folder `<pathToAppExe>\assets`), so I wouldn't expect that example to work for you unless you also had a folder named "assets" next to your app exe. Absolute folder paths are also allowed.

For the code you gave to work, you would need to be accessing the images in the HTML using an url like "https://test.editor/myImage.png". But otherwise that looks like the right code.

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
