### ISSUE TITLE
COMException while trying to initialize multiple CoreWebView2 environments using different options

### ISSUE THREAD

**Issue by carsonwilliamsdev** [MicrosoftEdge/WebView2Feedback#1421]
**Description**
I am trying to create a WPF app that displays multiple WebView2 browsers. The browsers are created dynamically and each one uses different CoreWebView2EnvironmentOptions, but I'm getting a generic COMException when calling EnsureCoreWebView2Async in certain situations.

**Version**
SDK: 1.0.864.35 (currently latest stable)
Runtime: 91.0.864.48
Framework: WPF
OS: Windows 10 Version 2004 (OS Build 19041.985

**Repro Steps**
1. Create two WebView2 browsers in code
2. Create two CoreWebView2EnvironmentOptions, one for each browser
3. Call EnsureCoreWebView2Async on each browser using their options
4. Set the Source on each browser and add them to a WPF window

If the environment options in step 2 are the same, it will work. If the options in step 2 are different, I get a COMException for the second browser in step 3.

Attached a basic WPF app to demonstrate: [WpfApp3.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6673714/WpfApp3.zip)

**Comment by champnic** [comment]
Hey @carsonwilliamsdev - Currently for a given user data folder (which is tied to the running browser process) each Environment/WebView2 that is created must have the same options. To workaround this issue you can specify separate user data folders, or use the same options.

In the example you gave, the first WebView2 would start the browser process without any debug port open. The second WebView2 would try to use the same browser process (because they share a user data folder) with a debug port, which fails because the process is already created.
