### ISSUE TITLE
How to handle otherwise unhandled exception with ProcessFailed

### ISSUE THREAD

**Issue by GunArm** [MicrosoftEdge/WebView2Feedback#1425]
I load a WebView2 instance in an initially hidden window and seeing an intermittent issue when the window is first unhidden (seemingly only once after the application is installed, although that doesn't make sense to me but whatever).  For a subset of users, some subset of the time, something fails before the NavigationCompleted event is fired in the hidden window.  And then when they trigger the window to be displayed, they get the following unhandled exception
(One of the environments where this issue occurs has WebView2 runtime 91.0.864.48)
```
System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I'm at a disadvantage troubleshooting/fixing this because I can't reproduce it on command (although it's not impossible through QA tedium to get it to *eventually* reproduce), and also because the stack trace does not point to the specific action in my local code which led to the exception bubbling up, in order to try to catch it there.  And I'm not sure what the idiom "Move focus" means, although I understand "GotFocus".

Anyway I have seen on issue #774 talk of using an event called ProcessFailed to potentially swallow the exception and provide a hook by which I can reinstantiate the control to continue execution in the case of a failure.  Normally I would just tinker with this until I figured it out but since I can't repro it on command it's hard to do iterative experimentation (and the notion of using an event to swallow an exception is unusual) so I'm wondering if anyone can provide information about what this process looks like in the event handler to:
1. Prevent the exception from being thrown unhandled and crash my application
2. dispose/reinitialize the component (I am using winforms)

If there is documentation somewhere about this I have overlooked that would be helpful

**Comment by GunArm** [comment]
On second thought, perhaps I misread this comment https://github.com/MicrosoftEdge/WebView2Feedback/issues/774#issuecomment-765802654 

> You can listen for this event and remove, nullify, or recreate the control upon the browser process crashing to avoid the COM exception you're seeing. The crash is coming from the implementation for the control so you'll have to dispose of it somehow.

The idea is to replace the crashed instance immediatly on ProcessFail, so that (under the theory that the exception comes not from the ProcessFail but a subsequent call after the ProcessFail) we can get ahead of the future action that would cause the exception?

**Comment by Syul968** [comment]
The exception in #774 was caused by the control's browser process unexpected termination leaving the underlying `CoreWebView2` in its "Closed" state. When the browser process supporting a control instance crashes, most functionality will be lost and calls to methods that depend on that process will report the exception. Since these calls can be made by the framework, the control needs to be disposed of and removed from the tree so the calls are not made.

The [ProcessFailed](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed?view=webview2-dotnet-1.0.902.49) event is raised as the control's `CoreWebView2` moves to the "Closed" state, which is why removing the instance when the event is raised prevents the trailing exceptions.

We made changes to both the WPF and WinForms controls so they catch browser process failures internally and stop forwarding these calls. The changes are available in SDKs `824-prerelease`/`818-release` and later. Could you confirm your application is using one of these versions?
