### ISSUE TITLE
C# Event AcceleratorKeyPressed Not Visible (.NET 4.8)

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftEdge/WebView2Feedback#1453]
**Description**
Event: AcceleratorKeyPressed Not Visible
WinForm .NET 4.8 / 
WebView2 1.0.864.35
RunTime 91.0.864.54

webView21.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled = false;
Working Fine. But Event AcceleratorKeyPressed  not visible.

**Comment by pmaytak** [comment]
@IrakliLomidze Do you mean that you get `'WebView2' does not contain a definition for 'AcceleratorKeyPressed'` error for that event? 
If so, I have the same issue then. `WebView2.AcceleratorKeyPressed` is missing since WV2 version `1.0.774.44`. This is for WinForms net461, netcoreapp3.1 and net5.0; runtime 91.0.864.54.

WebView2 team:
- Is `WebView2.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled` is the suggested workaround instead? PR #989 suggested `AcceleratorKeyPressed` should still exist.
- With `1.0.864.35` I tried setting `AreBrowserAcceleratorKeysEnabled` to false but get the error. (Let me know if I should create a separate issue for that).
![image](https://user-images.githubusercontent.com/34331512/123918599-e21ed700-d938-11eb-81ee-003b97123d40.png)

**Comment by IrakliLomidze** [comment]
webView21.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled = false;
Is working Fine:

But AcceleratorKeyPressed event is missing in the WinForm Control.
all other documented events are present.

**Comment by champnic** [comment]
In the WPF and Winforms controls you should listen to the `OnKeyDown` event instead for handling the accelerators.
Some info on this: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2?view=webview2-dotnet-1.0.864.35#remarks

Sorry for the confusion here. `WebView2.AcceleratorKeyPressed` does not exist By Design. `AcceleratorKeyPressed` is an event off of the CoreWebView2Controller class, which is used in Win32 or if you are creating your own .NET control (what we call "frameworkless") but if you are using the WPF or Winforms controls, then the controller is hidden and it's functionality is baked into those controls as appropriate for their respective frameworks (WPF or Winforms). 

To add to the confusion, we did have a dev who thought it was missing accidentally from the controls and so added the event, and this went out in a prerelease SDK before we caught and reverted it.

**Comment by duncangroenewald** [comment]
> 

Can someone please provide and example of how you capture key presses with WebView2. I just need to detect CTRL+A or ALT+A while the WebView2 has the focus but this seems to be difficult to achieve.

**Comment by Take-A-Byte** [comment]
@champnic What should we use in case of UWP?
