### ISSUE TITLE
XSL Transformations

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#1472]
At the moment I am getting around this issue by using C# to transform my XSML/XML into HTML and then navigating to the HTML. But when I was using IE I was able to use the XML link on my PC.

I understand that the webview2 does support xsl/xml but only if it is on a server. This is a limitation for me as the transformations for my app are due on the PC itself that runs my editor.

I can continue with my workaround but will be litigation be lifted?

**Comment by champnic** [comment]
Hey @ajtruckle - I assume you mean "limitation" and not "litigation"? Would you like me to add this as a feature request?

It sounds like you might be able to use the `--allow-file-access-from-files` browser command line arg to workaround this for now. Want to give that a try?

**Comment by ajtruckle** [comment]
Hi!

How can I try this command line switch with the WebView2 control? Thanks.

I did mean “limitation”.

Andy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by champnic** [comment]
Instead of using the `Source` property for initialization, you can create a CoreWebView2EnvironmentOptions with the additional browser arguments set:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.864.35#microsoft-web-webview2-core-corewebview2environmentoptions-additionalbrowserarguments
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.-ctor?view=webview2-dotnet-1.0.864.35

Then use that to create the CoreWebView2Environment with `CreateAsync(..., ..., envOptions)`:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.864.35

And then use the environment to initialize the WebView2 control using `EnsureCoreWebView2Async(env)`:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.ensurecorewebview2async?view=webview2-dotnet-1.0.864.35

You'll need to `await` on the Ensure call before interacting further with the WebView2, or listen to the `CoreWebView2InitializationCompleted` event.

**Comment by ajtruckle** [comment]
Thanks. I’ll see if I can do this. It may be worth adding it as a feature request. But let us see.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
Whilst the transformation approach was in C# the actual editor with the WebView2 is Visual C++ MFC. Will look at your links later today.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
I have got myself confused here. My  original browser code class already had this options variable, but it was set as `nullptr`. So I tried:

```
  /*ICoreWebView2EnvironmentOptions* options = nullptr; */
   auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
   CHECK_FAILURE(options->put_AdditionalBrowserArguments(L"--allow-file-access-from-files"));


   HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
      subFolder, 
      appData,
      options,
      Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
         this, 
         &CWebBrowser::OnCreateEnvironmentCompleted).Get());
```

I used `Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>` because that it what your samples show but the `CreateCoreWebView2EnvironmentWithOptions` does not like my `options` parameter. What is the correct way to create my `ICoreWebView2EnvironmentOptions *` pointer object so I can pass it?

**Comment by ajtruckle** [comment]
Go it!

```
   auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
   CHECK_FAILURE(options->put_AdditionalBrowserArguments(L"--allow-file-access-from-files"));


   HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
      subFolder, 
      appData,
      options.Get(),
      Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
         this, 
         &CWebBrowser::OnCreateEnvironmentCompleted).Get());
```

It does work and this seems a viable solution for this issue. Let me now try it in my real application.

**Comment by ajtruckle** [comment]
It works OK! Great!

Question:

Is it OK to use `std::make_unique` instead of `Microsoft::WRL::Make` to create the options object? I ask because the core web browser wrapper I am using uses `m_pWebBrowser = std::make_unique<CWebBrowser>();` so I wondered if I can do the same here for consistency.

**Comment by champnic** [comment]
I believe you need to use WRL here to properly instantiate the objects.

I'm going to mark this item as closed - glad you got it working! Feel free to continue asking questions though :)
