### ISSUE TITLE
Should AddScriptToExecuteOnDocumentCreatedAsync method work for popups?

### ISSUE THREAD

**Issue by anovik** [MicrosoftEdge/WebView2Feedback#1503]
I have the following question about AddScriptToExecuteOnDocumentCreatedAsync() method:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addscripttoexecuteondocumentcreatedasync?view=webview2-dotnet-1.0.864.35

From MSDN: The injected script will apply to all future top level document and child frame navigations 

Is it applicable for the popups, i.e. for child windows for which NewWindow property of CoreWebView2NewWindowRequestedEventArgs is set?

I mean if the javascript will be injected into the popup?

Framework: UWP
Version: Reunion 0.8.0 - prerelease

**Comment by champnic** [comment]
Hey @anovik - Currently no, it will not automatically be applied to popups, including default new window handling and if you provide a new WebView2 for the new window. If you are specifying a new WebView2 then this is By Design, but it's possible we should do this by default if no new WebView2 is specified. I can open as a feature request if you'd like?

Currently the workaround would be to listen to NewWindowRequested and give it a new WebView2 to use, and call "AddScript..." on that WebView2.

**Comment by anovik** [comment]
OK, I see. This behavior is acceptable for me, so I will close this issue for now.
