### ISSUE TITLE
Enhanced/built-in support for Targets/Sessions

### ISSUE THREAD

**Issue by Dudulle** [MicrosoftEdge/WebView2Feedback#1585]
**Is your feature request related to a problem? Please describe.**
There is currently no explicit support for Targets and Sessions for DevTools methods and events.
Supporting them would help to send commands, run script, and listen to events in cross domain iframes and maybe other areas. This would solve #670 for example.
The only way to do so for now is to explicitly create a session for those targets and use `Target.sendMessageToTarget` and `Target.receivedMessageFromTarget` and pass the session ID to send messages and listen to responses and events from those targets.

**Describe the solution you'd like and alternatives you've considered**
Adding a `sessionId` or session/target (or maybe just ICoreWebView2Frame for iframes) object as parameter to `CallDevToolsProtocolMethod`, `GetDevToolsProtocolEventReceiver`, and `ExecuteScript` would already be helpful. In the background this could either call `Target.sendMessageToTarget` and read the session ID in `Target.receivedMessageFromTarget`, or simply specify/read the session ID in the message when using flattened mode.
 
This could be further enhanced by adding support for those sessions in other methods and events, such as 'Navigate' or 'WebResourceRequested'

I'm not sure how everything is handled in the background now, but I see popup windows are represented as a ICoreWebView2 object. Maybe allowing the creation of an ICoreWebView2 object from a session, target, or frame could be an alternative too?

**Comment by champnic** [comment]
Hey @Dudulle - Thanks for the feature request. This is a great idea, and I believe we are beginning to implement this right now. We are working on an ICoreWebView2Frame, and rather than passing that in to all of our other functions as a parameter, instead we'll expose those functions on the ICoreWebView2Frame. So for example instead of `ExecuteScript(script, iframe)` it would look like `wvFrame->ExecuteScript(script)`. We are tracking requests for APIs to bring to the iframe in #670, #139, #900, and #1105. If there's an API you need that we haven't planned yet please let me know here and I can add that scenario to our backlog. Thanks!
