### ISSUE TITLE
WebView ContextMenu is marked Read Only - Why? 

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#1625]
In the latest .NET control I now get an error that `ContextMenu` is read only:

![image](https://user-images.githubusercontent.com/1374013/128648009-59d341dd-704b-44f2-ab06-a7711ad79a46.png)

Not sure why this is as you can still cast to `FrameworkElement` and it then works:

```cs
 // This works
 ((FrameworkElement)Window.WebBrowser).ContextMenu = ContextMenu;
```

This seems a pointless readonly setting that also seems to prevent XAML from creating an inline, declarative context menu.

This is for the WPF control with `1.0.902.49`

**Comment by champnic** [comment]
@RickStrahl Hey Rick,

I believe this was done because the normal ContextMenu functionality doesn't work in the WebView2 WPF control. Instead we are finishing up a custom context menu API for changing or replacing the regular web context menu:
https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ContextMenuRequested.md

Was the ContextMenu property working for you before? What was your scenario?

**Comment by RickStrahl** [comment]
Nooooooo - please no.

The use case is that **i want to handle the context menu in WPF**. I can control the context menu behavior in the browser if necessary by turning it of via the `oncontextmenu` event or I can let the Chromium menu fire.

What use case? Are you kidding? Everything?

Application context sensitive context menus:

In actual browser preview (things like opening OS specific options, toggling UI views, editing templates)

![image](https://user-images.githubusercontent.com/1374013/129394834-9bbd1529-9144-4bf0-8462-2151d750cbbd.png)

Truly context sensitive operations like spell checking suggestions in this case:

![image](https://user-images.githubusercontent.com/1374013/129394984-f4dab56b-543e-408f-a64a-04befe43a779.png)

This is **much easier to do in WPF** by creating a context menu on the fly, than having to deal with it inside DOM code!

Whatever you do please don't kill the easy abillity to pop over a host context menu!!!

**Comment by RickStrahl** [comment]
Ok so maybe I'm overreacting. I'm actually taking another look at my menu code and found out that I'm just creating a new context menu and overlaying it at the mouse position rather than using the context menu instance of the WebView control.

That said - **it does work** if assign the context menu to the WebBrowser control using `FrameworkElement` cast, but I think the issue is that you still need to explicitly provide the positioning as the browser's mouse position isn't bubbled up to WPF. So it works but unless you expicitly set the MP the Context menu is in the wrong place.

So - assuming for a second you take the functionality away completely this should still work:

```cs
public EditorContextMenu()
{
    Model = mmApp.Model;
    ContextMenu = new ContextMenu();

}

public void Show()
{
    if (ContextMenu != null)
    {
        Model.ActiveEditor.SetMarkdownMonsterWindowFocus();  // force focus out WebView

        ContextMenu.PlacementTarget = Model.ActiveEditor.EditorHandler.WebBrowser;
        ContextMenu.Placement = System.Windows.Controls.Primitives.PlacementMode.MousePoint;

        ContextMenu.Focus();
        ContextMenu.IsOpen = true;

        var item = ContextMenu.Items[0] as MenuItem;
        item.Focus();
    }
}
```

In this code the context menu is an unattached context menu and the placement is put on the WebBrowser and that seems to work just fine.


As long as this works I suppose there's no problem. 

Just please make sure there is an easy way to surpress the default context menu (I do that now in JavaScript by NOPing the `contextmenu` event).

**Comment by RickStrahl** [comment]
@champnic  You asked for context about the context menu.

In Markdown Monster I use native menus ontop of my WebView controls:

This one is essentially a replacement for the native menu with similar features, but a number of things that are custom:

![image](https://user-images.githubusercontent.com/1374013/129397663-3788e8c1-f6c5-4b7a-930c-893fd9da3c84.png)

This one in the editor is custom context sensitive in that provides spell checking hints:

![image](https://user-images.githubusercontent.com/1374013/129397720-34924f3f-05d0-4045-8ded-4a2b8a8bb63a.png)

The point is that these menus look a lot nicer and more consistent with the application than the native Chromium menu would look. And you can see some of the advanced features like (Show Developer Tools) are actually exposed on the WPF menu as well. As long as those types of things are available I see this as a much cleaner integration for most applications (unless you create HTML specific developer tools that expect the full Chromium experience).

**Comment by champnic** [comment]
I saw the email notification of your first response - I'm glad things aren't that dire! I originally asked because my understanding was that the mouse clicks in the WebView2 area wouldn't ever get handled on the WPF side (instead always getting handled by the WebView2) and so a ContextMenu would never work correctly. Thus I was surprised this was an issue and wanted to learn more about how you were currently using it today - I didn't mean to imply your scenarios are invalid or that we aren't supporting context menus. I assume you are capturing the mouse events in JS and then sending a message to your app to show the context menu?

I 100% support and understand that app's want to use their own context menus - that's the reason we are putting together a new API for custom context menus, to be able to support this without the app having to do anything with the DOM. Part of the proposed design is indeed allowing the app to draw it's own completely custom context menu and displaying it however they like, then sending the response back to the WebView2 to do the command (if it's a browser command) or handling the response within the app (if not a browser command).

I believe your scenario with a detached ContextMenu will continue to work.

I'm going to close this issue, but please let me know if you have other questions, want further clarification, or otherwise would like me to reopen this. Thanks!

**Comment by ekhcentrics** [comment]
We also were creating a context menu simliar to RickStrahl & were suprised and confused when updating to the latest version & the .ContextMenu property was now readonly.
