### ISSUE TITLE
Tip: WebView 1 works better than WebView2 

### ISSUE THREAD

**Issue by cnmade** [MicrosoftEdge/WebView2Feedback#1668]
1. WebView 1 is smaller than WebView2,  WebView1 based app only about 139MB file size. but WebView2 reach 320MB file size.
2. The memory consume WebView 1 is less than WebView2, WebView2 can take 150MB - 220MB memory , But WebView1 only take  46MB
![image](https://user-images.githubusercontent.com/278153/130207691-9b60f083-0b50-4092-b638-ce8d0b0043e6.png)
3. Developer friendly package WebView1, The WebView2 need more step to package runtime with my apps, I can not figure out how to easy to package the runtime into my app.

**Comment by cnmade** [comment]
WebView2 totally failed compare WebView 1. Useless.
I will pin on webview 1.

**Comment by champnic** [comment]
WebView1 is built on an older web rendering engine that is not longer updated and slowly becoming less standards compliant. WebView2 is based on Microsoft Edge/Chromium rendering engine and will always stay up to date.

For your point 1), WebView2 uses a single shared evergreen runtime, so will only reach that size per app (similar to Electron) if you choose to go with the Fixed Version runtime, which is why we don't recommend that model over evergreen.

2) Memory usage is site dependent, but yes, Microsoft Edge/Chromium generally uses more memory than the older EdgeHTML, but is also more fully-featured and standards compliant.

3) We have documentation and examples of packaging available:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps

In general though, we recognize that WebView2 may not work for everyone's needs, and there are viable alternatives such as WebView1 that you mention. However, this is not a WebView2 tip and so I'm going to close this issue. Thanks!
