### ISSUE TITLE
When Using Webview2 login to google account

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1669]
.net 4.8 framework
when logging in to google account i get error not safe to login error

![Schermafbeelding 2021-08-20 113248](https://user-images.githubusercontent.com/53493418/130213062-b21c4efc-5183-4983-9679-b9b880578a70.png)

**Comment by jarno9981** [comment]
Latest webview 2 version  no pre-release version

**Comment by da-vics** [comment]
this is a know issue. The problem is that google just updated there security policy

**Comment by brasten** [comment]
Is this the best place to track this issue? Our Office Add-in is suddenly unusable for many of our customers so I'm looking for the best place to be kept in the loop on what's happening with this.

**Comment by da-vics** [comment]
not at all follow this https://github.com/MicrosoftEdge/WebView2Feedback/issues/1647

**Comment by jarno9981** [comment]
@brasten    i hope it will by fixed main reason why i swichted from cef sharp to webview2 to login to google accounts and now webview2 is broken to i angry after putting 40hours work in webview2 app and now google account is unusable 😶😑😶😑😶

**Comment by jarno9981** [comment]
@champnic   please fix this bug it big problem

**Comment by da-vics** [comment]
I don't think so. it's not from WebView. it's a recent google update

**Comment by champnic** [comment]
Indeed this is due to a policy change for Google auth - for security reasons they are disabling logging in within any webview, including WebView2. As mentioned above please see #1647 for more info. Unfortunately we don't think there are great workarounds for this issue, but we are trying to come up with solutions, for example developing a "System WebView" which gives the dev fewer controls, but allows Google to trust it for logging in.

Here's Google's announcement: https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html
