### ISSUE TITLE
New tooltip style

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/WebView2Feedback#1677]
Currently, WebView2 has a tooltip style which don't really match Windows 11/WinUI 2.6. Edge is now updating the context menus, so I think the same could be done for tooltips.

![v1](https://user-images.githubusercontent.com/84711285/130333715-226891ca-05fe-4c87-adf4-2f3a7332f319.png) ![v2](https://user-images.githubusercontent.com/84711285/130333716-0888d9bb-726b-46f7-a337-4a2729c11098.png) ![2 6](https://user-images.githubusercontent.com/84711285/130333714-698b0504-6d45-4c85-8921-b9e7f24e2495.png)
From left to right: WebView, WebView2, WinUI 2.6.

It would be better if WebView2 could actually use the native tooltips offered by each platform, rather than having one with the Windows style everywhere.

**Comment by champnic** [comment]
Hey @gabrielconl - We match the browser's tooltip behavior and style and are unlikely to do work here only for WebView2. If you want you can leave browser feedback in Edge using the Feedback Tool (shift + alt + i). Thanks!

What we would do on the WebView2 side would be to provide an API for when a tooltip wants to be displayed so that the app could do it instead in whatever styling they wanted. Is that something you're interested in?

**Comment by gabrielconl** [comment]
I think the API would be a good option, but I'm not sure how it would work in practice. Could it be done automatically, depending on the platform where WebView2 is used? The goal is to not need to make your own tooltips.

**Comment by victorhuangwq** [comment]
We will track this as part of https://github.com/MicrosoftEdge/WebView2Feedback/issues/3826. Closing this issue
