### ISSUE TITLE
add_NewWindowRequested does not handle Shift and middle mouse click

### ISSUE THREAD

**Issue by TcT2k** [MicrosoftEdge/WebView2Feedback#168]
While opening new windows via the context menu has been fixed in the latest release (see #108 
Using Shift+Left Mouse Click or Middle mouse click still opens a new window without triggering the new window event.

I would expect the `NewWindowRequested` event to be triggered or at have another mechanism to detect and/or deny such actions.

[AB#26187414](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26187414)

**Comment by ukandrewc** [comment]
While we're on NewWindowRequested, target doesn't seem to be available anywhere.

**Comment by david-risney** [comment]
Thanks @TcT2k I would also expect that. We'll look into it.

@ukandrewc, that sounds like a feature request. At the point that we're firing a NewWindowRequested we've already interpreted target and figured out that we need to handle the navigation in a new window. Do you need to do additional work on the target?

**Comment by ukandrewc** [comment]
@david-risney, yes. route it to a tab of the same name, if it's already open.
It can be done getting the target from the DOM, when a link is clicked and patching window.open, but it would be great if **NewWindowRequested** was called before you handled it, with target as an additional property of **NewWindowRequestedEventArgs**. Thanks

**Comment by ukandrewc** [comment]
Just thought, unless you would route to an existing target if there is one?

**Comment by david-risney** [comment]
Yes we currently respect the target and route to the existing WebView2 if there is already one and otherwise can end up firing the NewWindowRequested event. 

For example, if in webview A in script you do `window.open(url1, "exampleTargetName")` then webview A will fire NewWindowRequested event. If you provide a new WebView2 webview B in that event to be the new window, then webview B will be used to navigate to url1. Then back in webview A you do `window.open(url2, "exampleTargetName")` webview B will navigate to url2 without NewWindowRequested firing.

Did you want the target so that you could handle it correctly like described above, or are you trying to do some custom handling of the target?

**Comment by ukandrewc** [comment]
That workflow is just what we need for our tabbed browser.  The only thing that may be useful, is to have the **target** in **NewWindowRequestedEventArgs**.

**Comment by TcT2k** [comment]
@david-risney The middle mouse click issue is still not resolved in the GA version

**Comment by pagoe-msft** [comment]
Hi Everyone,

This issue has been resolved in the [1.0.707-prerelease](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#10707-prerelease) package.

**Comment by TcT2k** [comment]
Just tested with Edge canary, and can confirm it works. Thanks.
