### ISSUE TITLE
Windows Application crashes randomly

### ISSUE THREAD

**Issue by andrei-ai** [MicrosoftEdge/WebView2Feedback#1681]
**Description**
Windows Application crashes randomly. 

Callstack:

{InitializeAsync}: WebView2 browser version: 90.0.818.66
256041582824 08/03/21 11:07:15.397 t@03052 DML dus.cpp(392){void __cdecl dus_trc_flush(void)}:
256043218094 08/03/21 11:07:17.032 t@05776 dus IProcess.cs(42){Application_ThreadException}: Fatal exception of type: System.Runtime.InteropServices.COMException
256044505204 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}: System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
256044505231 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}:    at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
256044505244 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}:    at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
256044505257 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}:    at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
256044505268 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}:    at System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
256044505280 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}:    at System.Windows.Forms.Control.WmSetFocus(Message& m)
256044505291 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}:    at System.Windows.Forms.Control.WndProc(Message& m)
256044505303 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}:    at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
256044505314 08/03/21 11:07:18.319 t@05776 dus IProcess.cs(42){Application_ThreadException}:    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Version**
SDK: 1.0.818.41
Runtime: fixed version 90.0.818.66
Framework: WinForms C#
OS: Win10

**Repro Steps**
It crashes randomly. I didn't find out the repro steps.

[AB#38991398](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38991398)

**Comment by champnic** [comment]
Hey @andrei-ai - Unfortunately there's not much we can do about this specific issue with this info and no repro steps. It's possible the underlying runtime crash was fixed in a newer version of the runtime.

If you want to avoid the app crashing, you can listen to the CoreWebView2.ProcessFailed event and recreate the WebView2 when it happens. Thanks!

**Comment by champnic** [comment]
This is available for testing in 1.0.1243-prerelease SDK. Thanks!
(Note: This SDK has been deprecated due to compat issues with the StatusBarTextChanged API, but should be safe to use if you don't use that API. See here for more info: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2414#issuecomment-1116335991)
