### ISSUE TITLE
PREVIEW 6 Disables Context menu

### ISSUE THREAD

**Issue by K-Benaissa** [MicrosoftEdge/WebView2Feedback#1694]
Hi,

With the last preview version (net 6). We can disable contextual menu, but it disable the html controls contextual menu too. so impossible to select and copy a text.
How disable THE BROWSER menu and keep native control menus.

Regards,

**Comment by K-Benaissa** [comment]
Hi
Thank you. But as I said before when I disable the menu using settings it disables all right click menu. So we can't open context menu of an input or text field (famous copy paste) or any other menu.
Actually I use chromium in net and it disables browser menu dev tools zooming ... but html native menu are working. So without this I can't switch to webview

**Comment by champnic** [comment]
Gotcha - within the context of a WebView2 all of those right-click menus are context menus and get disabled with the setting. This is by design currently.

We are working on a new API that would allow more detailed control over context menus, including disabling specific ones, adding/removing menu items, etc. You can see details here: https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ContextMenuRequested.md

We are using #80 to track this work. Thanks!
