### ISSUE TITLE
Need help with WebResourceRequest and CSS/XSLT StyleSheets

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebView2Feedback#172]
We are using an own HTML protocol in our application and want to display several information with the Edge (WebView2).

I managed so far to use our protocol (let's say it looks something like this: 'myProt:**doc*File') in 'normal' HTML code like e.g.:

`<a href="myProt:*File.txt">Link to an internal TXT file</a>`

But right now I'm struggeling with our protocol syntax in StyleSheet references.
The callback of ICoreWebView2WebResourceRequestedEventHandler is not executed.

For example in XML:

```
<?xml version="1.0" encoding="UTF-16"?>
<?xml-stylesheet type="text/xsl" href="myProt:*File.xslt" ?>
```

..or in HTML:

```
<html>
  <head>
    <link rel="stylesheet" href="myProt:*File.css">
  </head>
  <body>
    Test
  </body>
</html>
```

I already have the start-parameter '--allow-file-access-from-files' set during the call of CreateCoreWebView2EnvironmentWithDetails(), but it doesn't do the job as I expect it.

Does anyone can tell me, if it is possible at all to refer to StyleSheets by Web-Protocol, or has any clue for me how to manage this?

Thanks in advance

[AB#35541496](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35541496)

**Comment by david-risney** [comment]
Great question! We don't currently have support for custom URI schemes like 'myprot' but is something we're looking into.

As a workaround you might be able to do 'https://myprot/File.css' and then in the WebResourceRequested event look for https://myprot/ and respond with appropriate content based on the path of the URI.

**Comment by MarkusSchreiner** [comment]
Hi David

Thanks for your answer - but I have now found a way to make my custom URI scheme work for StyleSheets as well.

I looked through the List of Chromium Command Line Switches (from https://peter.sh/experiments/chromium-command-line-switches/), and found the switch

`--disable-web-security`

If this is set, the requested style sheets (both CSS and XSLT) work.
It's a bit overdone to set this switch, but until Edge officially supports these requests, I'll have to live with it.

Your suggestion with the https:// workaround is good, but unfortunately I cannot implement it. We are currently exchanging Internet Explorer for Edge in our application, and must remain backwards-compatible in any case.

Until when can I expect that all WebResourceRequests are officially supported by Edge?
I know you can't see into the future either, but maybe you can give a rough time frame?

Thank you, and best regards

**Comment by david-risney** [comment]
Ah, sorry I don't have any other workaround ideas.

I don't have a time frame for that feature request at the moment. We can provide more info about the feature request here in the future.

**Comment by wusyong** [comment]
Hello, is there any progress or news on custom protocol/url scheme registration?
Because we are still using some workaround like `https://custom.protocol.localhost/` in our use case and this still causes a few troubles from time to time.
Would be glad we have such API to serve this.

**Comment by maurawinstanley** [comment]
Thanks everyone for the feedback, we are starting to look into custom URI schemes again.  
One of the places we draw inspiration from is the equivalent feature EdgeHTML WebView, where WebView essentially fires an event when we see a scheme we do not recognize, and the host can do whatever logic they want in the event handler - [Reference doc](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.unsupportedurischemeidentified?view=winrt-20348).

Would this provide the support you are looking for, for custom URI schemes? If this event/handler was provided would you still need WebResourceRequested to fire for custom URI schemes? 

Thanks.

**Comment by liminzhu** [comment]
Hi folks! As @maurawinstanley mentioned we're currently working on custom protocol and it will looks similar to EdgeHTML's equivalent feature where you get an event when webview2 encounters an unrecognized protocol, and you can handle the event as appropriate. There area few things that planned to be exposed in the event handler - 
* Uri
* IsUserInitiated
* IsRedirected
* NavigationId
* Handled (if true, then we assume the host handled the event and wv2 will cancel the original navigation; otherwise the original passes through)
* HandleDialog (if true, webview2 suppress the browser app protocol prompt if the protocol is a registered app protocol, e.g. msteams://)

Would love some feedback on whether approach solves your scenario and whether these info is enough or developers would want access to additional information/parameter as well in the event handler.

**Comment by wusyong** [comment]
Thanks for the progress update! It looks promising. One thing about the argument in event handler I would like to see is same properties as [`CoreWebView2WebResourceRequestedEventArgs`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webresourcerequestedeventargs?view=webview2-dotnet-1.0.902.49) has. So we could get the type of request and set the response instead of just getting a string of URI.

**Comment by MarkusSchreiner** [comment]
Sounds good - I would agree with  wusyong's suggestion.

**Comment by maurawinstanley** [comment]
@MarkusSchreiner thanks for the input, we are planning on having this event fire separately with these event args, and the WebResourceRequested we are planning to have fire for custom URI schemes in the future. For this event separate of WebResourceRequested do these event args fit your scenario or are there additional ones you would like to see?

**Comment by MarkusSchreiner** [comment]
As far as I can estimate, the parameters mentioned would be sufficient for me.

**Comment by wusyong** [comment]
@maurawinstanley If WebResourceRequested can still fire for custom URI schemes, I think it could fit my scenario. Thank you.
We want to get the header of the request just like in HTTP requests.

**Comment by leaanthony** [comment]
@champnic any updates on this? Thanks

**Comment by champnic** [comment]
Work is progressing on this and is currently in pull request. Thanks!

**Comment by fedeazzato** [comment]
> Work is progressing on this and is currently in pull request. Thanks!

This is great news! Can you provide an estimate on when will it be available as a stable release in [nuget.org](https://www.nuget.org/packages/Microsoft.Web.WebView2)?

**Comment by champnic** [comment]
It looks like it's a runtime change (and not an SDK change) so you won't need to upgrade the SDK through nuget. Currently it looks like it will land in stable around the end of April (subject to change, as it hasn't been checked in yet).

**Comment by fedeazzato** [comment]
Thanks for the info. I'm a bit confused. I thought this issue was about support for handling custom schemes, and that would involve exposing new events in the SDK.

Maybe I miss read the thread.

**Comment by champnic** [comment]
It should use the existing WebResourceRequested event. Although now that I'm looking closer I believe there will be a new API for registering a custom protocol, so you will need to update the package. In that case the release date will likely be a month later (it will be in prerelease for a month, and then release package the following month).

**Comment by fedeazzato** [comment]
Thanks for the update!

**Comment by SureshkPerumal** [comment]
@champnic ,
Is there any update on release date for this issue

Thanks

**Comment by yildirimcagri** [comment]
Hi, this feature is released. Please see [https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2customschemeregistration?view=webview2-winrt-1.0.1369-prerelease](CoreWebView2CustomSchemeRegistration class) and sample app CustomSchemeRegistration scenario for more details.

**Comment by leaanthony** [comment]
@stffabi

**Comment by otakubeam** [comment]
Hey there!

Saw that the custom scheme support via CoreWebView2CustomSchemeRegistration is introduced in 1.0.1587.40. Since Windows 7 is retired now (as of SDK version 1.0.1519.0), just wondering: can I make this work on windows 7 SP1 (or later)?

Any workarounds or alternatives for handling custom protocols on older systems? We specifically need to load resources via WebResourceRequested event. Will windows 7 work with prerelease SDK (released just prior to win7 deprecation)?
