### ISSUE TITLE
WebResourceRequest is not executed for custom URI schemes in <iframe>

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebView2Feedback#173]
I have found the same problem with custom URI schemes as in issue #172 when they are used in an iframe:
example:
`<iframe src="myProt:*AnotherPage.html"></iframe>`

Also in this case the WebResourceRequest is not executed; setting the switches
`--allow-file-access-from-files`
and/or
`--disable-web-security`
 does not help at this point.

Although I can intercept the loading of this frame with the ICoreWebView2NavigationStartingEventHandler, but I have no possibility to convert the URI into a corresponding real path; in this callback I don't have access to a any Response-object.

Any suggestion for this case?

[AB#27223790](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27223790)

**Comment by david-risney** [comment]
Yes, we don't support custom URI schemes whether in an iframe or otherwise.

If you know the iframe you could cancel the navigation and then inject script to navigate the iframe to a file URI. But the navigation event doesn't have an indication of which iframe so you would need to know that on your own somehow.

**Comment by MarkusSchreiner** [comment]
Ok..

I think it would be important to support custom URI schemes.
Is the support planned in the near future?

**Comment by progsung** [comment]
Any update?
"WebResourceRequest for custom URI schemes" is an important feature.
Is the support planned in the near future?

**Comment by champnic** [comment]
Support is planned, but probably not for another couple releases.

**Comment by champnic** [comment]
Are you mostly using this for easy access of local file resources? If so we have a feature releasing sooner that may help. Details here: https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/HostResourceMapping.md

**Comment by MarkusSchreiner** [comment]
No, I want to use the custom URIs to parse them and poll the corresponding resources from a database.

**Comment by romanan** [comment]
+1 for custom protocol scheme support.
The application I am porting over from CEF has a custom scheme handler to handle local file access.  I will try using the folder mapping API for now, but it looks a bit cumbersome since the file resource is an arbitrary location on the client's hard-drive (not a known folder), and we can have multiple file locations at the same time.  We'd also like the same HTML to work on the Mac (Webkit) as well, which does not support file mapping, but does support custom schemes

**Comment by romanan** [comment]
@champnic Just want to check if this is on the radar.  I see that the VirtualHosting API is now promoted to stable in the latest prerelease (1.0.781-prerelease) so I will start working with that first, but please see the above comment on why I'd still prefer a custom scheme handler.

FWIW, our previous implementation in CEF used CefSchemeRegistrar::AddCustomScheme to register a scheme handler and CefStreamReader::CreateForFile to provide the resource stream when the handler was called

**Comment by champnic** [comment]
Hey @romanan - yes this is still on our radar, and relatively high priority on our backlog right now.

**Comment by romanan** [comment]
Great news, thanks!

**Comment by MarkusSchreiner** [comment]
Yes, very good that this issue is being addressed!

**Comment by Curve** [comment]
Is there any progress on this? 
I need support for this feature too

**Comment by maurawinstanley** [comment]
Thanks everyone for the feedback, we are starting to look into custom URI schemes again.  
One of the places we draw inspiration from is the equivalent feature EdgeHTML WebView, where WebView essentially fires an event when we see a scheme we do not recognize, and the host can do whatever logic they want in the event handler. 
[Reference doc](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.unsupportedurischemeidentified?view=winrt-20348)

Would this provide the support you are looking for, for custom URI schemes? If this event/handler was provided would you still need WebResourceRequested to fire for custom URI schemes? 

Thanks.

**Comment by NewPagodi** [comment]
What I would like to see in custom URI schemes is something like [RegisterNameSpace ](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767759(v=vs.85)) from the old mshtml/ie api.  This function lets you associate a scheme with an [IInternetProtocol](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767883(v=vs.85)) object.  (There are a few steps in between that I've left out, but that's the basic idea.)

The net result is that if I register the scheme "mycustomprotocol" in an application, when an mshtml object in my application trues to load content with a url such as "mycustomprotocol://mycustompage.html", it then call the read method for the associated IInternetProtocol object.  The read method of that IInternetProtocol will be implemented  to serve the content back to the mshtml object in whetever manner is appropriate for the application.

This was a very useful feature with the old api.  Is it possible to implement this type of functionality in the webview2 system?

**Comment by liminzhu** [comment]
Hi folks! As @maurawinstanley mentioned we're currently working on custom protocol and it will looks similar to EdgeHTML's equivalent feature where you get an event when webview2 encounters an unrecognized protocol, and you can handle the event as appropriate. There area few things that planned to be exposed in the event handler - 
* Uri
* IsUserInitiated
* IsRedirected
* NavigationId
* Handled (if true, then we assume the host handled the event and wv2 will cancel the original navigation; otherwise the original passes through)
* HandleDialog (if true, webview2 suppress the browser app protocol prompt if the protocol is a registered app protocol, e.g. msteams://)

Would love some feedback on whether approach solves your scenario and whether these info is enough or developers would want access to additional information/parameter as well in the event handler.

**Comment by MarkusSchreiner** [comment]
As in issue  #172 (comment of wusyong), perhaps it would be best to have the same properties as in CoreWebView2WebResourceRequestedEventArgs

**Comment by maurawinstanley** [comment]
@MarkusSchreiner thanks for the input, we are planning on having this event fire separately with these event args, and the WebResourceRequested we are planning to have fire for custom URI schemes in the future.

**Comment by leaanthony** [comment]
@champnic any updates on this? Thanks.

**Comment by Rezakarimi66** [comment]
@champnic @maurawinstanley Any update on this?

**Comment by champnic** [comment]
This has shipped and should also work in iframes. see https://github.com/MicrosoftEdge/WebView2Feedback/issues/172#issuecomment-1273437696

Thanks!

**Comment by debojit08** [comment]
Hi @champnic @david-risney 

I'm using the file:// protocol in my win32 app to Navigate, but with the file protocol, I'm getting a cross-origin platform error since I have an iframe used in one HTML file.  I tried enabling the flag "allow-file-access-from-files" or "--disable-web-security" that didn't help. If I use the HTTP protocol, I don't see the cross-origin platform error, but I am restricted from using HTTP. 

Does custom URI help to resolve the error? if so how to create custom protocol, I tried following [CoreWebView2CustomSchemeRegistration](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2customschemeregistration?view=webview2-1.0.2903.40&utm_source=chatgpt.com#get_schemename). didn't help also.

Thanks!
