### ISSUE TITLE
Cookie is not working on wpf webview2

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftEdge/WebView2Feedback#1740]
Hi, im trying to set cookie on my webview to show image to `img` tag from authenticated API. I tried to make a `fetch` call to my authentication API and successfully got this response back:

![image](https://user-images.githubusercontent.com/12814796/133083588-ddd1346c-7159-43d7-b657-827b7592f6d3.png)

The problem is the cookie seems not to be set so the image API calls are still failing:

![image](https://user-images.githubusercontent.com/12814796/133083797-95da5e31-88d4-46fc-9bf7-d8baa538f891.png)

![image](https://user-images.githubusercontent.com/12814796/133083917-50970a76-bdcd-4b23-991e-35071a7f4d9c.png)

Any help is appreciated. Thanks.

This issue is also on https://github.com/dotnet/aspnetcore/issues/27217#issuecomment-918144414

**Comment by champnic** [comment]
@realivanjx Hey Ivan - Are you able to test your scenario in Microsoft Edge browser? Does it work there? We mostly match the behavior of the browser when it comes to platform behavior.

**Comment by realivanjx** [comment]
Sorry @champnic, if im understanding you right, im using this for my blazor desktop app so i dont think it is possible to test it using ms edge browser outside of wpf's webview2 control. However it works perfectly well on the blazor wasm project using normal browsers be it chromium or firefox (i have 3 projects: shared razor library, wasm, and wpf).

**Comment by champnic** [comment]
Are you using the same WebView2 instance for both getting the cookie, and then expecting it to be set when requesting the image?

**Comment by realivanjx** [comment]
yes there is only one webview inside the entire wpf app

**Comment by champnic** [comment]
Would you mind capturing a network log? Might give you a clue, or you can send it to us to take a closer look:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1384#issuecomment-861893587

**Comment by realivanjx** [comment]
here you go [0.0.0.0.har.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7188979/0.0.0.0.har.zip)
 
btw i also noticed this:

![image](https://user-images.githubusercontent.com/12814796/133867667-bb9bc38a-994b-4569-9167-acb5ac415d17.png)

could this be the reason since my cookie is `secure`?

**Comment by ericlaw1979** [comment]
You need to update your fetch call with

                 `credentials:"include",`

(You also need to ensure that the server response with an appropriate `Access-Control-Allow-Credentials` directive. If you fail to set the `credentials` mode, the `Set-Cookie` response header from the cross-origin response is ignored.

As noted in https://fetch.spec.whatwg.org/#example-cors-with-credentials 
A request has an associated credentials mode, which is "omit", "same-origin", or "include". Unless stated otherwise, it is "same-origin". "omit" Excludes credentials from this request, and causes any credentials sent back in the response to be ignored. "same-origin" Include credentials with requests made to same-origin URLs, and **use any credentials sent back in responses from same-origin URLs**.
