### ISSUE TITLE
WebResourceRequested Fail to run in "2nd attempt"  1.0.1018-prerelease

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1766]
Using latest: SDK : 1.0.1018-prerelease
Runtime : 94.0.992.31
----------------------------------------------------------------------------
A) when setting the source property of the iframe for the first time it fires the **WebResourceRequested**  event successfully :
![image](https://user-images.githubusercontent.com/5411026/134821836-90cc133d-cc6c-46b6-a4b5-03d773e8d61a.png)

B) 2nd attempt to change the Source property of the iframe the **WebResourceRequested** fails to run.

![image](https://user-images.githubusercontent.com/5411026/134821892-c26486c0-27f9-41cf-9711-2da052488c42.png)

my **WebResourceRequested** carry the process to remove the unwanted header that causing some site to not render in the iframe :
![image](https://user-images.githubusercontent.com/5411026/134821952-f926651f-3623-4528-9c36-93b17b8df525.png)

This issue exisits since day 1. 

[AB#36479586](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36479586)

**Comment by xblack0** [comment]
> Thanks for the bug report @xblack0. How are you setting the source in the iframe? If you set it to a new value do you see the event fire?
> 
> I've opened this bug on our backlog.

iframe.src="https://www.google.com"

**Comment by yildirimcagri-msft** [comment]
Hello, it's been a while since this bug opened (sorry this one fell of our tracks), however if it is still reproing, it is likely because the old AddWebResourceRequestedFilter API did not support out of process (cross-origin) iframes. To get the WebResourceRequested events for cross-origin iframes, you should use [AddWebResourceRequestedFilter with SourceKind property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addwebresourcerequestedfilter?view=webview2-dotnet-1.0.2592.51#microsoft-web-webview2-core-corewebview2-addwebresourcerequestedfilter(system-string-microsoft-web-webview2-core-corewebview2webresourcecontext-microsoft-web-webview2-core-corewebview2webresourcerequestsourcekinds)). Hope this helps.

Closing for now, feel free to reopen if this still reproes.
