### ISSUE TITLE
Updating NewWindow Property in NewWindowRequested Event Causes Blank Page in Existing Window

### ISSUE THREAD

**Issue by dhallada** [MicrosoftEdge/WebView2Feedback#1771]
**Description**
I have a WPF app that uses webview2. When users navigate to a certain URL, there are links to pdfs that will open in a new window. The problem I am trying to address is that the new windows don't respect the sizing of the browser (a known issue #1343 ).

Based on what I am reading, I can address this by setting the NewWindow property on the CoreWebView2NewWindowRequestedEventArgs to my existing webview2's CoreWebView2, but when I do that, it:

1) Doesn't open the new window
2) Overwrites the existing window with a blank page

**Version**
**Version**: WebView2 1.0.902.49
**.NET Framework** 4.7.2
**OS** Wind10

![image](https://user-images.githubusercontent.com/83424630/134996591-caf27a94-e9b3-4288-86fe-2c2b8620ebb3.png)

**Additional context**

**Comment by dhallada** [comment]
Additional notes:

1) Even when I comment out all the above code and throw a debugger in that method to inspect the event args, it still overwrites the existing window (though all code is commented out). However, it only seems to do this when I hit the debugger and if I remove it, the window remains and the popup opens.

2) When I inspect the uri given, it is "about:blank#blocked", which is likely why the page is blank. So if I can't get the actual uri / url for this pdf, I can't open it in the new window even if I could get this to work.

**Comment by champnic** [comment]
Hey @dhallada - The issue here is that the CoreWebView2 you pass to the NewWindowRequestedEventArgs determines where the new window navigation will occur. If you give it the current CoreWebView2, then that's why it overwrites the existing content.

Instead, you should create a new WebView2 (and display it however you like - in a new Window/form, hidden, etc.) and give that in the NewWindowRequestedEventArgs. The navigation will happen in that new WebView2 and not in your current one.

Let me know if that helps or you are still running into issues.

Thanks!
