### ISSUE TITLE
--headless no longer works in scheduled task

### ISSUE THREAD

**Issue by GlennDelta** [MicrosoftEdge/WebView2Feedback#1776]
Hello,

Since some time (sorry, don't know exactly since what version exactly) the --headless parameter no longer works when launched from a windows scheduled task.

We have a powershell script in a scheduled task on a windows server which takes a screenshot of a site using msedge.exe with the parameters "--screenshot=$TempImageFolderPath\tmp.png --headless" to create a screenshot of a certain page and then mail it. 

It runs fine when we manually run the script, but when we run it as a scheduled task, the image does not get created. The msedge.exe process also never shows up in taskmgr...

We used this method for some time now and has always worked fine but since a certain update it has stopped working...

If anyone would like to share a workaround for this it would be much appreciated...

kind regards,
Glenn

**Comment by champnic** [comment]
Hey @GlennDelta - Unfortunately this seems like an issue with the Microsoft Edge browser (msedge.exe) and not WebView2. You can open feedback on the browser using the feedback tool (Shift + Alt + i). You can also see if the issue is the same in Chrome/Chromium, and open a bug on Chromium at crbug.com. Thanks!
