### ISSUE TITLE
ms-appx:/// support in WebView2 desktop packaged apps

### ISSUE THREAD

**Issue by btueffers** [MicrosoftEdge/WebView2Feedback#1827]
Related to https://github.com/MicrosoftEdge/WebView2Feedback/issues/1281#issuecomment-938308083

**Describe the solution you'd like and alternatives you've considered**

When creating a packaged WebView2 desktop app I would like to have ms-appx:///  support for setting the Source property.

As an alternative users can currently use full paths. However, things like images in packaged apps typically use ms-appx.

**Comment by champnic** [comment]
Hey @btueffers - If you have control of your html/js you can do this today by setting up a domain to file location mapping:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.992.28
and set if to your app's folder.

Let me know if that works for you. If not I can add this scenario to our backlog. Thanks!

**Comment by LouisLavallee** [comment]
@victorhuangwq  Is this completed? which version do i need for ms-appx to function?

**Comment by victorhuangwq** [comment]
@LouisLavallee referring to #1281 

> We don't currently have support for ms-appx:///. Instead, you can use SetVirtualHostNameToFolderMapping to map a host name to the same location as where ms-appx points to, or anywhere else that's convenient for you:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.992.28#Microsoft_Web_WebView2_Core_CoreWebView2_SetVirtualHostNameToFolderMapping_System_String_System_String_Microsoft_Web_WebView2_Core_CoreWebView2HostResourceAccessKind_ 

I closed this feature request because there has not been any activity in 2 years
