### ISSUE TITLE
CoreWebView2.CookieManager.DeleteAllCookies bug

### ISSUE THREAD

**Issue by gudieaofei** [MicrosoftEdge/WebView2Feedback#1923]
1.init webView1 control

```cs
var webView1 = new WebView2
{
    CreationProperties = new CoreWebView2CreationProperties
    {
        UserDataFolder = $"storage/profile1"
    }
};
await webView1.EnsureCoreWebView2Async();
```

2.init webView2 control,and use the environment of webView1,but different user data folder
```cs
var webView2 = new WebView2
{
    CreationProperties = new CoreWebView2CreationProperties
    {
        UserDataFolder = $"storage/profile2"
    }
};
await webView2.EnsureCoreWebView2Async(webView1.CoreWebView2.Environment);	
```

3.then call this code:webView2.CoreWebView2.CookieManager.DeleteAllCookies(),the webview1 cookies will also be deleted.

**Version**
SDK: 1.0.865-prerelease
Runtime: 92.0.902.62
Framework: donet core 3.1
OS: Win10

**Comment by champnic** [comment]
Hey @gudieaofei - the Environment object includes the user data folder, so by initializing the second WV2 with the Environment from the first WV2, they are actually using the same user data folder, which is why you are seeing the cookies deleted for both WV2. You'll need to create a separate environment object for the second WV2 with the user data folder set, or call EnsureCoreWebView2Async without any parameters to have it use the CreationProperties. Thanks!
