### ISSUE TITLE
Navigation To Google Through Webview2 Returning Too_Many_Redirects

### ISSUE THREAD

**Issue by TF523** [MicrosoftEdge/WebView2Feedback#2020]
@champnic 

**Description**
Attempting to navigate to https://www.google.com via webview2 control creates the following error. Clearing all cached data and cookie does not fix the problem.

![image](https://user-images.githubusercontent.com/5530663/146090064-c7cb3157-2f5e-4376-adb8-407a1c7901ba.png)

**Version**
SDK: 1.0.1054.31
Runtime:  Dev 98.0.11
Framework: WinForms
OS: Win10

**Repro Steps**
Try to navigate to google.

**Screenshots**
See above
**Additional context**

**Comment by TF523** [comment]
@champnic 

Have no other problems with navigating to any other sites...

yahoo
linkedin
bing
facebook

all work fine.

After rolling back to previous versions of your control 1.0.955 the problem still persists.  However, we did not have this problem in august when we were running this version. So I am not sure where the nav issue is coming from???

**Comment by TF523** [comment]
@champnic

Ok after changing the user agent it starting working??? I have no idea why a user agent change will fix the problem...

**Comment by jasonstephen15** [comment]
Thanks for the question @TF523, I tried to repro in the WinForms WebView2 Sample app, and wasn't able too. What had your user agent been set to before? Was it not the default setting?

Btw it could be related to this: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1647, but you aren't trying to do anything login/google auth stuff, so definitely an odd bug. Let me know if you are still having trouble, and we can get a deeper trace or something to see where the issue is.

**Comment by champnic** [comment]
@jasonstephen15 @TF523 This is the same issue as #1988, so we'll use that one to track. It is weird that even if you set the user agent to the same value it causes this behavior on google sites.

**Comment by nirbil** [comment]
This problem happens when you start with a clean environment and try to navigate to youtube or google.
I noticed however that sometimes after a few navigations it can get resolved, and once it's resolved it doesn't happen again until you restart with a clean environment. So probably cookies related?
