### ISSUE TITLE
What is the 'EBWebView' folder created for?

### ISSUE THREAD

**Issue by tatsuya-midorikawa** [MicrosoftEdge/WebView2Feedback#2023]
Hi, experts!

Why is the 'EBWebView' folder created and what is its purpose?
Also, what does the 'EB' stand for?

Thanks.

**Comment by jasonstephen15** [comment]
Good question @tatsuya-midorikawa. I actually don't know for certain, but my guess would be EB stands for 'Edge Browser WebView' and looks like it contains folders for browser features like SmartScreen, Widevine, etc. I do see it as a subfolder of the debug directory, so perhaps it's for crash dumps with Browser Features within WebView2.

I can have someone else on my team confirm after the holidays, but thought I'd give you my thoughts now :)

**Comment by kurash** [comment]
I'm not one of the WebView2 developers, but maybe this info will help.  The EBWebView folder contains the browser state for an instance of WebView2.  It contains cookies, local storage, history, and all the other local data that a browser needs to store in order to support modern web pages.

The location of the folder is set for a given instance of WebView by passing a path to CreateCoreWebView2EnvironmentWithOptions (for C++ apps at least).  If you do not specify a path, the folder is created in the current working directory.  Note that if the cwd is read only for the user, you're likely to see an exception thrown.

**Comment by jasonstephen15** [comment]
Thanks @kurash! Got confirmation from the dev team, that EBWebView (EB = Embedded Browser) folder is just the user data folder's default location. You can read more about it here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder.

Closing this thread for now, since we have confirmation, but feel free to add any other questions about it here.

**Comment by tatsuya-midorikawa** [comment]
Thank you all for your help.

Regards,
midoliy
