### ISSUE TITLE
WebView2 renders incorrectly with HighDpiMode = DpiUnawareGdiScaled

### ISSUE THREAD

**Issue by RalphLAtGitHub** [MicrosoftEdge/WebView2Feedback#2059]
**Description**
MDI child control designed for 96 dpi that contains a WebView2 control is not rendered correctly on a screen with a dpi value greater than 96.

**Version**
SDK: .NET 6.0.101 + WebView2 1.0.1054.31
Runtime: Edge 96.0.1054.62 
Framework: WinForms
OS: Win10 Pro 21H2 Build 19044.1415

**Repro Steps**
Create a WinForms app with a MDI parent and a child. Add WebView2 to the child. Set HighDpiMode to DpiUnawareGdiScaled as application default.

**Screenshots**

Actual behaviour:
![DEMO_1](https://user-images.githubusercontent.com/34791469/148265857-4d9e1a6d-2e32-439f-bad1-bd661567a47e.jpg)

Expected behaviour:
![DEMO_2](https://user-images.githubusercontent.com/34791469/148265872-dabb8cb7-86a4-4e7b-b6be-5988d4e43c05.jpg)

**Comment by champnic** [comment]
Hey @RalphLAtGitHub - thanks for the bug report! This looks to be the same issue as #1700. Per documentation, it looks like `DpiUnawareGdiScaled` only does scaling for GDI content, which is why you aren't seeing the WebView2 get scaled in the high DPI scenarios.
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.highdpimode?view=windowsdesktop-6.0#fields
