### ISSUE TITLE
Multiple instances of Edgeview 2 crash Photoshop

### ISSUE THREAD

**Issue by HenkPeels64** [MicrosoftEdge/WebView2Feedback#2092]
I can find multiple instances of people reporting crashes with Photoshop related to multiple Webview2 processes appearing under the Phiotoshop 2022 process. I will assume you are aware of the issue. Are you?

I cannot find any hint of a resolution  though. My wife is a professional photographer and we recently upgraded to a fairly capable laptop, yet she experiences frequent crashes with Photoshop, even when only working on 2 or 3 photo's. Before Webview2 and with much less capable hardware this never happened.
The frequency of crashes has become unbareable and unworkable, hence my wife has become unbareable :-) /

Can you offer a resolution or workaround?

[system overview and processes.pdf](https://github.com/MicrosoftEdge/WebView2Feedback/files/7911595/system.overview.and.processes.pdf)

**Comment by jarno9981** [comment]
@HenkPeels64  do you got a windows 11 or 10 because i had a issues with something different to but champnic told that was a small taskmanager issue

**Comment by HenkPeels64** [comment]
Windows 10. 

What was the small issue?

**Comment by jarno9981** [comment]
@HenkPeels64 the process name and icon changed and after a wille the separate webview2 goes to the background not on the app the same a you thats shows in photoshop webview2 for me it goes the a background process

**Comment by champnic** [comment]
Hey @HenkPeels64 - It looks like Photoshop is using a WebView2 control, which is why the processes are appearing as children of the Photoshop process. How do you know that the crashes are related to WebView2?

Unfortunately there isn't really much we can do with this information on the WebView2 side. You should try reaching out to Photoshop to get help with this issue. Thanks!
