### ISSUE TITLE
Windows 10 Performance Issues 

### ISSUE THREAD

**Issue by okina** [MicrosoftEdge/WebView2Feedback#2096]
**Description**

First of all apologies for the severe lack of technical detail that follows.  I do not directly use Webview2 runtime.

As of yesterday my Win10 Del XPS laptop started experiencing severe slowness to the point where scrolling became fragmented and laggy.  Task manager/resource monitor did not indicate anything out of the ordinary.

I began to stop lots of different services at startup to figure out what was going on, and it was only when I came across this Reddit sub that I came to suspect the newly installed Webview2 Runtime: 

https://www.reddit.com/r/MicrosoftEdge/comments/m9x0xj/microsoft_edge_webview2_runtime_is_a_huge_problem/

Anyway, sure enough I uninstall Webview2 and the issues resolve immediately.

My main browser is Google Chrome. I wasn't using Edge at all.  I'm assuming this was installed through Windows Update and will probably creep back in.  I don't have the version that was installed as it's now gone, but on chance it reinstalls I will provide it.

Again, apologies for lack of useful information, but I echo the sentiment of the Reddit threads that something is seriously wrong.

**Version**
OS: Win10

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Hey @okina - Thanks for the bug, and sorry to hear you are running into that. As a control, WebView2 can be used by apps to build their UI and do other tasks, so by uninstalling WebView2 you may be breaking or changing the behavior of some apps. Many apps will attempt to reinstall WebView2 if they detect that it's missing, so that would be why it gets reinstalled if it shows up again. I wouldn't expect WebView2 to cause performance issues unless there was memory or CPU pressure on the machine.

If you do see this issue again, please let us know and we can try and gather some diagnostic data. You can also check in Task Manager to see which apps are using WebView2, for example:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/45700886/151456861-d2169290-58e6-4c52-b8c7-b7ae81c7c77a.png">

Thanks!

(I'm going to close this issue because it's not actionable at this time, but please reach out if you see this again)
