### ISSUE TITLE
Questions about the relationship between Edge, WebView2 SDK and WebView2 Runtime

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftEdge/WebView2Feedback#2100]
Transferring @dhammondhelient 's issue originally posted here: https://github.com/MicrosoftDocs/edge-developer/issues/1688

> Hello! I am trying to understand relationship between Microsoft Edge, Microsoft Edge WebView2 Runtime, and WebView2 SDK. I know that there are independent release notes for Microsoft Edge and WebView2 SDK, but I can't seem to find where WebView2 Runtime's own release notes are. Like for example, where would I go to find the release notes for Microsoft Edge WebView2 Runtime 97.0.1072.69 (the latest release)? Are they included under Edge's or SDK's notes? Also is WebView2 SDK a required component to download for Runtime, or is it an optional add-on?

**Comment by champnic** [comment]
Hey @dhammondhelient -

**WebView2 Runtime release notes**
The runtime will have some notes listed under the SDK release notes, that will normally be denoted as a runtime fix. Otherwise, the runtime mostly shares its code with the browser, so you can see the Microsoft Edge browser release notes:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

**WebView2 SDK**
The SDK is required to use WebView2, but not required in order to download the runtime. The SDK includes binaries that allow the host app to find and launch the WebView2 runtime that will navigate and render web pages. The runtime can be downloaded separately by users or the app:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Hope this helps! Let me know if you have further questions. Thanks!
