### ISSUE TITLE
How to modify the language of WebView?

### ISSUE THREAD

**Issue by xiao-cao-x** [MicrosoftEdge/WebView2Feedback#2119]
` webView.Language = "zh-CN";` invalid

**Comment by champnic** [comment]
hey @xiao-cao-x - Is this in WinUI 3? In .NET you can specify the language property of the CoreWebView2EnvironmentOptions. In WinUI 3 there is no way to create a custom environment though. You can ask about this issue here for more information:
https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=

Thanks!
