### ISSUE TITLE
Add API to open/close the find dialog programmatically

### ISSUE THREAD

**Issue by Kay-Burchardt** [MicrosoftEdge/WebView2Feedback#2316]
Currently the find dialog can only be opened by pressing CTRL+F when the WebView2 is focused. It can only be closed by hitting ESC or clicking the X icon of the dialog. There should be an API to open/close the find dialog. This would allow to open/close the find dialog with custom accelerators in the embedding application.

Furthermore, keyboard input in the find dialog currently doesn't trigger the AcceleratorKeyPressed event. This should also be fixed to improve the interoperability with the embedding application.

**Comment by champnic** [comment]
Hey @Kay-Burchardt - We are tracking this feature request in #1737. If there's anything related in that ask that you see is missing please add it to that thread. Thanks!

**Comment by nishitha-burman** [comment]
Hi @Kay-Burchardt, 

I am looking into this feature and have a couple of questions to better understand the requirements:
1. Can you please describe the scenarios where find needs to be invoked programmatically vs. triggered by end users?
2. How do you envision the UI/UX when find is triggered? Do you want the find dialog to appear, be able to build a custom dialog with the matching words, see all matching words to be highlighted, etc.?

Thanks!

**Comment by Kay-Burchardt** [comment]
Hi @nishitha-burman ,

we do not want a custom UI. The standard UI is just fine. We simply want a way to programmatically toggle and check visibility of the find dialog which is currently opened by CTRL+F. We have three different cases where this would help us:

1. Implement a "Find" item in the window menu of our embedding application.
2. Implement a "Find" item in a custom Webview2 context menu.
3. Implement a (custom) accelerator in our embedding application.
4. Our embedding application has tabbed browsing. The Webview2 instances are stacked, and the webview2 of the currently selected tab is brought on top (z-order). Unfortunately the find dialog for Webview2s which are pushed in the background are still floating on top. Currently we need to make them additionally hidden to prevent this. This saves some resources, but also slows down tab change and introduces some flickering in the process. If we could determine and control visibility of the find dialog for each Webview2, we could implement a nicer solution.

I suggest to simply implement a property "IsFindDialogVisible". To getter would allow us to check visibility of the standard find dialog, while the setter would allow us to toggle it reliably.

Best regards,
Kay

**Comment by fotodmitriru** [comment]
Hello! Tell me at what stage of the API implementation for Find dialog? Or possible open Find dialog programmatically? Variant SendKeys doesn't suit me, because my App accepts keystrokes - it turns out to be an eternal cycle. I need a beautiful solution via API or programmatically open Find dialog. Also my application has Javascript disabled, - this is a necessity.

**Comment by fotodmitriru** [comment]
Hello! Tell me at what stage of the API implementation for Find dialog? Or possible open Find dialog programmatically? Variant SendKeys doesn't suit me, because my App accepts keystrokes - it turns out to be an eternal cycle. I need a beautiful solution via API or programmatically open Find dialog. Also my application has Javascript disabled, - this is a necessity.
