### ISSUE TITLE
License for embedding DLL?

### ISSUE THREAD

**Issue by hectorcastro-teamviewer** [MicrosoftEdge/WebView2Feedback#240]
Dear WebView team.
One of our developers is using the WebView2 SDK. As there´s a DLL to be embed in our application we need to know if there´s any licensing or security consideratons when shipping it along with our software. Also it would be interesting to know if there´s any way to bypass embedding that DLL.
Thank a lot and best regards,

Hector Castro

**Comment by liminzhu** [comment]
For the DLL, we have a very liberal BSD-style license included in the SDK that should give you distribution rights. 

> Also it would be interesting to know if there´s any way to bypass embedding that DLL.

Not yet, but we're considering making this DLL a static lib (cross-post https://github.com/MicrosoftEdge/WebViewFeedback/issues/110). Can you tell me a bit more about the motivation behind trying to bypass embedding a DLL? Is it that you can ship a single executable for the app, or because of license or security or something else?
