### ISSUE TITLE
[Announcement] WinRT JavaScript Object Projection now supported

### ISSUE THREAD

**Issue by jasonstephen15** [MicrosoftEdge/WebView2Feedback#2448]
The latest webview2 prerelease nuget package ([1.0.1248-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1248-prerelease)) includes a tool that will now enable projecting WinRT Objects into Javascript, which is a widely requested feature from many developers!

Please read our [full doc](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=csharp) for more details on the tool and scenario! We are looking for any feedback, so please drop any questions or issues below!

**Comment by Jaifroid** [comment]
Thank you very much for this. I'm just exploring options, but this looks very exciting. I have a PWA that uses native JS APIs, but that can be enhanced with WinRT APIs if packaged as a UWP app. For the latter, I'm currently stuck using the old Edge Legacy framework for HTML/JS UWP apps that can only be built in Visual Studio 2017. I've been looking for a way forward within the UWP framework for a long time.

My particular requirement is as follows: while my PWA can use native JS APIs such as the File System Access API (which is great), these APIs are not yet at the stage where they give a full native-app-like experience. The File System Access API, for example, still prompts the user for permission for read access to a previously picked file or directory _on every app launch_. Currently in my UWP version, I test for the WinRT Storage APIs and use those in preference, and this gives the app a much more native feel for end users.

Would you say this project is suitable for my use case?

For now, I've followed the guide and have the webview up and running, and have verified that my PWA can be accessed from it, which is all very encouraging. Next step is to experiment with adding the Windows.Storage WinRT APIs, which are the ones I'm most interested in.

I did notice that WebView2 doesn't seem to support the standard JS drag-and-drop API yet, which is quite a basic and universal JS API. That is a little worrying. Additionally, the WebView does not show a file or directory picker with the File System Access API, and it reports that the user denied permission to access a file (but there is no permissions prompt). Hopefully these are just wrinkles (unrelated to this issue, I know).

**Comment by lukeblevins** [comment]
Greetings.

Does the new wv2winrt tool support having a C# WinRTAdapter project that also happens to reference the WinAppSDK? This would simplify the project structure of my app if the existing WinUI C#/WinRT component can project some of its types to be used in the same project?

My solution:
- A C#/WinRT Component which references WinUI using WebView2 (also contains a folder of source files that need to be accessible as host objects within the WebView2)

- Sample app to demo a control contained inside the WinRT component, powered by WebView2

I'm finding there are the following issues when building my WinRT component (also the WinRT adapter):

```
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2303,5): warning MSB3243: No way to resolve conflict between "Microsoft.Web.WebView2.Core, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime" and "Microsoft.Web.WebView2.Core, Version=1.0.1305.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e". Choosing "Microsoft.Web.WebView2.Core, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime" arbitrarily.
1>CSC : warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'Win32Exception' with message 'Incorrect function'
```

It also appears that the generated winmd is being placed in the wrong Generated Files directory (one level up from where it's supposed to be)

I would be thrilled to hear your advice on how to fix this, if possible.

**Comment by david-risney** [comment]
I'm not sure I quite understand your setup but I can describe how wv2winrt could work with C# projects and some restrictions.

wv2winrt generates c++/winrt code. In a project where the calling code is c++ you might be able to build the wv2winrt generated code in your c++ project and not need more than one project. For C#, the calling C# code would need to be in a project that depends on a different c++/winrt project that builds the wv2winrt generated code.

Additionally, in the case of third party winrt the wv2winrt generated code would have a dependency on the third party winrt code. If this code is C++ again the third party winrt code could live in the same project as the wv2winrt generated code. For C#, you would need a different project that the wv2winrt generated code's project would depend on. The C# project would need to build first to generate the winmd file that the wv2winrt tool can parse to generate its generated code.

Combining the calling code and third party winrt parts together for C#, you'd need 3 projects. The calling C# code in one project that depends on the wv2winrt generated c++/winrt code in a second project that depends on your third party winrt C# code in a third project. The first and third projects have to be different because the calling code depends on code generated in project two which depends on winmd generated by project three. 

Putting projects one and three into the same C# project would create a cyclic dependency. You might be able to hack it together manually editing msbuild files or something but I'm not sure what that would look like offhand and would likely have bad build properties (like having to build twice whenever you change the third party winrt API).

To share code between projects one and three you might move common code to project three and have project one depend on it as well:

```mermaid
flowchart TD
 A[Project 1\nC#, App Code] --> B[Project 2\nC++/winrt, wv2winrt generated code]
 A --> C[Project 3\nC#, Third Party WinRT & shared app code]
 B --> C
```
