### ISSUE TITLE
Error - Source Property cannot be set to null.

### ISSUE THREAD

**Issue by jeremygrmn** [MicrosoftEdge/WebView2Feedback#2518]
Hello. Please see the following [original issue](https://stackoverflow.com/questions/72590297/wpf-webview2-error-source-property-cannot-be-set-to-null).

I have a view model for the view with the WebView2. Navigation in the app perspective (not WebView) is done by changing data contexts in a parent viewmodel. The issue I am running into is that when I navigate away from the view with the WebView, I am given the error " The source property cannot be null". I find this to be erroneous however, as the source property is never infact set to null - the view model for the WebView2 is no longer in use.

What are some options on solving this? On navigation, should I also be creating an event to dispose of the WebView?

**Comment by yildirimcagri** [comment]
Hi, could you provide us with a dump of the exception? My speculation is that this could be a [re-entrancy issue](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model) since you are destroying the WebView2 in the event handler, but a dump would help figure out the actual issue. You could also try to see if scheduling a task to destroy the WebView2 as described in the article instead of directly running in the event handler fixes the issue for you.  Hope this helps!

**Comment by yildirimcagri** [comment]
Hi, I will close this issue for now as we haven't heard back from you in a while. Let us know if you still run into this and feel free to reopen if so. Thanks!

**Comment by darbid** [comment]
Please note that you are getting an error because that is the way it is currently coded. I argue this needs to be fixed and you can track this on #1136. @yildirimcagri please note open issues.

**Comment by jpgarza93** [comment]
I am having the same issue. Changing the DataContext of the view due to MVVM navigation causes this.
