### ISSUE TITLE
Allow Multi-Platform Bundling

### ISSUE THREAD

**Issue by TonyValenti** [MicrosoftEdge/WebView2Feedback#252]
Current I use CEFSharp but want to migrate to WebView2 once it supports distributing all the chromium DLLs with the app.  CEFSharp supports this workflow and I want to make sure that WebView2 will as well:

Please store the platform specific binaries in a /x86 /x64 or /arm64 subfolder and load the correct one based off of the bitness of the app - this way two EXEs with differing bitness can coexist in the same folder.

**Comment by pagoe-msft** [comment]
@TonyValenti,

Yes, out plan is to enable this workflow - for WebView2 to allow you to distribute chromium DLLs with the app. We call this the "Fixed" model. 

Could you provide us with some more clarity on your scenario and why you prefer shipping chromium DLLs instead of relying on the "Evergreen" model?

**Comment by TonyValenti** [comment]
@pagoe-msft This is great!  With the fixed model, please make sure that multiple platforms can co-exist in the same folder.

I definitely prefer fixed over evergreen because it allows me to be in control of my update cycle and have confidence that everything works well and tests well together.  The last thing that I want is to start getting support phone calls because my app stopped working because an IT admin did or did not install a specific OS patch.

We want our apps to be self-contained as much as possible.  We already have our own update procedures in place and feel much better being able to build, test, and release at our own cadence without any surprises.  With CEFSharp, it is nice because we just have to update nuget packages and our next build will have the updates.

**Comment by liminzhu** [comment]
Yeah we will provide separate binaries for x64/x86/ARM64, and you can decide where to put/how to load them.

**Comment by LeoDavidson** [comment]
Just to add a slightly different use-case (but similar underlying issue): We want to use the "evergreen" WebView, but we have the problem that our exes (say Blah32.exe and Blah64.exe) are both in the same folder, and ideally need to stay there (else we have to make a lot of changes).

Since both the 32-bit and 64-bit versions of WebView2Loader.dll have the same filename, and are loaded by your .lib file on process start before any of our own code has run, it's currently (or at least, last time I looked at this) impossible to keep the two exes in the same folder.

A way to specify where to load the DLL from, and be able to load the DLL after process launch, would fix this, and allow us to move it (but not our main EXEs) into a sub-folder, or to rename the DLLs to include bitness (assuming that renaming them won't break something else).

Alternatively, if the standard names for the DLLs were not the same for both bitnesses, that would also solve the problem for us, but I can understand that that might cause problems on your side or for other use-cases.

**Comment by liminzhu** [comment]
@LeoDavidson this is really interesting and I think we will want to look at your scenario separately from this current issue. May I ask you to open a new issue? It's easier for us to track that way :).

**Comment by LeoDavidson** [comment]
> May I ask you to open a new issue? It's easier for us to track that way :).

Sure thing! Done, and you should see the link just above.

Thanks for your time.
