### ISSUE TITLE
WebView2 CodeIntegrity Error with SEP version 14.2.1031.0100 on Windows Server 2016

### ISSUE THREAD

**Issue by kyawhpa** [MicrosoftEdge/WebView2Feedback#2540]
WebView2 Runtime Version: **102.0.1245.44**
Symantec Endpoint Protection Version: **14.2.1031.0100**
OS Info: Windows Server 2016: **14393.4946**

Error message in event logs: **Code Integrity determined that a process (\Device\HarddiskVolume2\Program Files (x86)\Microsoft\EdgeWebView\Application\102.0.1245.44\msedgewebview2.exe) attempted to load \Device\HarddiskVolume2\Windows\System32\sysfer.dll that did not meet the Microsoft signing level requirements.**

**With the previous version of WebView2 Runtime, this error did not happen.**
Please help.

**Comment by LiangTheDev** [comment]
This issue is caused by Symantec Endpoint Protection injecting sysfer.dll into msedgewebview2.exe renderer process.
Have you tried to update SEP to latest version?
I am not familiar with how SEP works, if there is a way to config exclusion list for injecting dlls into processes, you could also try that.
As a last resort, you can set environment variable WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS with value --disable-features=RendererCodeIntegrity.
