### ISSUE TITLE
exe has exited with code 2147483651 (0x80000003)

### ISSUE THREAD

**Issue by jsclough** [MicrosoftEdge/WebView2Feedback#2542]
Regularly getting ". . .exe has exited with code 2147483651 (0x80000003)"

Have reproduced this crash on WebView2 stable release 1.0.1245.22 and also on prerelease 1.0.1248.

As was the case in issue [2132](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2132), this crash is not captured by the WebView_ProcessFailed event.

Attached is one of the mini dumps.

This is a leaflet app running on WebView2.  The problem was occurring intermittently, but now seems to occur regularly when a modal output window in C# is spawned over the WebView2 form.

I tested calling the modal output window prior to showing the WebView2 component and the crash does not exist.  If the modal window is produced after the WebView2 component is activated the crash occurs randomly after a minute or two of using the modal window .

This is a Windows forms Application with .NET 6.0 developed on Visual Studio 2022 on Win10 Pro.

Please let me know if you need more info and thanks for any insight you may be able to provide!

**Additional context**
Mini-Dump Removed.

**Comment by LiangTheDev** [comment]
This is due to running a message loop (modal dialog) from WebView2 event handler, which is not recommended, as no further webview events will be process before the dialog is dismissed and returned from the event handler. If you show the dialog asynchronous outside of WebView2 event handler, then it will be fine.
This is actually not a real crash. If you run the app without a debugger attached, it will not crash. If you run the app under a debugger, we will display a message in debugger with link to https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#re-entrancy, and break into debugger. That page has information on how to refactor the code to avoid this.

**Comment by jsclough** [comment]
Thank you so much for your quick response!  I will work on the threading of my application and get back to you if I continue to have a similar problem.  (I was also seeing this error intermittently prior to opening a modal window, but that could have somehow been related to the threading.)

**Comment by jsclough** [comment]
As expected, this problem is solved by scheduling the modal window to open after completion of the event handler from the link provided above (code below).  Thanks again for the quick help.

private void CoreWebView2_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
{
   string msg = e.TryGetWebMessageAsString();
   if (msg == "Open Dialog")
   {
      // Show a modal dialog after the current event handler is completed, to avoid potential reentrancy caused by running a nested message loop in the WebView2 event handler.
      System.Threading.SynchronizationContext.Current.Post((_) => {
         Form1 form = new Form1();
         form.ShowDialog();
         form.Closed();
      }, null);
   }
}
