### ISSUE TITLE
How to get WebView2 to open links in the default browser?

### ISSUE THREAD

**Issue by hakzhyena** [MicrosoftEdge/WebView2Feedback#2587]
So far what I have done is registering to '[CoreWebView2.NewWindowRequested Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.newwindowrequested?view=webview2-dotnet-1.0.1264.42)' and when a link from WebView2 control is clicked I am able to capture the event.

In the handler I am just doing the following:

`args->putNewWindow(sender);`
`args->put_Handled(TRUE);`

This is just redirecting to the link in the same page instead of opening a new window. But I want to be able to open a new (default) browser when the link is clicked.

Please let me know how it can be achieved.

**Comment by yildirimcagri** [comment]
If you pass the source WebView2 as the NewWindow, the URL will open in the existing WebView2, which is the expected behavior. To open the URL in the default browser, in the NewWindowRequested event handler, you can use the [Process.Start API](https://stackoverflow.com/questions/21835891/process-starturl-fails) and pass the URL that's requested from NewWindowRequested event and mark the event as handled. Hope this helps!
