### ISSUE TITLE
window.print() not work when print html file which contains embed/object tag

### ISSUE THREAD

**Issue by fangjialivico** [MicrosoftEdge/WebView2Feedback#2601]
**Description**
In our project, we use WebView2 to open HTML file, and use ExecuteScript(_T("window.print();"), nullptr) to show print dialog.

when open normal HTML file,  
    after calling ExecuteScript(_T("window.print();"), nullptr), the print dialog is shown, it is OK.

when open HTML file which contains embed/object tag(Embedded PDF files)
    after calling ExecuteScript(_T("window.print();"), nullptr), it don't work and the print dialog is NOT shown.
    but if we click the "print" item in right menu, the print dialog is shown.

So, why "window.print()" not work when print html file which contains embed/object tag?

**Comment by vbryh-msft** [comment]
Does it work when you run `window.print()`; from DevTools console?

**Comment by fangjialivico** [comment]
> Does it work when you run `window.print()`; from DevTools console?

It also not work when I run window.print(); from DevTools console

**Comment by fangjialivico** [comment]
In the HTML file, we use embed/object tag to embed the PDF file

when run window.print(); from DevTools console, it doesn't work.
when click print item in right menu, the print dialiog is shown, but the embedded PDF area is show blank

**Comment by monica-ch** [comment]
@fangjialivico

Opening print dialog using window.print() - This looks to be in line with browser behavior. However, we are currently working on a Print API that lets you open a browser print dialog programmatically. You can use that API to open a print dialog programmatically instead of relying on window.print() and ExecuteScript.

Embedded PDF area is shown blank when click on print in right menu - This is by browser design. You might be able to use an iframe or window.open instead, and then call the new frame/window's .print() method  to print content.

What is your goal here? Are you trying to print whole html page or PDF file?

**Comment by fangjialivico** [comment]
> Opening print dialog using window.print() - This looks to be in line with browser behavior. However, we are currently working on a Print API that lets you open a browser print dialog programmatically. You can use that API to open a print dialog programmatically instead of relying on window.print() and ExecuteScript.

OK.
Could you share us the schedule? When can we use this print API?

> Embedded PDF area is shown blank when click on print in right menu - This is by browser design. You might be able to use an iframe or window.open instead, and then call the new frame/window's .print() method to print content.
> 
> What is your goal here? Are you trying to print whole html page or PDF file?

Yes,
in our project, we need to print whole html page, and the embedded PDF file in html page also need to be print.

**Comment by monica-ch** [comment]
The experimental API to show print dialog will be available in couple of months.

There isn't a way of printing whole html page with PDF content according to my research. You would have to convert PDF to an image.
