### ISSUE TITLE
How to disable print, save and download options in the Webview2 browser for certain pages

### ISSUE THREAD

**Issue by haQathon20** [MicrosoftEdge/WebView2Feedback#2638]
How to disable print, save and download options in the Webview2 browser for certain pages.
For example, the Print option as shown in the picture below.

![image](https://user-images.githubusercontent.com/74808806/182309893-1f2ed249-501d-4b59-912b-aebc429211c3.png)

**Comment by monica-ch** [comment]
@haQathon20 There isn't a way to restrict printing in webview2. We can investigate and provide an API to disable printing. Please open a feature request from [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/new/choose).

**Comment by vbryh-msft** [comment]
@monica-ch is the right answer. Somehow hacky workaround could be to override `window.print` method using [AddScriptToExecuteOnDocumentCreated](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1264.42#addscripttoexecuteondocumentcreated) with the stub:
```
window.print = function () {
    console.log('Skip printing');
};
```

It worked for the mentioned Service Agreement page for me, but I'm not sure if there could be any issues with this solution on other pages.

**Comment by monica-ch** [comment]
Thanks for the workaround. This restricts opening the print dialog using JavaScript but might also have to restrict end user from opening print dialog using ctrl+p and print from context menu. 

They might also have to disable accelerator keys using [CoreWebView2Settings.AreBrowserAcceleratorKeysEnabled](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.arebrowseracceleratorkeysenabled?view=webview2-dotnet-1.0.1245.22)

and also remove print context menu using [Contextmenurequested](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.contextmenurequested?view=webview2-dotnet-1.0.1264.42) , https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/context-menus

**Comment by vickiez** [comment]
As for downloads, you can disable them by handling the [DownloadStarting](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_4?view=webview2-1.0.1293.44#add_downloadstarting) event and setting the Cancel property on the event args. The event args also provide a [DownloadOperation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadoperation?view=webview2-1.0.1293.44) object so that you can cancel based on properties like URI and mime type.

**Comment by monica-ch** [comment]
Closing this for now, feel free to reopen if you have more questions about this.

**Comment by vickiez** [comment]
@JJ-connect you are right that this is not currently supported by our download API, but we are working on a SaveAs API in #1090 that may be helpful. What is the scenario you are trying to accomplish?

**Comment by JJ-connect** [comment]
@vickiez thanks for the speedy reply

The SaveAs API does sound good.

The application I have been working on is hosted as a remote app. It has a WebView2 control in a WPF app that allows some limited browser of allowed pages.

I was attempting to prevent users from saving to (or accessing) the host computer without having to disable/edit the context menu.
Even with DownloadStarting, they can still save pages.
Also when clicking `Save as...`, the location selection dialog pop up still appears before the `DownloadStarting` event fires.
This allows users to look around the file system of the host computer.

I have looked at #419, #1479 ([this workaround](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1479#issuecomment-1365894371) did not work for me), #3103 but couldn't catch the popup event anywhere.


I found [this page](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.isdefaultdownloaddialogopenchanged?view=webview2-dotnet-1.0.1722.45) and [this page](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.downloadstarting?view=webview2-dotnet-1.0.1722.45) slightly confusing as I thought they implied all download dialogs/popups would be blocked (doesn't apply to `Save as...` on page, doesn't apply to 'Save as' location selection?)

**Comment by vickiez** [comment]
The download dialog refers specifically to this download UI, not the Save dialog:

![image](https://user-images.githubusercontent.com/8353720/235548436-14dee2ec-909a-4f42-a6f1-8a7691795d31.png)

Because files saved through the Save As dialog do appear in the download dialog later, I think it would make sense to capture them with the DownloadStarting event. Feel free to open a separate issue for that.

It sounds like that would not be sufficient for your scenario, though, because you would also like to block the Save dialog. I'm not aware of other workarounds besides the one you shared - editing the context menu or using CDP. + @Master-Ukulele who can comment on the new Save As API
