### ISSUE TITLE
WPF Popup/Window with Trasparent Background Color and WebView2 content transparent

### ISSUE THREAD

**Issue by RobertGlobant20** [MicrosoftEdge/WebView2Feedback#2648]
Currently in a WPF .NET 4.8 Desktop app I'm displaying a WebView2 component (using a local html as embedded resource) inside a WPF Popup, then in the Popup constructor I'm setting the next properties:

Popup.AllowTransparency = true
WebView2.DefaultBackgroundColor = "Transparent"

After doing that the WebView2 content is blocked (not allowing the user to click, select text or do anything - see second image below) but if I set the Popup.AllowTransparency = false works as expected (javacript and css code works) but showing a black background (as shown in the first image below). By reading the Microsoft documentation seems something related to security but not sure about it.
https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.popup.allowstransparency?view=windowsdesktop-6.0

do I missing something? 
or this feature of transparency with user interaction is not supported yet?

![image](https://user-images.githubusercontent.com/61755417/182461872-c3909ba0-6cdb-48eb-bfeb-e4ad522ae37c.png)
![image](https://user-images.githubusercontent.com/61755417/182462608-c56e2868-d43a-4780-a3e6-23c794958b85.png)

**Comment by yizhao5** [comment]
@RobertGlobant20. Hello. My WebView2 content is not blocked and can also be clicked. For example, when I click Login, there will be a response. Since there is no sample code, I cannot reproduce your scenario.
![image](https://user-images.githubusercontent.com/109595412/196395314-863037c8-4ac0-4581-a80c-746a2465f305.png)

`MainWindow.xaml`
```xaml
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">

    <DockPanel>
        <wv2:WebView2 Name = "webView"
                  Source = "https://www.microsoft.com" Height="290" Width="400"/>
        <DockPanel  Width="810" Background="Aqua" Height="510">
            <Popup Placement="Center" PlacementRectangle="0,0,30,50"  
                IsOpen ="True" AllowsTransparency="True"
                PopupAnimation="Fade">
                <TextBlock Background="Purple">Popup Text</TextBlock>
            </Popup>
        </DockPanel>
    </DockPanel>

</Window>

```

**Comment by darbid** [comment]
@RobertGlobant20 reading you question it is sounds like your Webview2 is IN THE POPUP, right? If that is the case then you will never ever be able to set transparency on the popup because webview2 cannot perform like a real WPF control it's just a wrapper around the win32 version, has a hand and displays its pixels very different to true WPF.

**Comment by RobertGlobant20** [comment]
Ok, thanks for the answer
