### ISSUE TITLE
Webview2 - Fixed version : sometimes "not found"

### ISSUE THREAD

**Issue by jeff-1984** [MicrosoftEdge/WebView2Feedback#2734]
**Description**
Hello,

I could successfully use the option to specify the path to a fixed version of WebView2 (CreateCoreWebView2EnvironmentWithOptions , parameter WEBVIEW2_BROWSER_EXECUTABLE_FOLDER - https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1293.44#createcorewebview2environmentwithoptions)

But... on some specific computers, this does not work, I just get an error "NOT FOUND".

I already tried to add the access rights on the folder as described here : https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution (icacls), but this has no impact.

The only thing I could find is a log in the event viewer that seems to be linked (in french) :
"Les paramètres d’autorisation propres à l’application n’accordent pas l’autorisation Local Activation pour l’application serveur COM avec le CLSID
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
et l’APPID
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
au SID JEAN-MAES-E580\jeang de l’utilisateur (S-1-5-21-2010270883-1447936690-2847641450-1001) depuis l’adresse LocalHost (avec LRPC) s’exécutant dans le SID Non disponible du conteneur d’applications (Non disponible). Cette autorisation de sécurité peut être modifiée à l’aide de l’outil d’administration Services de composants."

Is there any place where we could have a hint on the error ? Any idea why the folder is not found ?

With the evergreen version it's working, but we would like to avoid the automatic updates because we had an issue and we suspect this is linked to an automatic update.

For the moment, that "not found" problem is happening on 2 computers, 6 have no issue.

PS : The final application is a Java application using SWT + Edge brower (which is using the WebView2Loader.dll)

Thank you,
Jean-François

**Version**
SDK: 
Runtime: Tried different versions (95.?, 100.?)
Framework: Java / SWT over native WebView2Loader.dll (https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/174084/12/bundles/org.eclipse.swt/Eclipse+SWT+Browser/win32/org/eclipse/swt/browser/Edge.java)
OS: Win10, Win11

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by LiangTheDev** [comment]
The log in event log is about OS's PerAppRuntimeBroker that is not part of the Edge WebView2 Runtime. You might want to compare registry values under HKEY_CLASSES_ROOT\AppID\{15c20b67-12e7-4bb6-92bb-7aff07997402} from the machines that is working and machines that is not working.

I don't expect that to impact whether we could found the WebView2 Runtime though. As it is likely due to some permission issue, the best way is to use [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to capture which registry and files the application process tries to access to find the WebView2 Runtime and where some potential access denied happens. Then check the permission on the file/registry.
It seems that you are using  WEBVIEW2_BROWSER_EXECUTABLE_FOLDER environment variable to specify where to find the fixed version WebView2 runtime. If this is not the case, then we would want to check whether there is any some override set by this WEBVIEW2_BROWSER_EXECUTABLE_FOLDER environment variable or in registry under HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Edge\WebView2 or HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\WebView2.

**Comment by jeff-1984** [comment]
Hello,

Thank you for the advice with procmon. 
We could find that the directory what not accessed at all, the parameter was not passed for some reason on these two computers.

Then it's not a bug, sorry for the wasted time !
