### ISSUE TITLE
Microsoft.Web.WebView2 - set Response Property of CoreWebView2WebResourceRequestedEventArgs in WebResourceRequested event handler throws NullpointerException

### ISSUE THREAD

**Issue by LSeppA** [MicrosoftEdge/WebView2Feedback#275]
Hi, 

First of all thanks for the pre-release of the Microsoft.Web.WebView2.Wpf control. -I really love it!

Now I want to inform you about two issues in the .net wrapper:

Motivation: I have tried to implement an equivalent to the C++ WebView2APISample SettingsComponent.cpp method SetBlockImages

```
// Turn on or off image blocking by adding or removing a WebResourceRequested handler
// which selectively intercepts requests for images.
void SettingsComponent::SetBlockImages(bool blockImages) {
...
// Override the response with an empty one to block the image.
// If put_Response is not called, the request will continue as normal.
wil::com_ptr<ICoreWebView2WebResourceResponse> response;
CHECK_FAILURE(m_webViewEnvironment->CreateWebResourceResponse(
                            nullptr, 403 /*NoContent*/, L"Blocked", L"", &response));
}
```

in a test c# WPF application by adding following handler to webView.CoreWebView2.WebResourceRequested:

```
   private CoreWebView2Environment _coreWebView2Environment;
   private async Task InitializeAsync()
   {
   ....
   _coreWebView2Environment = await CoreWebView2Environment.CreateAsync();
   webView.CoreWebView2.AddWebResourceRequestedFilter(null, CoreWebView2WebResourceContext.Image);
   webView.CoreWebView2.WebResourceRequested += testWebView2ViewModel.CoreWebView2_WebResourceRequested;
   }
   ....
   private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
   {
      e.Response = _coreWebView2Environment.CreateWebResourceResponse(null, (int)System.Net.HttpStatusCode.Forbidden, "Blocked", string.Empty);
   }
```
and got 2 issues:
a) if parameter "Stream **Content**" of CoreWebView2Environment method CreateWebResourceResponse is set to **null** (like it is done in c++) a System.ArgumentNullException: 'Value cannot be null. ' will be thrown on calling time.
b) if e.Response property of the e handler argument is in origin null and a new value will be set, **the setter of the the Response property raises** a System.NullReferenceException: 'Object reference not set to an instance of an object.'.

**e.Response =** _coreWebView2Environment.CreateWebResourceResponse(**null**, (int)System.Net.HttpStatusCode.Forbidden, "Blocked", string.Empty);
fails.

I think both issues are bugs in the iterop wrapper.

Best from Vienna,
Sepp

[AB#26980001](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26980001)

**Comment by pagoe-msft** [comment]
@LSeppA thanks for raising this issue. I have filed a bug and we will have a fix soon!

**Comment by kissstudio** [comment]
umm... the same error. 
```   at Microsoft.Web.WebView2.Core.COMStreamWrapper.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__39_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebView2WindowsFormsBrowser.BrowserForm.<CoreWebView2_WebResourceRequested>d__6.MoveNext() in D:\WebView2Samples\WebView2WindowsFormsBrowser\BrowserForm.cs:line 57

**Comment by kissstudio** [comment]
please fix soon ^^

**Comment by kissstudio** [comment]
more clear.  its about failed to read request.
![image](https://user-images.githubusercontent.com/2771647/86201068-0f537080-bb91-11ea-91ee-e5698873b05f.png)

**Comment by kissstudio** [comment]
![image](https://user-images.githubusercontent.com/2771647/86201104-26925e00-bb91-11ea-9b91-ca02ece3cb1b.png)

**Comment by kissstudio** [comment]
hi, i have tried fix it and made it.  

first, we should dump the dll code
then add a test when access the raw response if its null.

if it is null, a raw response should be created. 

we have a method in the CoreWebView2Environment can create a raw response. its a instance method named CreateWebResourceResponse.


![image](https://user-images.githubusercontent.com/2771647/86342914-d7c8ef00-bc8a-11ea-80d7-3b6021c9c488.png)

so we should create a Environment instance field on CoreWebView2.
the CoreWebView2.Environment is a CoreWebView2Environment, should be inject from the begining of the call stack:

![image](https://user-images.githubusercontent.com/2771647/86343311-5e7dcc00-bc8b-11ea-8696-2c8a92c3f9b6.png)

CoreWebView2CreateCoreWebView2ControllerCompletedHandler

![image](https://user-images.githubusercontent.com/2771647/86343401-7fdeb800-bc8b-11ea-974a-daa30156b9b8.png)

CoreWebView2Controller
![image](https://user-images.githubusercontent.com/2771647/86343454-9127c480-bc8b-11ea-857a-19b916d9db87.png)

CoreWebView2
![image](https://user-images.githubusercontent.com/2771647/86343531-ab61a280-bc8b-11ea-9bdf-8edb78ccfc51.png)

After the environment has been added, Environment._nativeCoreWebView2Environment.CreateWebResourceResponse is available for creating a raw resposne. 

Another problem is missing rawRequest.Content null test in COMDotNetTypeConverter.cs. lets fix it.
![image](https://user-images.githubusercontent.com/2771647/86344647-18c20300-bc8d-11ea-9ef1-9a68f71efb93.png)


after all changes applied, rebuild the dlls
Microsoft.Web.WebView2.Core
Microsoft.Web.WebView2.WinForms

add ref to the sample projects WebView2WindowsFormsBrowser. 
use yourself code to process request rather than webbrowser.
![image](https://user-images.githubusercontent.com/2771647/86344951-81a97b00-bc8d-11ea-8f2c-24e5d72226fb.png)

then all works without errors.

**Comment by kissstudio** [comment]
yes , it works without errors,,, but with no effects on browser. nothing changed on response when i open devtools window to check if it really replaced...

**Comment by kzgrey** [comment]
Any idea of an ETA on this?  It looks like this would be the best way to reject/redirect page resources programmatically.

If there is a better method of achieving this, please advise.  Thanks!

**Comment by champnic** [comment]
This was fixed a while ago by we missed updating this thread. Should be in 1.0.674-prerelease+. Thanks!
