### ISSUE TITLE
Extra double quotes are included in the return string value from web-code by calling ExecuteScriptAsync

### ISSUE THREAD

**Issue by ahmed-salem-me** [MicrosoftEdge/WebView2Feedback#2752]
**Description**
When web-code returns a string; extra double quotes are included in the return value from ExecuteScriptAsync

**Version**
SDK: 1.0.1340-prerelease
Runtime: 
Framework: WPF
OS: Win10

**Repro Steps**
![image](https://user-images.githubusercontent.com/95217221/188468078-d358389f-964b-45ad-b638-8276e0174e2f.png)

![image](https://user-images.githubusercontent.com/95217221/188467978-79a891f6-e6d7-4814-9b6f-5250ccced976.png)

The tmp variable should just have "it" value no extra double quotes.

**Comment by david-risney** [comment]
This is actually intentional. The result of ExecuteScriptAsync is a JSON string representing the result of the script execution. In this case `getIt()` returns a string so the JSON string returned by ExecuteScriptAsync is itself a string. ExecuteScriptAsync doesn't return the value of the result string, but the JSON encoded result string. To get the value of the result string from ExecuteScriptAsync you'll need to parse the return value as JSON. If the result of `getIt()` returned an object, ExecuteScriptAsync would return the JSON representation of that object and you'd similarly need to parse it as JSON to extract any properties from it.

Especially with strings its easy for this to be confusing so we're adding another API to make this easier in the future to specifically get the value of the result if its a string from ExecuteScriptAsync.

This and related ExecuteScriptAsync issues are described in this doc [ExecuteScript JSON encoded results](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/javascript#scenario-executescript-json-encoded-results).
