### ISSUE TITLE
Cannot open local office files 

### ISSUE THREAD

**Issue by br1an-h** [MicrosoftEdge/WebView2Feedback#2774]
**Description**
When the flag "msOpenOfficeDocumentsInWebViewer" is passed as a browser argument, remote Office files (URL starting with "http://") can be viewed as expected, however local files (URL starting with "file://") just download instead.  This same behaviour is seen when using the Edge browser, with the same option enabled from the settings page, so not sure if this is a bug, or just the way it works.

I first raised this issue in another thread, and was asked to open it as a separate issue (see: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1959#issuecomment-1240020707)

**Version**
WebView2 control is 1.0.1343.22
C++ (VS2017 Pro)
Win 10

**Repro Steps**
Set the msOpenOfficeDocumentsInWebViewer option as an additional browser argument in the CoreWebView2EnvironmentOptions object, before passing to the CreateCoreWebView2EnvironmentWithOptions() function. E.g. opts->put_AdditionalBrowserArguments(L"--enable-features=msOpenOfficeDocumentsInWebViewer");

Then try navigating to a local office file. e.g. file://c:\mytestfile.docx, this will download instead of viewing the file, however, when navigating to an Office file on the web (URL starts with "http://" or "https://") the file is shown in the viewer as expected.

**Comment by yildirimcagri** [comment]
Hi, since the behavior is same in Edge, this would need to be fixed in the browser. You can file a bug via "Send Feedback" in Edge.  
However, for a workaround in WebView2, can you try using [SetVirtualHostNameToFolderMapping API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.1343.22 ) pointing to the office path and navigating to it as a HTTP URL? Alternatively, you can also try [WebResourceRequested event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=webview2-dotnet-1.0.1343.22) to set a custom response to a HTTP URL.

**Comment by hbl917070** [comment]
Edge or Webview2 does not have the ability to parse office files.
Edge or Webview2 can open an office file through a URL, which simply directs the URL to "Microsoft Office Online".
Therefore, the url of the office file must be a public url that can be accessed by the Microsoft server.
Neither local file nor local server will work.

Chrome can open local files of office files through this extension.
I'm not sure if there is any way to use it for webview2.
https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj

**Comment by yildirimcagri** [comment]
The document does need to be publicly accessible for Office Web Viewer to work, which means this won't work with local files. Closing for now, please let us know if you need any further help with this.
