### ISSUE TITLE
The drag and drop API in WinForms

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#2873]
How can I use just intoduced drag and drop API in WinForms? I registered all drag-n-drop events
```
                this.webView.DragDrop += WebView_DragDrop;
                this.webView.DragEnter += WebView_DragEnter;
                this.webView.DragLeave += WebView_DragLeave;
                this.webView.DragOver += WebView_DragOver;

```
but no one is ever raised.

Also there is new CoreWebView2CompositionController.DragLeave method which is not accessible in Winforms, because I have no way to get a CoreWebView2CompositionController instance. Or maybe there is a way, but I can't find it.

SDK: 1.0.1370.28
Platform: WinForms

**Comment by victorthoang** [comment]
Hello @mikeduglas,

Thanks for your inquiry. I've assigned your question to a dev that might best answer your question.

**Comment by mikeduglas** [comment]
Well, I found a way to get CoreWebView2CompositionController:
`    var compositionController = await environment.CreateCoreWebView2CompositionControllerAsync(hwnd);`
but still no idea how to use the drag and drop. This document https://github.com/MicrosoftEdge/WebView2Feedback/pull/1276/commits/c3fe5df025536f88ebfc81be1efc4b5e1c6f1117
is not informative.

**Comment by david-risney** [comment]
Drag and drop should work for the WinForms WebView2 element, but unfortunately won't raise the WinForms Control drag and drop events because of how WebView2 handles input.

The WinForms WebView2 element uses HWND hosting via the CoreWebView2Controller. The CoreWebView2CompositionController drag and drop APIs aren't helpful here because those are only applicable if you are directly hosting (not using a WPF/WinForms/WinUI2/3 WebView2 element) the CoreWebView2CompositionController (which uses composition APIs rather than HWND hosting which won't work with WinForms).

**Comment by novac42** [comment]
Hi @mikeduglas , does Dave's answer above address your question? If yes would you like to close the issue?

**Comment by mikeduglas** [comment]
If I understood correctly, the drag and drop API is not available in WinForms. Are there any plans to add this later?

**Comment by david-risney** [comment]
Yes, drag and drop should be working in WinForms even though those APIs aren't working. Can you describe what you're trying to do with those APIs? Sounds like this should be a feature request
(@bradp0721)

**Comment by mikeduglas** [comment]
I'm working on porting WebView2 (WinForms) to another program language (Clarion). I try to expose as many APIs as possible. Drag and drop API for WinForms was introduced in Release Notes (don't remember exact version), hence my question. If D'n'd API for WinForms is not planned, then so be it.
