### ISSUE TITLE
How to provide an instance of MyObject via AddHostObjectToScript and not only a namespace 

### ISSUE THREAD

**Issue by agenne** [MicrosoftEdge/WebView2Feedback#2879]
Hi,
we try to find a strategy for migration of our WebView Bridge to WebView2.
Platform **UWP**  

The documentation in this post is working for us:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=csharp

Our problem is, that we can only provide a namespace this way. But what we need is to provide an already created instance of an object. Is that possible somehow?

Assuming that MyClass is within the namespace Abc, we can provide the namespace this way:

      var dispatchAdapter = new WinRTAdapter.DispatchAdapter();
      webView.CoreWebView2.AddHostObjectToScript("Abc", dispatchAdapter.WrapNamedObject("Abc", dispatchAdapter));
 
What also worked for us is that:
      var myClass= new MyClass("...");
      webView.CoreWebView2.AddHostObjectToScript("bridge", dispatchAdapter.WrapObject(myClass, dispatchAdapter));

Can we do that? Any Risks?

The interface IDispatchAdapter has two more methods:
1. UnwrapObject
2. Clean

Could you please point out when to call this methods.
Is there any work to do in order to avoid leaks etc.?

It would be great to get some more informations. 

Thank You in Advance
Best Regards

[AB#41858230](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41858230)

**Comment by david-risney** [comment]
Thanks, great point! We're missing documentation for this. I've opened bug to track updating this.

> var myClass= new MyClass("...");
webView.CoreWebView2.AddHostObjectToScript("bridge", dispatchAdapter.WrapObject(myClass, dispatchAdapter));

Yes that's right. That is how you would add an object instance rather than a namespace.

> UnwrapObject

UnwrapObject takes the return value of a call to WrapObject and provides back the original parameter to WrapObject - myClass in this case. In most circumstances you shouldn't need this.

> Clean

The DispatchAdapter internally maintains a list of mappings from winrt objects to their wrapped counterparts. You can call Clean to have it remove any references in its internal map that are no longer required.

**Comment by agenne** [comment]
Thank You
