### ISSUE TITLE
Disable hotkeys 

### ISSUE THREAD

**Issue by Sulquendi** [MicrosoftEdge/WebView2Feedback#288]
Hello, i'd like to be able to disable all accelerator keys while using WebView2. I've read about an `AcceleratorKeyPressed `event but can't find it in C# Winforms... I tried with the existing `KeyDown `and `KeyUp`, (returning `e.SuppressedKeypress = true;`) and also with `KeyPressed` (returning `e.Handled = true;`) but no success... 

[AB#27045718](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27045718)

**Comment by pagoe-msft** [comment]
@Sulquendi 

Thanks for raising this issue! Its still early days for our WinForms control and as of now, we currently don't have a way to handle accelerator keys like we do in our Win32 and WPF controls. This functionality is on the roadmap!

**Comment by kirsan31** [comment]
Any news? Disable context menu will be good too.

**Comment by champnic** [comment]
The AcceleratorKeyPressed event will be exposed on the WebView2 .NET controls in the next prerelease SDK. In the meantime though, you can explicitly initialize the control and create a CoreWebView2Controller to listen to the [AcceleratorKeyPressed event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.acceleratorkeypressed?view=WebView2-dotnet-1.0.674-prerelease).

**Comment by kirsan31** [comment]
@champnic 
> In the meantime though, you can explicitly initialize the control and create a CoreWebView2Controller to listen to the [AcceleratorKeyPressed event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.acceleratorkeypressed?view=WebView2-dotnet-1.0.674-prerelease).

Thank you for your answer. Sorry, but I can't understand how to achieve this :( CoreWebView2 is uninitialized (null). I am create new `CoreWebView2Environment`, get `WebView2Controller` from it and than pass env to `EnsureCoreWebView2Async`. But it still creates its own `CoreWebView2Controller` and `CoreWebView2` instances:
![image](https://user-images.githubusercontent.com/17767561/97962765-e48b5a00-1dc6-11eb-905b-d438179bf26c.png)

**Comment by champnic** [comment]
The Handled issue is known and tracked in #549 - a fix should be available in the next SDK.

You're right - looks like we have a bug where the controller gets overwritten by the control, so unfortunately sounds like you'll have to wait for the next SDK when the API becomes available. I'm going to open a bug on our backlog for the controller issue. Thanks for the investigation here!

**Comment by pagoe-msft** [comment]
Hi Everyone,

This was addressed in the 1.0.707-prerelease version.

**Comment by champnic** [comment]
Hey all - I had a mistake in a previous response. The controller is not intended to be created or interacted with for the WPF/Winforms controls. It can be used directly if you are writing your own .NET control and using the CoreWebView2* classes.

The CoreWebView2Controller.AcceleratorKeyPressed events are forwarded to the WebView2.KeyDown events, and apparently have been for a while. We're removing exposing the AcceleratorKeyPressed event and have updated our documentation to try and make this more clear.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode

> Accelerator key presses (e.g. Ctrl+P) that occur within the control will fire standard key press events such as OnKeyDown. You can suppress the control's default implementation of an accelerator key press (e.g. printing, in the case of Ctrl+P) by setting the Handled property of its EventArgs to true. Also note that the underlying browser process is blocked while these handlers execute, so:
You should avoid doing a lot of work in these handlers.
Some of the WebView2 and CoreWebView2 APIs may throw errors if invoked within these handlers due to being unable to communicate with the browser process.
If you need to do a lot of work and/or invoke WebView2 APIs in response to accelerator keys then consider kicking off a background task or queuing the work for later execution on the UI thread.

I'm going to close this issue. Please let me know if you are running into other issues or are having trouble getting the events to work properly. Thanks!

**Comment by kirsan31** [comment]
@champnic thank you, but currently (1.0.664.37) this is not working due to KeyDown and focus bugs :(

1. The link you have provided is wrong?
2. WebView2 Can't be focused with mouse while in NonInit State. With tab focus change all is ok.
3. After Init, WebView2 can be focused with mouse, but KeyDown will behive wrong (see below). With tab focus change all is ok.
![WVHK](https://user-images.githubusercontent.com/17767561/100867125-c9d20100-34aa-11eb-810f-cbf5b62e4959.gif)
<details>
  <summary>Code</summary> 

```cs
public partial class Form1 : Form
{
    private string _LastText;
    public Form1()
    {
        InitializeComponent();
        webView21.KeyDown += WebView21_KeyDown;
    }

    private void WebView21_KeyDown(object sender, KeyEventArgs e)
    {
        string info = $"Key: {e.KeyCode}; KeyData: {e.KeyData}; Control: {e.Control}.\n";
        if (_LastText != info)
        {
            _LastText = info;
            richTextBox1.Text += info;
        }

        if (e.KeyData == (Keys.Control | Keys.G))
            e.Handled = true;
    }

    private async void btnInit_Click(object sender, EventArgs e)
    {
        await webView21.EnsureCoreWebView2Async().ConfigureAwait(true);
    }
}
```
</details>

`AcceleratorKeyPressed` (through reflection) works normally with both mouse and tab focus. But naturally only in the initialized state.
Repro:  
[WebView2Test.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5628959/WebView2Test.zip)

**Comment by champnic** [comment]
1. Sorry, that link was quite wrong. I've updated it 👍 
2/3. I saw you opened a separate issue (#721) for the focus problems, and we'll continue discussion/track fix using that.

**Comment by ryanroe** [comment]
> Any news? Disable context menu will be good too. Current keyboard support is near zero :( To catch keyboard (mouse too) events we need to use [Javascript](https://github.com/MicrosoftEdge/WebView2Feedback/issues/536), but if this is known combination - all is useless. For example we need `Ctrl+G` shortcut - we can handle it through Javascript but WebView2 will open search bar any way :((((

have you tried with javascript 
```js
window.onkeydown = (e) => {
  if(e.ctrlKey && e.code === 'KeyG') {
      e.preventDefault();
      return;
  }
}
```

i don't know if this works on wpf / winform version , but this works on [tauri](https://tauri.app)  :)

**Comment by otykier** [comment]
Why is this issue closed? As far as I can tell, even with the latest build for WinForms, it's still not possible to disable specific hotkeys (such as Ctrl+G) in order to redirect them to the parent?

**Comment by champnic** [comment]
@otykier Are you listening to the KeyDown event on the WebView2 control and marking Ctrl+G as handled?

**Comment by otykier** [comment]
@champnic yes, and this partly works in the sense that the WebView2 control ignores the keypress. However, I expected the KeyDown event to propagate up to the parent control/form in this case, but that doesn't happen.

**Comment by champnic** [comment]
Gotcha - Yes that's currently expected for WebView2. You can handle the event yourself if you want to in the WebView2 KeyDown or continue to propagate it manually. We're also working on a feature that would enable keyboard input handling to be more expected and inline with other Winforms/WPF behaviors. You can track that work here: #951 (it's not a direct duplicate, but the work entails routing input first through the UI frameworks/controls, rather than having input go straight to the WebView2 runtime hwnd).
