### ISSUE TITLE
UWP: how to properly set and reset WebView2's DefaultBackgroundColor

### ISSUE THREAD

**Issue by agenne** [MicrosoftEdge/WebView2Feedback#2899]
Hi,
we have to change our UWP app so that it now use the new WebView2.
Unfortunately there is no DefaultBackgroundColor available on the WebView2 which is very important for us.

First we found this post which stated that it will not be supported in winui3:
https://github.com/microsoft/microsoft-ui-xaml/issues/2992

and this one:
https://github.com/microsoft/microsoft-ui-xaml/issues/4378

After further research we found this post:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1621

and this one:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1604

Both suggest to set the DefaultBackgroundColor by setting a Environment Variable like so:
Environment.SetEnvironmentVariable("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "0");

We tried out and it worked well. The WebView become transparent.

Now we would like to know, if this undocumented way to make this work is officially allowed, and if there are risks to do so.

After some testing we found out, that it is not possible to set a specific color this way:
Environment.SetEnvironmentVariable("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "FF0000");

What is the correct syntax?

What we also need, is to reset this transparent color for WebView's which are created later on in the app.
Is that possible?

Thank You in advance

**Comment by johna-ms** [comment]
@agenne the environment variable is officially allowed, there aren't risks. The only issue is they do not support setting a given webview's background color more than once the way a normal xaml control's DefaultBackgroundColor field would.

I believe you should be able to set a different initial background color per webview by setting the environment variable between initializations.

Regarding the syntax, the environment variable requires you to set the value of the alpha channel, and that is read first. so AARRGGBB. The reason why FF0000 doesn't show is because the variable is read as 00FF0000. If you passed FFFF0000 instead, that would show red which I believe is the intent.

**Comment by johna-ms** [comment]
Provided instructions seem sufficient to solve your use case. If this is still an issue for you, please reopen this. But I am closing this for now.
