### ISSUE TITLE
Disabling Ads in Webview2

### ISSUE THREAD

**Issue by BrianRoach** [MicrosoftEdge/WebView2Feedback#2906]
Is there a setting for disabling webbased ads, note, these are not external pop up ads, but just embedded ads in webpages similar to what could be found on this webpage https://time.com/6220951/colonial-america-is-a-myth/

We have clients who are using sites like this for instructional purposes, and in standard Edge they can block the ads, but in the internal browsers in the app the ads are showing up and making it difficult for students to navigate the pages.  

I thought perhaps something to do with the UserAgent setting, but not clear if that is a valid solution.

**Comment by victorthoang** [comment]
Hello @BrianRoach, sorry for the delayed response,

How are your clients currently blocking ads today? Are they simply looking for a solution that is built into WebView2, or are you looking for a way for developers to programatically add an extension into WebView2? 

I know people have previously asked for this feature [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/191), but we haven't yet focused our efforts on this yet. 

Another option, is you could program your own ad blocker by blocking certain navigations within webview yourself, just not sure what kind of resources you have to pursue this as a workaround.

**Comment by victorhuangwq** [comment]
Closing the issue as stale

**Comment by thelittleerik** [comment]
Please add a possibility to manage extension on Webview2. For example I got a rainmeter extension that opens links directly and when a Webview2 instance pops up I want to be able to manage the profile of a default webview2 instance so I can add or remove extensions.

**Comment by 59de44955ebd** [comment]
FYI, even if the extension's icon can't be displayed, since the is no extension toolbar in WebView2, and therefor also no way to open a extension popup in the context of the current webview, the extension [uBlock Origin](https://ublockorigin.com/) works perfectly fine in a WebView2 project, it does what you want and removes all ads, but also disables malicious trackers etc. You can install it by [downloading the .crx file](https://superuser.com/a/1937868/1886300) from the [Edge addon store](https://microsoftedge.microsoft.com/addons/detail/ublock-origin/odfafepnkmbhccpbejgmiehpchacaeak), unpacking it with e.g. 7-Zip and then using [AddBrowserExtension(Async)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.addbrowserextensionasync) to install it in the current user profile.
