### ISSUE TITLE
 WIX Installer (.MSI) failing due to WebView2 runtime installer registry check

### ISSUE THREAD

**Issue by NagarajKSundar** [MicrosoftEdge/WebView2Feedback#2911]
Hi

We are using **Package bootstrapper as binary stream to use during app install**  to do the WebView2 runtime installer registry check.
but our installer fails with the below error and installation is not happening.

The machine we tried to install already has webview2 runtime installed

Image 1 : ![image](https://user-images.githubusercontent.com/116784388/198203049-7e328759-e39d-42cc-8cde-eab14a3ca0af.png)
Image 2 : 
![image](https://user-images.githubusercontent.com/116784388/198203210-ea71cee8-aec3-4fb2-b792-84923e1f1f9a.png)

we are following the below steps in our **product.wxs** file.

**Step 1:**

```
<Property Id="WVRTINSTALLED">
  <RegistrySearch Id="WVRTInstalled1" Root="HKLM" Key="SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" Name="pv" Type="raw" />
  <RegistrySearch Id="WVRTInstalled2" Root="HKLM" Key="SOFTWARE\Microsoft\EdgeUpdate\Clients{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" Name="pv" Type="raw" />
  <RegistrySearch Id="WVRTInstalled3" Root="HKCU" Key="SOFTWARE\Microsoft\EdgeUpdate\Clients{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" Name="pv" Type="raw" />
</Property>
<Binary Id="MicrosoftEdgeWebview2Setup.exe" SourceFile="C:\Users\source\setup dependency\MicrosoftEdgeWebview2Setup.exe"/>
<CustomAction Id='InvokeBootstrapper' BinaryKey='MicrosoftEdgeWebview2Setup.exe' Execute="deferred" ExeCommand=' /install' Return='check' />
```

**Step 2 :** Defining the custom action 

```
<Custom Action="CloseAppsPrompt" After="CostFinalize"></Custom>
<Custom Action='InvokeBootstrapper' Before='InstallFinalize'>
<![CDATA[NOT(REMOVE OR WVRTINSTALLED)]]>
</Custom>
```

**Note :**  We have followed the steps given in this sample : https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WV2DeploymentWiXCustomActionSample/Product.wxs

**Comment by dianaqu** [comment]
Could you share you whole product.wxs file?

**Comment by manijak** [comment]
We have noticed same issue recently with our installer package. What we found out is that the error is not comming from the new installer, but rather the old one. Since our installers are told to first uninstall the older version before installing the new one. So the older version is trying to uninstall Microsoft WebView2 Runtime from the machine, and that is not allowed. Therefore the error. 

So a question @dianaqu, how do we make sure our WiX Toolset installer does not try to uninstall the WebView2 runtime during an update or uninstall of our app? 

This has made a slight issue now in production for us, as users cannot seem to update or uninstall our app, because of the installer trying to remove WebView2...
