### ISSUE TITLE
Subclassing CustomNavigationStartingEventArgs Error

### ISSUE THREAD

**Issue by Ziebell-INL** [MicrosoftEdge/WebView2Feedback#2928]
I cannot descend from CustomNavigationStartingEventArgs.

When I attempt to descend from CustomNavigationStartingEventArgs I get a "'CustomNavigationStartingEventArgs' Does not contain a constructor that takes 0 arguments" error.

Please see the playground at https://dotnetfiddle.net/ILjnVx.

Any insights would be helpful. Thanks!

**Comment by victorthoang** [comment]
Hello @______,

Thanks for your inquiry. I've assigned your open issue to a dev that might best answer your question.

**Comment by Ziebell-INL** [comment]
Thanks @victorthoang. @yildirimcagri, Any thoughts?

**Comment by yildirimcagri** [comment]
Hi @Ziebell-INL , I don't think you can construct a CoreWebView2NavigationStartingEventArgs type or extend it. This class is only useful for handling the WebView2.NavigationStarting event, in which you get an instance from WebView2. What are you trying to achieve here by extending this class?

**Comment by Ziebell-INL** [comment]
@yildirimcagri, "I don't think you can construct a CoreWebView2NavigationStartingEventArgs type or extend it." Yes, exactly. You understand my problem.

Shouldn't I be able to use the default constructor in the CoreWebView2NavigationStartingEventArgs parent EventArgs? But I can't. Upon decomplication, CoreWebView2NavigationStartingEventArgs gives no reason why (e.g., a private parameterless constructor to hide the default constructor in EventArgs).

I am attaching to the WebView2 handlers and want to extend the custom EventArgs (i.e., CoreWebView2NavigationStartingEventArgs and CoreWebView2NavigationCompletedEventArgs) with additional properties for our custom logic to control synchronization across threads.

I often extend custom EventArgs to add properties, especially in WinForm applications.

From a C# perspective I do not understand why I can't call the default constructor.

Can you please explain to me what am I missing here?

**Comment by yildirimcagri** [comment]
Since a WinForms app can [raise generic events](https://learn.microsoft.com/en-us/dotnet/standard/events/how-to-raise-and-consume-events?redirectedfrom=MSDN), it is possible for the app to create EventArgs objects of certain WinForms control events that are functionally raisable, such as input events.  CoreWebView2 events are specific for the WebView, they always originate from WebView2 and an app cannot raise CoreWebView2 events. Therefore, an app cannot create any CoreWebView2 EventArgs objects. For your scenario, I'd recommend wrapping the CoreWebView2 EventArgs in your object for the custom logic you are implementing.
