### ISSUE TITLE
PDF response content stream not working

### ISSUE THREAD

**Issue by yalinluo** [MicrosoftEdge/WebView2Feedback#2944]
Trying to save a PDF from a web page using the 'WebResourceResponseReceived' event but the 'e.Response.GetContentAsync()' returns the web page HTML instead of the PDF stream. It seems that if a file with known supported type such as a PDF is always opened by the browser and the response stream got replaced by the browser HTML text. Interestingly, the 'content-length' header has the correct PDF file size information. This issue can be re-generated by browsing to a local file; e.g., file://c:\test.pdf.

**Comment by darbid** [comment]
I would very much love someone to help explain where the pdf is, although I have a sneaking suspicion it's not a bug, chromium does it. [i had a similar question](https://stackoverflow.com/questions/73673095/where-is-the-pdf-in-a-browser-response-where-content-type-is-application-pdf).

**Comment by yildirimcagri** [comment]
Since you are navigating to a PDF, for WebView2 and Edge browser, this activates the PDF viewer extension and the resource effectively gets overridden with the HTML that embeds the PDF. Instead of navigating, could you issue an XHR to the resource? If your use case requires the navigation flow (like a user link follow), you may use the NavigationStarting event to cancel the original navigation and issue the XHR then.

**Comment by darbid** [comment]
Thank you. So the answer is it I am not missing it the pdf is not exposed in anything.

**Comment by yildirimcagri** [comment]
Have you tried if [PrintToPdf ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.printtopdfasync?view=webview2-dotnet-1.0.1418.22) API works here by any chance?
