### ISSUE TITLE
WSUS: WebView2 Update v108.* missing

### ISSUE THREAD

**Issue by htcfreek** [MicrosoftEdge/WebView2Feedback#3034]
There is no Edge WebView2-Update to v108.* on WSUS available. When will it be available on WSUS?

**Comment by champnic** [comment]
It should be there:
https://www.catalog.update.microsoft.com/Search.aspx?q=webview2
<img width="453" alt="image" src="https://user-images.githubusercontent.com/45700886/206290821-adafebda-64f7-4bb2-a38a-998191c08718.png">

We had a slight delay in rolling out our 108 runtime as compared to the browser due to a pipeline issue that has since been resolved (this is also why our version is slightly different from the Edge browser).
