### ISSUE TITLE
Narrator can not complete the speech on changing text

### ISSUE THREAD

**Issue by BrightWind** [MicrosoftEdge/WebView2Feedback#3055]
**Description**
When focusing on an ui element with changing text  on a web app hosted on Edge or hosted  on Webview2 app, Narrator can complete reading the text of the element for the first time, the following repeated speech will always be broken which bring pretty bad experience.  As a versus, Chrome will not repeat the speech.

**Version**
SDK: 1.0.1264.42
Runtime: 103.0.1264.77
Framework: WPF
OS: Win10, Version	10.0.19045 Build 19045

**Repro Steps**
1. Load the demo html on webivew2 app or Edge or chrome
2. Launch window narrator.
3. Use tab to move the focus to the text element "The time has ellapsed for ... milliseconds"

**Screenshots**
![Accessiblity tree on different browser](https://user-images.githubusercontent.com/12066973/207011104-f30a0cc3-c598-4772-817e-47f31a979e17.jpg)

**Additional context**
Demo code
[accessibility-test.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10243700/accessibility-test.zip)

**Comment by bradp0721** [comment]
From the description, this issue is not WebView2 specific and is actually a browser issue. If you are able to repro the issue in the current Edge stable channel (Edge 109), will you please file feedback through the Edge app and also include the Chrome version you're using that doesn't repro the issue? That will route the issue to the correct team.
