### ISSUE TITLE
How does one trap accelerator keys when using WebView2 with Windows App SDK

### ISSUE THREAD

**Issue by duncangroenewald** [MicrosoftEdge/WebView2Feedback#3098]
I need to trap the CTRL+A or ALT+A keystroke combination while the WebView2 has the focus either before or after WebView2 received them - preferably before.  

There doesn't seem to be any example of how this can be achieved although there are lots of references to the AcceleratorKeyPressedEvent but it does not appear to be available on WebView2 or WebView2.CoreWebView2.

**Comment by victorthoang** [comment]
Hello @duncangroenewald,

Thanks for your inquiry! I've assigned this to a dev that might best answer your question.

**Comment by bradp0721** [comment]
I reached out to the WinUI3 owners and unfortunately, there is not currently a way to intercept accelerator keys. The CoreWebView2Controller does raise the AcceleratorKeyPressedEvent, but the WinUI3 WebView2 element does not expose that functionality.

I'd recommend opening an issue in the [Windows App SDK GitHub](https://github.com/microsoft/WindowsAppSDK) repo for adding an accelerator key mechanism (similar to [CoreDispatcher.AcceleratorKeyActivated](https://learn.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.acceleratorkeyactivated?view=winrt-22621) from UWP).

Otherwise, you can use a similar mechanism to what RickStrahl linked above, which involves receiving the input in the web page and using one of the JavaScript to native communication channels to notify your app code about the accelerator keys.

**Comment by applefanbois** [comment]
Wake up Microsoft, you are 15 years behind Android, iOS, macOS and Linux.

I need this feature for yesterday.

When I getangry customers that complain about why they cannot search in their app like the apple version, I give them this link.
