### ISSUE TITLE
webview2 crash on start

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#3113]
Use the webview2 installed in the system, the version information is as follows:
![image](https://user-images.githubusercontent.com/48123998/211263057-91b169ec-0c5d-4e8f-84a2-d88c84d5896a.png)

Use the test program provided by WebView2Samples
https://github.com/MicrosoftEdge/WebView2Samples/releases

The crash error message is as follows：
![image](https://user-images.githubusercontent.com/48123998/211263538-b01a8435-4910-47f7-bb4f-bbd757a2e934.png)

Many of our customers have been affected by this error, I would like to know how to fix this error.

**Comment by LiangTheDev** [comment]
The exit code suggests that the renderer process was terminated due to some dlls injected into the process does not have trusted signature. It is most likely due to third party software like antivirus products injecting dlls into processes. Some antivirus software like Symatec has addressed the issue and updating to latest version should fix the issue.
To quickly determine whether it is indeed due to dlls injected into WebView2 processes, you can try to set environment variable WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS with value of --disable-features=RendererCodeIntegrity and see whether that makes a difference.
If it does make a difference, you can try to use Event Viewer (eventvwr.exe) to check events in Microsoft-Windows-CodeIntegrity/Operational channel. There should be events indicating which dlls are causing trouble for msedgewebview2.exe process. If you don't know how to do this, you can share %SystemRoot%\System32\Winevt\Logs\Microsoft-Windows-CodeIntegrity%4Operational.evtx and we can take a look.

**Comment by ztextplus** [comment]
@LiangTheDev  thanks very ,much, will check this on our customer's computers.
