### ISSUE TITLE
[DMC] Document that CoTaskMemFree is necessary after GetAvailableCoreWebView2BrowserVersionString #791

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#313]
Please review this customer feedback, and make the doc fix as needed. Thank you.
https://github.com/MicrosoftDocs/edge-developer/issues/791

[AB#37258039](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37258039)

**Comment by Reezaali** [comment]
@Urmeli0815 - I opened this issue for the engineering team to review. Thanks.

**Comment by quietfanatic** [comment]
We have the general convention documented at https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/win32-api-conventions#strings, but for easier access we're making it so that the documentation for any function that returns an LPWSTR mentions to use CoTaskMemFree.  These changes will be coming with a prerelease package soon.
