### ISSUE TITLE
Webview2 breaking W11 alt-tab and taskbar click - cannot focus windows/apps, certain windows get stuck in foreground

### ISSUE THREAD

**Issue by haveabyte** [MicrosoftEdge/WebView2Feedback#3157]
**Description**
In Windows 11, I randomly cannot click a taskbar icon for an app or window, or click the window itself, or alt-tab to the window, in order to focus it.  It stays behind other Windows.  Happens randomly with various apps.  New apps launched appear behind other windows and cannot be brought to the foreground.

**Version**
OS: Win11 Pro 22H2 22621.1105
Webview2:  109.0.1518.61
Edge:  109.0.1518.61

**Repro Steps**
Most commonly occurs with Chrome but can occur at any random time, with any window becoming a dominant foreground window which cannot be backgrounded.  Steps are to simply use apps normally until it occurs, then note that ALT-TAB, clicking taskbar, Win+R, or even directly clicking on the backgrounded windows themselves will not bring them into the foreground until the foreground-dominant "always on top" app is closed or restarted.

**Screenshots**
n/a

**Additional context**
This has been going on for months, prior to update 22H2 even.  

Issue acknowledged as Taskbar/Webview2 interaction problem over a year ago by Visual Studio team.  I do not have Visual Studio installed.  I'd rather not install 7 GB+ worth of stuff in the hopes that the fix is there, particularly given that Webview2 is a core Windows/Edge component.

https://developercommunity.visualstudio.com/t/window-switching-in-window-11-taskbar-stops-workin/1597282

**Comment by AndrewXY44** [comment]
I would like to add my voice to this issue. I am seeing intermittent results with this bug. I have deployed 30 new Lenovo laptops at work and this issue is intermittently happening on 90% of them. Why it isn't every device and why it can disappear for a couple of days and then come back again I don't know. I have not been able to find a way to successfully replicate the problem and the only fix I have for a short period of time is to reboot the device.
I have tried resetting the devices, and a clean W11 install with no success. I have removed the Webview2 Runtime and this makes no difference, in fact, MS just re-installs it straight away.
I have tried every fix listed in this MS forum with no joy https://answers.microsoft.com/en-us/windows/forum/all/windows-11-difficulty-to-bring-a-window-to-the/ee10a155-1647-472a-9740-fdeb888f7f71?page=1 It would be great if someone who has found a fix could update everyone.
Crossy

**Comment by haveabyte** [comment]
>The Windows team was also looking at making the Taskbar more resilient to these scenarios.

Yeah that seems to be ongoing or forgotten.

>Are you seeing the same application always get stuck

It varies.  It's my work/game rig so most common applications it happens with are Chrome (Ctrl-N for new window often opens behind existing window and the new cannot be focused without restarting Chrome), and Discord.

It's hard to give a specific example which acts as reliable steps to reproduce - it's very random, but definitely most common with Ctrl-N or Ctrl-Shift-N in Chrome, but Chrome is not the only app that gets stuck, and the similiarities between the types of app that do this are minimal to non-existent.  Quickbooks 2017 is pretty old but it gets stuck in foreground, Discord sometimes.  Most common manifestation is Win+R (run dialog) or clicking a shortcut on desktop to a file folder opening behind Chrome, Quickbooks, Discord, or some other app that happens to be running.

Maybe something _built_ with VC is accessing some internal VC runtime that is still spamming, which hasn't been updated because I don't have VC installed?  Perhaps?

**Comment by haveabyte** [comment]
I'm home W11 Pro at home and not joined to Azure and the problem happens every day.

**Comment by bradp0721** [comment]
With this happening to several different apps, what makes you believe this is a WebView2 issue? For sure, Chrome is not using WebView2.

The Visual Studio issue was not related to the VC runtime. It was specifically that the Visual Studio app started using WebView2 for part of its debugging UI and was constantly calling a WebView2 API to update a real-time graph in the html. This was fixed in the WebView2 Runtime (since v102). The linked Visual Studio issue only reproed while Visual Studio was actively debugging a VS solution.

Other than the linked Visual Studio issue, is there something else that indicates WebView2 is at fault? Any app calling AllowSetForegroundWindow too frequently could cause the Win11 TaskBar to not be able to foreground other apps. I'm wondering if this is actually a separate issue that should be opened raised to the Windows team.

**Comment by haveabyte** [comment]
I believed that due to this quote from the original thread:

[https://developercommunity.visualstudio.com/t/window-switching-in-window-11-taskbar-stops-workin/1597282]

"This issue is caused by an interaction between the WebView2 component used by Visual Studio and the Windows 11 taskbar. The Windows 11 taskbar team is currently actively investigating.

Update: the Windows 11 taskbar team has a fix, which makes the taskbar resilient to the issue triggered by WebView2, but it is uncertain when that fix will be released. However, the WebView2 team also has a fix so that WebView2 won’t trigger the problem in the first place. We expect that fix to be rolled out in the next stable WebView2 release in early March. We will provide further information here when that fix is available (for most people, their WebView2 installation should update automatically when the new release rolls out)."

In other words, I think the core Webview2 bug occasionally (and repeatedly) triggers a seperate, related malfunction in the Taskbar code which prevents it from focusing something when clicking an app on the taskbar, or alt-tabbing, in other words, focus is requested but the Taskbar malfunction triggered by Webview2 prevents it from doing so, even if Chrome was not the triggering application - it was triggered by Webview2, and while they fixed it in VC, they didn't fix it in the core Webview2 component that is part of Edge and thus part of all Windows installations.

It's conjecture, I admit, due merely to the similarity between the behaviors described, in a scenario that doesn't include VC, but does include Webview2 and the issue has already been acknowledged there by the Webview2 and VC teams, and to some extent, the Taskbar team.

**Comment by bradp0721** [comment]
> It's conjecture, I admit, due merely to the similarity between the behaviors described, in a scenario that doesn't include VC, but does include Webview2 and the issue has already been acknowledged there by the Webview2 and VC teams, and to some extent, the Taskbar team.

It's not clear to me that WebView2 is included in this scenario. Chrome does not use WebView2 and I'm not aware of Discord, Quickbooks, or Steam using it either (but I don't know for sure).

The comment on the VS issue is over a year old. The Visual Studio person who wrote that comment was not aware when the WebView2 fix would ship. The WebView2 fix was shipped in the v102 runtime. The TaskBar malfunction could be being triggered by something other than WebView2 but in a similar manner as the fixed WebView2 issue. That's why I said this might be an issue that needs to go to the Windows team.

To help confirm whether this is or isn't WebView2, can you look in TaskManager and see what apps you have that are using WebView2? When the issue happens, can you terminate the msedgewebview2.exe instances? Does the issue continue to repro?

**Comment by haveabyte** [comment]
@bradp0721 sorry I missed part of your previous message, I didn't look closely enough.

In Task Manager, under Details > msedgewebview2.exe (there are 6 of these) - there's one that's described only as Microsoft Edge Webview2 which I believe is running all the time for Windows itself, and 5 for an ASUS motherboard app called Armoury Crate. 
 Described as ArmouryWebBrowserEdge.  I'm quite sure this is related to the ASUS Armoury Crate, a clunky but useful app included on my new Asus mobo for driver downloads and various other tasks like pushing content recommendations that I don't use it for.  This app is not in startup, has no icon, and does not appear to currently be running when the problem manifests, as it's used as a hit-and-run app only.  But there is a service.  Here's the full list of descriptions associated with that msedgewebview2.exe process:

ArmouryWebViewEdge - Webview2 Manager
Microsoft Edge Webview2
ArmouryWebViewEdge - Webview2 GPU Process
ArmouryWebViewEdge - Webview2 Utility: Network Service
ArmouryWebViewEdge - Webview2 Utility: Storage Service
ArmouryWebViewEdge - Webview2: Armoury Peripheral

Service:  "C:\Program Files\ASUS\ARMOURY CRATE Lite Service\ArmouryCrate.Service.exe"

When I stop the service and set it to manual, the associated msedgewebview2.exe processes are still there, which surprised me.

Now, the service is stopped and I manually terminated all the msedgewebview.exe processes.

I noticed some lingering msedge.exe processes - then I notice that when I terminate them, then re-launch Edge, it launches 14(!) msedge.exe processes, and when closing Edge app, 6 msedge.exe processes remain - which is annoying, but it did not launch any msedgewebview2.exe processes.  I terminated these as well.  So there are literally no msedge*.* processes at all.

Yet, the problem still occurs - it's very common with switching from Discord to Chrome, but those are the most common apps I'm sitting in most of the time.  However, restarting with this Armoury service disabled might accomplish something, since those apps were already running at the time that those processes existed.  I'll update if it made a difference, but I suspect it won't.

**Comment by haveabyte** [comment]
Disabling ArmouryCrate services and manually terminating its leftovers via Task Manager ultimately didn't help.

Did tons of experimentation, even trying 2 utilities that show me what window has active/focus/etc with lots of detail.  Interestingly, nothing changed in these apps when the problem occurred.

Today I tried something that might have worked - I disabled Settings > Multitasking > Snap Windows in the Windows 11 Settings App.  I've tinkered a bit with this before but generally enjoyed having it on, although I kinda forgot about it and never relied on it.  Turned it off, and haven't had the problem occur all day, and normally it's many MANY times per day.

Will start an alternating schedule of one day off and one day on to verify this is in fact the cause, and then from there try to work up reliable steps to reproduce.  Hopefully I didn't fix it accidentally with some other change that I don't know about, but I tried to document everything here which I have done that might affect this.

**Comment by haveabyte** [comment]
Well, disabling Snap Windows didn't solve it.  Seemed to lessen it a bit.  I'm near the point of giving up trying to solve this.  Working around it by constantly restarting apps is preferable to endless troubleshooting of the most basic feature of windows - SHOW THE WINDOW I CLICK WHEN I CLICK IT, AND LAUNCH NEW WINDOWS IN THE FOREGROUND - not working.

**Comment by haveabyte** [comment]
The longer I"ve run with "Snap Windows" disabled, the more this problem appears to be solved.  I'm not sure why it wasn't at first, it may have occurred a few more times, but in the last weeks while I've had this setting disabled, the problem has pretty much gone away.
