### ISSUE TITLE
I want the behavior of the IsPasswordAutosaveEnabled property to match Edge

### ISSUE THREAD

**Issue by tatkobayashi** [MicrosoftEdge/WebView2Feedback#3197]
**Is your feature request related to a problem? Please describe.**

By setting the IsPasswordAutosaveEnabled property to true, it is possible to save the authentication information once entered.
However, since the behavior is different from Edge, I would like to have it aligned.

In Edge, if you save the password at the first authentication, the authentication screen will not appear on subsequent accesses.

But if you set the IsPasswordAutosaveEnabled property to true in WebView2,
Even if you save the password at the first authentication, the authentication screen will be displayed at the time of subsequent access.
(The authentication screen is displayed, and the saved values are set in the user name and password fields.)

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by monica-ch** [comment]
The is the expected behavior of setting saved username and passwords for all the subsequent requests with `IsPasswordAutosaveEnabled`. However, if you want to avoid authentication login print you must provide the username and password using [basicauthenticationrequested](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.basicauthenticationrequested?view=webview2-dotnet-1.0.1518.46) api.
