### ISSUE TITLE
CoreWebView2NewWindowRequestedEventArgs.IsUserInitiated has wrong value when script is executing

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#3255]
**Description**
When a `NewWindowRequested` is triggered by a `window.open` call inside a `setTimeout` then `IsUserInitiated` is set to `false` properly. However if WebView2 is executing a script using `WebView2.ExecuteScriptAsync` while this happens then `IsUserInitiated` is set to `true`.

**Version**
SDK: 1.0.1671-prerelease
Runtime: Evergreen, 110.0.1587.57
Framework: WPF
OS: Win11

**Repro Steps**
1. Set up a timer to call `WebView2.ExecuteScriptAsync("console.log('stuff happening');")` every second
2. Add an event handler to `NewWindowRequested` and check the value of `IsUserInitiated`
3. Or alternatively just clone [this branch](https://github.com/q71114/WebView2Samples/tree/bug/popup-requested-while-executing-script) I created from the WebView2Samples.
4. Navigate to https://permission.site
5. Click on the button `Popup (delayed 5 seconds)`
6. A popup should appear after 5 seconds

**Expected:**  `IsUserInitiated` value for the popup request should be `false`
**Actual:**  `IsUserInitiated` value for the popup request is `true`

**Additional context**
If `WebView2.ExecuteScriptAsync("console.log('stuff happening');")` is commented out the proper  `IsUserInitiated` value is reported

[AB#47659344](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47659344)

**Comment by monica-ch** [comment]
@q71114 

NewWindowRequested `isUserInitiated` flag received by WebView2 from the edge/chromium platform without any changes and provides information about user activation. About user activation [HTML spec](https://html.spec.whatwg.org/multipage/interaction.html#tracking-user-activation)

In case there if there is some sort of user interaction with window.open the `isUserInitiated` flag is true. Here, User interaction does not necessary means human involvement, but also can be caused by some calls on the parent page (here execute scripts).
Our recommendation is to never ignore isUserInitiated flag, but for this particular use-case you will need to write workaround this case in your app.

**Comment by q71114** [comment]
Thanks @monica-ch for the details.

> Our recommendation is to never ignore isUserInitiated flag, but for this particular use-case you will need to write workaround this case in your app.

I’m not sure how we can work around this without ending up with false positvies/negatives.
Could you give me any pointers please?
