### ISSUE TITLE
OnNavigationCompleted callback is sometimes called twice for a Navigation call

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#3292]
**Description**

**Version**
SDK: .0.1264.42 release
Runtime: 110.0.1587.63
Framework: Win32
OS: Win10

**Repro Steps**

1. call Navigate(url);
2. receive OnNavigationCompleted two times:
    - OnNavigationCompleted get_IsSuccess: [**false**] get_WebErrorStatus:[**COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED**]
    - OnNavigationCompleted get_IsSuccess: [**true**] 

The interval between two OnNavigationCompleted is about 1 second. This problem is not inevitable. When our customers use the VPN network, the probability of occurrence is relatively high.

**Comment by yildirimcagri** [comment]
Hi @ztextplus , from what you are describing it sounds like this is happening due to a network issue that is failing the original navigation and the retry logic in WebView2 redoes the navigation. If that is the case, this would be by design as WebView2 will also [report failed navigations](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2navigationcompletedeventargs.issuccess?view=webview2-dotnet-1.0.1661.34#microsoft-web-webview2-core-corewebview2navigationcompletedeventargs-issuccess).
