### ISSUE TITLE
Why are my my own custom menu items not firing?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3300]
If I use the built-in menu then all the items work, including my own.

But, as soon as I add the sample code to use the Win32 menu:

```
CHECK_FAILURE(items->get_Count(&itemsCount));
auto showMenu = [this, args, itemsCount, items, target] {
	CHECK_FAILURE(args->put_Handled(true));


	HMENU hPopupMenu = CreatePopupMenu();
	AddMenuItems(hPopupMenu, items);
	HWND hWnd;
	m_pImpl->m_webController->get_ParentWindow(&hWnd);
	::SetForegroundWindow(hWnd);
	RECT rct;
	::GetClientRect(hWnd, &rct);
	POINT topLeft{};
	topLeft.x = rct.left;
	topLeft.y = rct.top;
	::ClientToScreen(hWnd, &topLeft);
	POINT p;
	CHECK_FAILURE(args->get_Location(&p));
	RECT bounds;
	CHECK_FAILURE(m_pImpl->m_webController->get_Bounds(&bounds));
	double scale;
	m_pImpl->m_webController3->get_RasterizationScale(&scale);

	INT32 menuItemID{};
	m_itemPrint->get_CommandId(&menuItemID);
	::SetMenuItemBitmaps(hPopupMenu, menuItemID, MF_BYCOMMAND, (HBITMAP)m_bmpPrint, (HBITMAP)m_bmpPrint);
	m_itemRefresh->get_CommandId(&menuItemID);
	::SetMenuItemBitmaps(hPopupMenu, menuItemID, MF_BYCOMMAND, (HBITMAP)m_bmpRefresh, (HBITMAP)m_bmpRefresh);
	m_itemFind->get_CommandId(&menuItemID);
	::SetMenuItemBitmaps(hPopupMenu, menuItemID, MF_BYCOMMAND, (HBITMAP)m_bmpFind, (HBITMAP)m_bmpFind);


	const INT32 selectedCommandId = ::TrackPopupMenu(
		hPopupMenu,
		TPM_TOPALIGN | TPM_LEFTALIGN | TPM_RETURNCMD,
		bounds.left + topLeft.x + ((int)(p.x * scale)),
		bounds.top + topLeft.y + ((int)(p.y * scale)), 0, hWnd,
		nullptr);
	CHECK_FAILURE(
		args->put_SelectedCommandId(selectedCommandId));
};
wil::com_ptr<ICoreWebView2Deferral> deferral;
CHECK_FAILURE(args->GetDeferral(&deferral));
RunAsync([deferral, showMenu]() {
	showMenu();
	CHECK_FAILURE(deferral->Complete());
	});

```

Only the built-in menu items work (like Inspect).

Example:

```
if (!m_itemOpenFileLocation)
{
	CString strMenuText;
	strMenuText.LoadString(IDS_STR_MENU_OPEN_FILE_LOCATION);
	CHECK_FAILURE(webviewEnvironment->CreateContextMenuItem(
		strMenuText, nullptr,
		COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND, &m_itemOpenFileLocation));

	CHECK_FAILURE(m_itemOpenFileLocation->add_CustomItemSelected(
		Callback<ICoreWebView2CustomItemSelectedEventHandler>(
			[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
			{
				appWindow->GetParentWindow()->SendMessage(WM_COMMAND, ID_DISPLAY_WORKING_FOLDER, NULL);

				return S_OK;
			})
		.Get(), nullptr));
}
CHECK_FAILURE(items->InsertValueAtIndex(itemsCount, m_itemOpenFileLocation.get()));
```
Why is my own handlers not working with the Win32 version of the menu? I looked at the [Context Menu API ](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/context-menus?tabs=csharp)and I can't work it out.

[AB#43991012](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43991012)

**Comment by ajtruckle** [comment]
I checked the return value of `TrackPopupMenu` and that matches the item I chose. It is just not running the actual event handler which posts the message using `SendMessage`..

**Comment by ajtruckle** [comment]
Hi @yildirimcagri 

I look forward to your clarification about this matter.

Thank you in advance. 😊

**Comment by yildirimcagri** [comment]
Hi @ajtruckle , thanks for reporting this! There was a bug that prevented the CustomItemSelected event from firing for custom items in custom context menus even though the SelectedCommandId is set and we have a fix in the works which should make it to Edge 114.

**Comment by ajtruckle** [comment]
@yildirimcagri Awesome. When it is stable I can test for you. Please let me know in due course.

**Comment by ajtruckle** [comment]
Hi @champnic 
My stable version of Edge / Runtime is 112.0.1722.58 so when will 114.0.1796.0+ become the default? 🤔

**Comment by champnic** [comment]
Hey @ajtruckle - Stable ships roughly every month, so 113 is scheduled around the beginning of May, and 114 is scheduled around the beginning of June.

**Comment by ajtruckle** [comment]
Hi @champnic Thats great. Look forward to it. My only other main gripe with WebView2 context menu (not native) is that we can’t specify the short description (hotkey) for the right. This seems a major omission IMHO. I did request it in another ticket and was told to use the native menu. That decision surprised me. Also, in another ticket I mentioned about changing icons when themes change. I found a workaround d and then a member of staff suggested another way which did not work as far as I can see and they never got back to me. 

My application is now live with WebView2. I just keep an eye on all my interested tickets. Like improved Find UI and associated API to invoke default. It all went quiet.

**Comment by champnic** [comment]
Thanks for the feedback. We're working on improving our GitHub responsiveness and clarity. I took a look at the HotKey issue. I think the challenge is that across WebView2 we don't have enough resources to get to every request or feature improvement, so we have to prioritize what we do based on a number of factors indicating the expected impact of doing that work. 

A general policy that came out of that is that we try to expose as many features from the browser engine as we can, but rather than creating tons of knobs and options for every feature, we will provide either the default browser experience, or the ability for the app to build their own custom option. With the Context Menu we did a bit more configuration than we normally would, by allowing devs to edit the default list of context menu options. But in your case we didn't quite go far enough, in that we can add custom options but not add a shortcut key, or shortcut key string. For other devs the limitation can be lack of icons, or images, or default theming, or font, or positioning, etc. Besides the bug with the tab character, our general policy is that if devs want more customization then they have to build their own. This isn't a great answer and can be varying degrees of cost and complexity for the devs, but allows us to focus on other more pressing issues that may be completing blocking an experience. I wish we did have more resources, because I agree that it's a reasonable addition to the context menu API (though I'm not the owner of that particular area).

Can you link the other item you mentioned around icons?

**Comment by champnic** [comment]
And congrats on going live with WebView2! Please let us know if your users come back with other feedback :)

**Comment by ajtruckle** [comment]
@champnic Here. See last few comments:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/3346

**Comment by champnic** [comment]
Took a look. My guess is it's just a mistake. Sometimes we offer potential workarounds without necessarily having the time to try them out ourselves.

**Comment by ajtruckle** [comment]
@champnic Alright. That is fine. But an acknowledgment like you provided me would have been courteous. 👍
