### ISSUE TITLE
Popup window - scroll wheel not work - bug?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3322]
Code:

```
void CWebBrowser::ShowFullScreen(const CString strFilePath)
{
	if (m_pImpl->m_webView)
	{
		CRect rctSize;
		CWnd::GetDesktopWindow()->GetWindowRect(rctSize);
		rctSize.DeflateRect(10,10);
		CString strJS;

		strJS.Format(L"window.open('%s', 'customWindow', 'width=%d, height=%d, top=%d, left=%d')",
			strFilePath.IsEmpty() ? GetLocationURL() : EncodeFilePathToUrl(strFilePath),
			rctSize.Width(), rctSize.Height(), rctSize.top, rctSize.left);

		m_pImpl->m_webView->ExecuteScript(strJS,
			Callback<ICoreWebView2ExecuteScriptCompletedHandler>(
				[](HRESULT error, PCWSTR result) -> HRESULT { return S_OK; })
			.Get());
	}
}
```
I am unable to scroll the popup window with the mouse.

**Comment by ajtruckle** [comment]
@bradp0721 Thoughts? Still behaving this way. 🤔

**Comment by ajtruckle** [comment]
Hi @bradp0721 Have you been able to investigate this. A bug perhaps?

**Comment by novac42** [comment]
Hi @ajtruckle I will reach out to him for an update or see if it should be assigned to someone else. Sorry for the wait!

**Comment by ajtruckle** [comment]
@novac42 Please ask someone else. It has been 3 weeks.

**Comment by ajtruckle** [comment]
@champnic ?

**Comment by champnic** [comment]
Hey @ajtruckle - Sorry for the delay here. 

1. Can you share the version numbers you are seeing this with?
2. Does your app handle the NewWindowRequested event and do anything special there, or is this the default window that's getting shown?
3. Is focus getting set to the new window, or does clicking into the window first fix the scrolling?

My assumption is also that this would repro without the sizing constraints, and if the javascript were run directly on the page instead of using ExecuteScriptAsync, but those would also be things to try and see if they have an effect.

**Comment by ajtruckle** [comment]
Thanks for replying @champnic .
The version info is:

- WebView2 Runtime Version: 112.0.1722.34
- WebView2 SDK Build: 1661.34

My app does not handle the `NewWindowRequested` event and I do nothing specifically in the way of setting focus. I just execute that javascript as per my code.

That said, I am finding that the scrolling is working OK now! 🤔 Maybe it was a glitch. Just bizarre! I know that I recently updated the runtime. I will check again tomorrow afternoon.

**Comment by champnic** [comment]
That's good to hear :) Let me know if you run into it again and we can reactivate this issue.
