### ISSUE TITLE
How to find the root cause when CoreWebView2.ProcessFailed raised?

### ISSUE THREAD

**Issue by szanto90balazs** [MicrosoftEdge/WebView2Feedback#3326]
For our use case we host multiple instances of WebView2 within a window and every now and then run into process failures in all our instances. Sometimes we can fairly easily provide clear repro steps (e.g. https://github.com/MicrosoftEdge/WebView2Feedback/issues/2359), but other times we can only find the crash dumps, but no repro steps (e.g. https://github.com/MicrosoftEdge/WebView2Feedback/issues/3202)

I'm wondering what other information we can collect on top of https://github.com/MicrosoftEdge/WebView2Feedback/tree/main/diagnostics that can help us open easily actionable issues for you. Do you have specific ETW providers which usually contains helpful information? Any other loggers we can enable?

I'm also wondering if `CoreWebView2.ProcessFailed` originate from the WebView2 code layer or the underlying Edge/Chromium layer? One idea I'm playing with is to automatically reload some of these pages on `CoreWebView2.ProcessFailed`, but I believe I would loose the travel log for that given page.

So besides your guidance on what information is recommended to be collected, I would be interested in if there's any best practices can be shared on how to handle `CoreWebView2.ProcessFailed`. Thanks 👍

**Comment by LiangTheDev** [comment]
Sharing the stack or bucket id from related Windows Error Reporting events using Event Viewer should provide enough info for us to start investigation of those crashes. For https://github.com/MicrosoftEdge/WebView2Feedback/issues/3202, we actually have enough information from the stack to start looking on it. I'll ensure that the issue got proper attention.

For handling ProcessFailed events (log telemetry events so that we know that it occurred and we could get alarmed if the rate becomes high):
 - If it is browser process failed, recreate WebView
 - If it is renderer process failed, reload the page (ignore if failed happened before we even started navigation), for non responsive renderer, ignore it unless it repeatedly happening for a long time. The non responsive event is raised every 30s if the renderer process stay as non responsive.
 - Ignore other process failures like GPU, utility process failure, Edge/Chromium will try to auto recover.

**Comment by LiangTheDev** [comment]
You could navigate WebView to edge://gpucrash/ to cause GPU process crash and edge://inducebrowsercrashforrealz to crash the main browser process. Other than those, you might have to manually kill the processes to trigger the process failures.

**Comment by szanto90balazs** [comment]
Thanks @LiangTheDev that's useful 👍 Last but not least, can I ask how often do you encounter crashes coming from the main host process (the process WebView2 is initialized)? Do you have some ballpark estimation? We track the number of Process.Failed events and also the number of .NET unhandled exceptions, but we don't really have a number / handle on how many native crashes occur in our main process (e.g. something horribly going wrong in `WebView2Loader.dll`. We want to track these crashes as well, but it would be great to get a sense whether it's worth doing it.

**Comment by LiangTheDev** [comment]
The main browser process crash is different from the app process crash.

For main browser process crash, it is not often, but not extremely rare either. Since it is not difficult to track, I would recommend tracking it. It more likely happened due to some regression in Edge. If you track it, you could alert us of the impact. In case it only impacts some apps, we might not be alerted from our telemetry system.

For app process crash itself, the crash is more likely to happen from EmbeddedBrowserWebView.dll that is loaded into the app process. It is hard to catch and log telemetry events. The process just crash and not reporting any events to the app. You might want to do some self hosting/testing with non stable Edge browser channel so that we can be aware of the crashes and alert us. 

We do monitor all those crashes, but might not always catch it early enough.
