### ISSUE TITLE
Does webview2 runtime need to be installed for each domain user?

### ISSUE THREAD

**Issue by ffireflyy** [MicrosoftEdge/WebView2Feedback#3338]
Our application is hosted by RemoteApp. We have no problem running the application when log in as administrator. However, if we run as any other user, we get error indicating the webview2 runtime is not found. Is there a way to make the runtime available to all users or do we have to install the runtime for each user?

BTW, the runtime was installed using the Evergreen download method while log in as administrator.

Thank you.

**Comment by LiangTheDev** [comment]
It might be related to how the WebView2 Runtime is installed. When "log in as administrator" to install it, do you run the installer "as administrator" or run the installer exe from an elevated cmd.exe? If not, the installer runs unelevated and will only install for the current user instead of installing it for the machine. If it is installed for the machine, it should be installed under "c:\Program Files (x86)\Microsoft\EdgeWebView\Application" folder and registered under HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}. If it is installed per user, it would be registered under HKEY_CURRENT_USER\Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5} and installed at %LOCALAPPDATA%\Microsoft\EdgeWebView\Application for the administrator account.
