### ISSUE TITLE
Different results when using Web Select and Select All / Copy / Paste

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3363]
WebView2 Runtime Version: 111.0.1661.62
WebView2 SDK Build: 1661.34
Platform: MFC Window32

If I use the Web Select feature and pick all the content like this:

![WebSelect1](https://user-images.githubusercontent.com/7985331/230317737-b2dc7359-034a-45ea-9c28-7a51c06c75e8.png)

And, then I paste it into Microsoft Word, it looks different to when I use Select All / Copy / Paste:

![WebSelect2](https://user-images.githubusercontent.com/7985331/230318070-ad6a6bff-969b-43ba-91e1-559c72e86080.png)

The left view is the results from Web Select and the right view is the results from standard clipboard shortcuts.

**Comment by champnic** [comment]
Hey @ajtruckle - my quick guess (I'm not super familiar with web select) is that your selection doesn't include the outer table information, which is why the table is not formatted correctly with web select. That aside, I believe you would see the same behavior in the Edge browser and that this is out of scope for WebView2 specifically. If so, can you use the Edge Send Feedback tool (... -> Help and feedback -> Send feedback, or alt + shift + i).
