### ISSUE TITLE
The group or resource is not in the correct state to perform the requested operation. (0x8007139F) when EnsureCoreWebView2Async with different language

### ISSUE THREAD

**Issue by ye4241** [MicrosoftEdge/WebView2Feedback#3389]
**Description**

In WPF Window1:
```csharp
        private async void Window1_OnLoaded(object sender, RoutedEventArgs e)
        {
            var options = new CoreWebView2EnvironmentOptions(null, "en");
            var environment = await CoreWebView2Environment.CreateAsync(null, null, options);
            await this.WebView2.EnsureCoreWebView2Async(environment);
            this.WebView2.CoreWebView2.Navigate("https://www.bing.com");
        }
```

```csharp
        private async void Window2_OnLoaded(object sender, RoutedEventArgs e)
        {
            var options = new CoreWebView2EnvironmentOptions(null, "zh");
            var environment = await CoreWebView2Environment.CreateAsync(null, null, options);
            await this.WebView2.EnsureCoreWebView2Async(environment);
            this.WebView2.CoreWebView2.Navigate("https://www.bing.com");
        }
```

The second window cannot EnsureCoreWebView2Async, the exception is, 
```
System.Runtime.InteropServices.COMException: 'The group or resource is not in the correct state to perform the requested operation. (0x8007139F)'
```

**Version**
SDK: both latest release (1.0.1661.34) or pre-release version (1.0.1777-prerelease)
Runtime: 112.0.1722.39
Framework: WPF, WinForms
OS: Win10, Win11

**Repro Steps**
Just use different language setting for CoreWebView2EnvironmentOptions will cause this issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/6803102/231748854-77622cac-d5ca-4812-8bd1-a3c157c5900b.png)

**Additional context**

Sample project: https://1drv.ms/u/s!AgvJSayGHEKGi-QsGt9p3xe5hp3xag?e=s7JSyq

**Comment by lflores-ms** [comment]
Hi @ye4241,

To use different languages for your webview instances, you can specify the user data folder for each environment by setting `userDataFolder` in the call to [CoreWebView2Environment.CreateAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1722.32#microsoft-web-webview2-core-corewebview2environment-createasync(system-string-system-string-microsoft-web-webview2-core-corewebview2environmentoptions)).

**Why it fails**
The WebView2 Runtime has a single language per instance, set at startup time from the environment configuration used to create the first webview. There is a single WebView2 Runtime instance per user data folder.

Since both of your windows are creating their environment under the same (default) user data folder, the first to create the webview will define the effective language. Any further attempt to create a webview with an incompatible environment will fail with this error, since the WebView2 runtime instance for the user data folder is already running with a different configuration.

**Comment by ye4241** [comment]
@lflores-ms So if there is any possible to change the language in user profile without recreate instance?

**Comment by lflores-ms** [comment]
The language of the WebView2 Runtime can't be changed once the processes have started.

* If you're trying to **create a WebView using the same _User Data Folder_, but a different language**, you'll have to close all WebView objects and wait for [BrowserProcessExited](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.browserprocessexited?view=webview2-dotnet-1.0.1722.45) before creating the new instance.

* If you want **multiple WebViews at the same time, each with a different language**, they will have to be bound to different processes: create an environment object for each language you want, and use a unique _User Data Folder_ for each of those environments. Please note that this will create an entire set of processes for each distinct _User Data Folder_ you use. See [Process model for WebView2 apps](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model?tabs=csharp) and [Avoid running too many folders at once](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32#avoid-running-too-many-folders-at-once) for reference.

---

> sometime use additional browser arguments with same use data folder will cause same exception.

Yes, this is due to the same reason. Many browser switches are effective throughout the whole lifetime of the WebView2 processes set. If you try to create new WebViews with incompatible environment configuration for the same _User Data Folder_, creation will fail. If your app(s) are using the same _User Data Folder_, they must coordinate their environment configuration so it remains compatible. See [Sharing user data folders](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32#sharing-user-data-folders) and [Globals](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1722.45#:~:text=WebView%20creation%20fails%20with%20HRESULT_FROM_WIN32(ERROR_INVALID_STATE)) for reference.

**Comment by ye4241** [comment]
Thanks for your clarification, I will try to use different folders for different processes.
