### ISSUE TITLE
Convert JavaScript strings to C# strings

### ISSUE THREAD

**Issue by RaphMar2021** [MicrosoftEdge/WebView2Feedback#3396]
When `WebView2.ExecuteScriptAsync()` is runned and the JavaScript function returns a string, the method returns a string but it's not right.

Exemple of Monaco Editor's `editor.getValue()` function :
![image](https://user-images.githubusercontent.com/81994075/232345566-b55b0412-fa84-48f8-8145-748bea352013.png)

What format i would like to get :
![image](https://user-images.githubusercontent.com/81994075/232345610-ce0dd203-77e3-4714-8649-e879b80710a8.png)

Also, i'm using C# with WinUI 3 with WebView 111 on Windows 11

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this?

	• Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
	• SDK and Runtime version.
	• Operating System
This will help with figuring out how to best address your issue. Thanks!

**Comment by RaphMar2021** [comment]
Done

**Comment by david-risney** [comment]
I would guess that you have potentially escaped your newline characters incorrectly (it would be good in the future if you can include a snippet of your failing code)

![image](https://user-images.githubusercontent.com/2541336/232567805-ff461982-4d10-431a-aa2e-a8713db2f5ec.png)

In C# you need to make sure you escape your \r\n so that they are newline control characters in the string in JS and not a newline in the C# string nor escaped to be literal \r\n in the string in JS

```
            string snippet = "alert(\"hello\\r\\nnewline\")";
            //string snippet = @"alert(""hello\r\nnewline"")"; // this also works
            string scriptResult = await WebView2.CoreWebView2.ExecuteScriptAsync(snippet);
```

**Comment by david-risney** [comment]
I'm not sure what the issue is then. It would be helpful if you could include some snippets of your C# and JS code and the string value you are getting and the string value you wanted to get.

**Comment by RaphMar2021** [comment]
I will try making a parser
