### ISSUE TITLE
WebView2 in Hololens

### ISSUE THREAD

**Issue by hzhong16** [MicrosoftEdge/WebView2Feedback#3410]
### Discussed in https://github.com/MicrosoftEdge/WebView2Feedback/discussions/3401

<div type='discussions-op-text'>

<sup>Originally posted by **hzhong16** April 17, 2023</sup>
I notice that WebView2 is push out in Hololens 2 on insider preview. I Had update my Hololens 2 to the newest Dev Version but I am not sure where to begin with implement it in to Hololens, there is not much documentation on it. 

Can anyone give me a direction where should i start? I am currently developing my Hololens application inside the unity.

Thank you</div>

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by hzhong16** [comment]
Is the documentation for the hololens out yet? Need it to do with unity

**Comment by nishitha-burman** [comment]
Hello,

WebView2 Preview is available in the Insider Preview for Microsoft HoloLens. Here is documentation to get started: 
https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2. 

Thanks!

**Comment by GLARKI** [comment]
It's great only for some reason I cant find the WebView2 prefab only the WebView prefab. I think it has something to do with the available version in the mixedrealityfeaturetoolkit.exe, it has 0.17.0 instead of 0.19.0 used in the tutorial. 

Could this be the reason that I cannot scroll on the webpage or click anything on the webpage, everything else works fine.
