### ISSUE TITLE
Context menu options not working properly (Web capture not working)

### ISSUE THREAD

**Issue by nirbil** [MicrosoftEdge/WebView2Feedback#3426]
Certain context menu options are malfunctioning:

1. 'Copy image' isn't working
2. 'Web-capture' features are not working properly. Right click on an image and select web-capture, mark an area and you get three menu options, none work as they should. 'Copy' doesn't copy, 'Visual search' doesn't search, and 'Mark up capture' results can't be copied, or properly saved
3. 'Copy link to highlight' (selected text context menu) frequently results in core process failure
4. 'Save As' (page context menu) is invoking a none standard download behavior where OnDownloadStarting is not invoked, and the resulting file is inaccessible. Other save options that I checked (link and image context menus) seem to be functioning correctly
5. 'Emoji' isn't working (input text box context menu)
6. In case of custom context menu handling, 'Spell check' isn't working, the label for each returned suggestion is empty and invoking the command (by setting SelectedCommandId) isn't changing the text
7. 'Show all saved passwords' isn't working (password input context menu) 
8. Setting 'Writing direction' to Default results in core process failure

SDK: 1.0.1777-prerelease
Runtime: Edge Dev Channel 114.0.1807.6
Framework: UWP
OS: Win10

[AB#45058240](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45058240)

**Comment by novac42** [comment]
Could you please provide some more information about this?

- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version 
- Operating System

**Comment by nirbil** [comment]
Running on Win10 UWP, latest edge dev channel

**Comment by ajtruckle** [comment]
I also agree on Win32 MFC:

WebView2 Runtime Version: 112.0.1722.58
WebView2 SDK Build: 1722.45

If I try to use the Visual Search with an image nothing appears to happen. But if I view same page in Edge and do same Web Capture / Visual Search I get results. But, the results are in a side pane which would not be visible in my embedded browser control. I don't have a direct use for it but maybe it should be showing the results in a popup window.

Can't comment on the others as I have not tried them and I am only using Win32 app anyway.

**Comment by nirbil** [comment]
Any comment on this? The entire context menu mechanism seems to be plugged with bugs...

**Comment by nirbil** [comment]
@novac42 @yildirimcagri please update if this is at all being looked at?

**Comment by yildirimcagri** [comment]
Hi @nirbil, thanks for your detailed feedback about the context menu in UWP WebView2. It seems there are multiple issues at play here:
1) I can repro the "Copy image" issue in UWP in 114. This seems to be tracked with #2278 as clipboard functionality is not implemented in UWP yet. @champnic may have more information on the status of clipboard in UWP.
2) I can repro the issue for "Web capture" also in Win32. We can use this issue to track this feedback (both Win32 and UWP). The other items listed such as "Visual search" are Edge specific features, and they should not show up in the WebView2 context menu. I believe the issue that affects the issue 1 also is at play here for UWP.
3) I wasn't able to repro this one, but if you could share a dump, I'd be happy to take a look.
4) This could be due to an app container issue. Are you attempting to save the page to a directory accessible to the app? I can see that the behavior you are describing unless I attempt to save to the app local directory, in which case the save works.
5) I'm able to repro this in UWP only. Will follow up with the hosting team on this.
6) This is tracked with #2340 . I believe this is being actively worked on.
7) edge://settings page is disabled in WebView2. We'll disable this context menu item, filed a work item for this on our side.
8) For me, the "default" option in "Writing direction" is always grayed out, could you give some steps on how to enable it?

Hope this helps!

**Comment by nirbil** [comment]
Hey @yildirimcagri, thanks for the detailed response, here are some clarifications:

Re 1 - Not sure if it's covered under that bug. Is copying an image to the clipboard and pasting an image from the clipboard to the WebView handled under the same scope? @champnic can you clarify whether I should open a dedicated bug?
Re 2 - I'm not sure I understand, should the entire 'Web-Capture' functionality just be disabled as it's edge specific?
Re 3 - Can't reproduce it either. I think I may have mixed it up with a different already documented bug by accidentally triggering drag and drop on the highlighted text which occasionally leads to a crash
Re 4 - Correction, the page is saved fine, but the download implementation is none standard. I have my own download UI as UWP's download UI is very buggy, but only in this case the OnDownloadStarting is just never invoked, and the default UI is visible instead.
Re 8 - Well I have a custom context menu and I've been showing and invoking that submenu command while ignoring if it's IsEnabled is set to false, which in this case lead to a core process failure. So I guess that was my mistake and isn't really a bug, but maybe the option shouldn't be there in the first place if it's none functional...

**Comment by vickiez** [comment]
Hi @nirbil, 

2 - For now we are planning on removing visual search from the menu. The other options appear to be working now, at least in Win32. For UWP, it's likely they are affected by the clipboard issue Cagri mentioned
4 - Can you open another issue regarding this? We'll create a separate bug for it and provide updates on the new issue 
8 - The "Writing direction" option is functioning normally in Win32, are you seeing something different when it is enabled in UWP?

**Comment by champnic** [comment]
@nirbil 
1- It's very likely the same underlying issue relating to using images with the clipboard APIs in UWP. I don't think we need a separate issue, but it might be good to add a note to #2278.

**Comment by champnic** [comment]
@nirbil We are using #2900 to track both copying and pasting images in UWP. Please refer to that thread for more info and updates. Thanks!

**Comment by nirbil** [comment]
Hi @vickiez,
2 - There's just one other thing, if you choose to save the capture (after capturing full page, or after capturing an area and then selecting 'mark up capture') it invokes the same none standard download behavior, so I'm adding it to the download issue
4 - Here - #3600 
8 - The writing direction is fine, just the option to reset to default seems to be always disabled, and if you trigger it by mistake programmatically then it crashes the app, but whatever.

**Comment by vickiez** [comment]
2 & 4 - Thanks! Created an internal work item for the new issue
8 - Got it, thanks for clarifying. We can't change much here besides throwing a more specific exception, but that would also crash the app. For now we'll update our docs to advise developers to check whether an item is enabled before invoking it, otherwise it can result in the process failure

**Comment by champnic** [comment]
Main issue should be fixed in runtimes 117.0.1945.0+. Thanks!
