### ISSUE TITLE
Problem with Intel Vtune Profiler

### ISSUE THREAD

**Issue by btlopener** [MicrosoftEdge/WebView2Feedback#3469]
**Description**
I've crashes in  my application that is using WebView2 when profiling with VTune Intel Profiler.
(I was able to replicate with WebView2Samples). When I was searching for a solution I found this switch "--enable-vtune-support"(https://peter.sh/experiments/chromium-command-line-switches/#enable-vtune-support), try to specified it when creating the WebView but with no success, maybe I did something wrong. If this switch is supposed to work? If so, can you provided me with an example?  
 
**Version**
Runtime: 112.0.1722.68
Framework: Win32
OS:  Win10/Win11

**Repro Steps**
1. Have Intel VTune Profiler
2. Try to profile (HotSpot+User-Mode Sampling) the application https://learn.microsoft.com/en-us/microsoft-edge/webview2/samples/webview2apissample or any (?) app using WebView2 ( Outlook also have issues)
3. Observe crashes and strange behaviors .

I'm only looking to make profiling works for development purposes.

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev who can help follow up on this.

**Comment by LiangTheDev** [comment]
This is due to VTune Profiler injecting dlls into processes and WebView2 renderer process has code integrity requirement of dlls running in them.

There seems to be 2 ways to make it work by changing configuration:
 - Uncheck "children" for in Analyze column of "Per-process Configuration", so that we profile only the app process itself. As you could not change WebView2 Runtime code, focusing on app process might be what you want.
 - Set "User-defined environment variables": WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS with value of --disable-features=RendererCodeIntegrity. So that we don't enforce code integrity rules while doing profiling.

**Comment by btlopener** [comment]
Hi, thank you for your fast answer.
The first solution, **_Uncheck "children"_** is working perfectly and for most profiling uses cases is the way to go.
The second solution **_using RendererCodeIntegrity option_**  seems to change observed behavior, but I still have crashes when profiling. I combine this option with the **_--no-sandbox_** option and the crashes seem to go away. I don't know if it makes sense. Is that the case? I still need to do some more testing but it looks pretty good.
Thanks!

I call CreateCoreWebView2EnvironmentWithOptions with the following options:
`    std::wstring args;
    args.append( L" --no-sandbox" ); //Only for profiling with VTune with children
    args.append( L" --disable-features=msSmartScreenProtection" );
    args.append( L", RendererCodeIntegrity" );  ///Only for profiling with VTune with children

    auto options = Microsoft::WRL::Make< CoreWebView2EnvironmentOptions >();
    options->put_AdditionalBrowserArguments( args.c_str() );
 `

**Comment by LiangTheDev** [comment]
Glad that you have found solutions. For me, disabling RendererCodeIntegrity alone is enough to get it working. --no-sandbox would also avoid RendererCodeIntegrity issue as we don't even create sandboxed renderer process. But if we have to use --no-sandbox to get it work, it is OK to do that for profiling.

In the code above, RendererCodeIntegrity is not really disabled though. There is a space before it and that space would make it a separate command line switch instead of one of the disabled features. Try remove that space and make it `args.append( L",RendererCodeIntegrity" )` and see whether it works without --no-sandbox.

Also, if we only need something when profiling, using environment variable to config VTune might be better as that is a natural way to limit the command line switch to profiling. The command line switch defined in environment variable will be auto merged with the one specified in code.

**Comment by btlopener** [comment]
Hi!
I confirm that RendererCodeIntegrity option is not enough to make it works. But the --no-sandbox fix my problem from code or from environment variable.  Like you said I will use the environment variable.
