### ISSUE TITLE
Browser policies for WebView2

### ISSUE THREAD

**Issue by ztanczos** [MicrosoftEdge/WebView2Feedback#3528]
Hi,

Does WebView2 respect the browser policy settings set for Edge, under Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge?

Is this the full list of policies supported by WebView2: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-webview-policies ?

I'm specifically interested in learning whether the https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#legacysamesitecookiebehaviorenabled or https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#legacysamesitecookiebehaviorenabledfordomainlist policies can somehow be set for WebView2.

Thanks,
  Zoltan

**Comment by novac42** [comment]
Hi @ztanczos Policies set for Edge doesn't apply to WebView2. For WebView2 policy you would need change the path to SOFTWARE\Policies\Microsoft\Edge\WebView2\ instead of Edge. However the policies officially supported are limited to what's listed in https://learn.microsoft.com/en-us/deployedge/microsoft-edge-webview-policies as you mentioned. 
We have a few more listed in our backlog but not the ones you are interested in. Would you like to explain why you need these two policies? It would help us better understand your use cases.

**Comment by ztanczos** [comment]
Hi @novac42,
Browser policies are managed centrally within our organization. It would help in troubleshooting/explaining issues if WebView2 would follow / or would have the same set of policies, i.e.: "why application X behaves differently in the browser vs. in WebView2?"

**Comment by darbid** [comment]
Thumbs down. Leave the webview2 out of the hands of group policy.

**Comment by novac42** [comment]
Hi @ztanczos may you help clarify do you need to handle some legacy web apps using HTTP in certain WebView2 apps, or all of them? Would adding APIs for WebView2 apps to enable legacy samesite cookie behavior work?
[legacysamesitecookiebehaviorenabledfordomainlist](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#legacysamesitecookiebehaviorenabledfordomainlist) can have security implications so we'd like to be cautious when evaluating the necessity of adding such policy.

**Comment by ztanczos** [comment]
Hi @novac42,

Sorry for the delayed response. Yes, this question came up while troubleshooting internal, legacy web applications, but that specific issue isn't important anymore. 
I assume the discussion around policies in general would be far-reaching and can have enormous consequences, so your answer - Edge policies don't apply to WebView2 - is good enough for us.

Thanks,
  Zoltan
