### ISSUE TITLE
WebView crashes at in printer menu

### ISSUE THREAD

**Issue by jonasLH4** [MicrosoftEdge/WebView2Feedback#3575]
Hello, we recently replaced our old printers in my company, the printer driver isn't uninstalled. This causes an issue where Applications that use Web View like outlook and edge are crashing.

OS: Win 11
Webview Version: 114.01823.79

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this?

- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version 
- Operating System

**Comment by jonasLH4** [comment]
@novac42 

OS: Win 11
Webview Version: 114.01823.79

**Comment by monica-ch** [comment]
@jonasLH4 Sorry you are seeing an issue with printer's dropdown.  I see from description that you are also seeing the issue in edge browser. If the issue exists in both Edge and WebView2, please send feedback to Edge.

**Comment by jonasLH4** [comment]
> @jonasLH4 Sorry you are seeing an issue with printer's dropdown. I see from description that you are also seeing the issue in edge browser. If the issue exists in both Edge and WebView2, please send feedback to Edge.

Yeah it exists both in outlook and edge Browser. It first appeared in Edge and than on some workplaces in Applications that using WebView like Outlook too.

**Comment by novac42** [comment]
@jonasLH4 Since this issue exists in Edge it may require upstream Edge code update. As Monica suggested, may you send a feedback to Edge to report this problem? I will close this issue as it's in Edge scope. 
<img width="512" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/6320831/2f93aff9-816e-427a-9df2-43d2ebe0b90a">
