### ISSUE TITLE
Windows GUI freeze

### ISSUE THREAD

**Issue by neech** [MicrosoftEdge/WebView2Feedback#3581]
**Description**
I made a software that stay in the windows tray. It will act as a daemon and will create the view when the user click on the icon.
When a user clicks on the icon it will open the software in an always on top mode. The software will show a message in a webview2 page.
The issue occurs randomly, or I can force it when I use the remote desktop app to access the computer where the software is running.
The windows UI will freeze while the software is in the foreground.

How I know it’s caused by webview2? when I remove the code portion initializing WebView2 or remove WebView2 in the xaml or if I close all the msedgeview2.exe with the task manager I don’t encounter this bug anymore.

**Version**
SDK: 1.0.1823.32
Runtime: 114.0.1823.51
Framework: WPF
OS: Win10

**Comment by neech** [comment]
here is a mini project to reproduce the bug.

**Stages allowing reproduction:**

1. Start the project
2. Press the icon in the tray
3. Observe the proper functioning of the software

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/43536929/1e875b3f-15aa-464e-a300-41d683879c8d)

5. Close the sotware with the cross
6. Change screen scaling

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/43536929/3e8d8278-592b-431b-a822-7bc2bf617c6d)

7. Restart the software
8. Observe the bug (windows GUI freeze and the app UI preview is transparent)

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/43536929/6ad6be48-83bc-4656-a31d-e16aca829a86)


[EdgeBug.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/11837282/EdgeBug.zip)

**Comment by champnic** [comment]
Hey @neech - Is it frozen or did it just fail to load the WebView2? This looks like a DPI awareness mismatch to me. Are you listening to CoreWebView2InitializationCompleted event, and if so does that indicate that the WebView2 initialization succeeded? Under a debugger you may also get an error message in the debug output that can help indicate what the issue is.

I would suggest trying to set your app to be in PerMonitorV2 mode:
https://github.com/microsoft/WPF-Samples/blob/main/PerMonitorDPI/readme.md

**Comment by neech** [comment]
Hello @champnic I haven't received CoreWebView2InitializationCompleted event errors. 
The PerMonitorV2 mode resolved my issue, thank you very much for your help :)

**Comment by champnic** [comment]
Glad to hear it!
