### ISSUE TITLE
How To Store Pages As Trusted From Content Dialog C# uwp webview2

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#3672]
i made a costum dialog  that ask to proceed or ask to not proceed make i want if i click proceed it adds the website to trusted website certificates but i tryed multible options but they didn't work

Webview2 : Latest Pre-Release
Uwp 

![help](https://github.com/MicrosoftEdge/WebView2Feedback/assets/53493418/415920ba-04a6-4721-ac5c-ddfd11757547)

i want to remove default and when clicking in costum that website certificate gets approved and so that unvalid will not trigger c#

C#

**Comment by novac42** [comment]
@jarno9981 you mean you are using UWP framework? May you also share Operating System version?

**Comment by jarno9981** [comment]
> @jarno9981 you mean you are using UWP framework? May you also share Operating System version?

Yes uwp framework , Windows 11 latest beta

**Comment by jarno9981** [comment]
> > @jarno9981 you mean you are using UWP framework? May you also share Operating System version?
> 
> Yes uwp framework , Windows 11 latest beta 

@novac42

**Comment by novac42** [comment]
@jarno9981 Thanks. Do you have sample app you can share to reproduce the issue?

**Comment by jarno9981** [comment]
> @jarno9981 Thanks. Do you have sample app you can share to reproduce the issue?

Yes buts really big i can send it after i am home from work

**Comment by jarno9981** [comment]
project is 450mb total it can throw .pri error can be ignored after building second time it dissepears

drive link here : https://drive.google.com/file/d/1MWDc8Esf4XP68AJiTAfIB5bX-nXtBAn7/view?usp=sharing

here are webview2 located
WebConten.xaml.cs
WebContent.xaml

Code Line = 252 t/m 278

Control located in = Core Folder

@novac42 

My expected behaiver is when clicking proceed that you can store the site a trusted

Windows 11 Pro, 22631.1972
Edge Runtime 115.0.1901.188
Microsoft.Ui.Xaml = 2.8.5

**Comment by jarno9981** [comment]
navigate any localpage than this will appear

**Comment by monica-ch** [comment]
@jarno9981 There is a [ServerCertificateErrorDetected](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.servercertificateerrordetected?view=webview2-dotnet-1.0.1901.177) event you can use to intercept the error page, show the custom dialog and respond to continue/cancel the request.

**Comment by monica-ch** [comment]
@jarno9981 Can you check if it repros after deleting the WV2 user data folder? Also, I'm not able to access the project you shared in the google drive.

**Comment by jarno9981** [comment]
> @jarno9981 Can you check if it repros after deleting the WV2 user data folder? Also, I'm not able to access the project you shared in the google drive to test it locally

I will test after deleting it and fixing google drive

**Comment by monica-ch** [comment]
@jarno9981 I see server certificate event gets fired upon subscribing to [ServerCertificateErrorDetected](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.servercertificateerrordetected?view=webview2-dotnet-1.0.1901.177) in your app. Also, you must have to move your logic of showing the dialog in the server certificate event callback (not in the navigation completed) and get the deferral object and show the dialog in order to respond to the request.

Example of using deferral in UWP apps https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/webview2_sample_uwp/Pages/Browser.xaml.cs#L71

Example of responding to server certificate error detected event.
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.servercertificateerrordetected?view=webview2-dotnet-1.0.1901.177
