### ISSUE TITLE
Memory leak while running webview2 in WindowsFrom app with runtime version 109

### ISSUE THREAD

**Issue by ironsoccer21** [MicrosoftEdge/WebView2Feedback#3678]
**Description**
Reloading a WebPage in Webview2 control causes memory leak.

**Version**
WebView2 Runtime version 109.0.1518.49
Build Env : Windows 10 / Visual Studio 2022
Deploy Env : Windows Embedded Standard 7

**AppDetails**
We built WindowsFromBased App powered by WebView2(Version 109) in Windows10.
The App runs in Windows Embedded Standard 7, and open simple html.
The App keep reloading browser every 30sec by .Reload() function while viewing webpage.

**MemLeakDetails**
We continuously used the application and measured the memory usage for 7 days.

- For each "msedgewebview2" instance, the memory usage keeps increasing.

As a result, the application crashed, and all operations became completely unresponsive on Windows 7.

**Question**
Is there a way to resolve the above memory leak issue?

**Comment by LiangTheDev** [comment]
What happened when we reload a page: since it is the same site, we will reuse the same renderer process. And as we are loading a new page, we will create a set of new objects for the new page while the old objects are still alive, waiting for garbage collection to clean them up. GC will happen at its own pace. If we reload or navigate in the same site faster than GC, then we will keep using more memory. If there are leaks in the page or Edge implementation, those leaks will be there until the process is terminated when we navigate away to a different site or close the WebView.

So, things you could try:
- Call ExecuteScript for window.gc() to trigger GC frequently.
- Navigate to another “site”, like NavigateToString(“”), and then navigate to the real site again. Note that navigate to about:blank does not count. It will reuse the same renderer process. Navigate to another site will force the platform to use a different renderer process. To avoid showing blank during transition, we might have to use 2 WebViews: navigate webview_2 to the site and switch it to be visible to the user, and then navigate webview_1 to the blank page; navigate webview_1 to site and switch it to be visible to user and navigate webview_2 to blank page, and repeat.
- Create a new WebView, navigate to the site and switch it to be shown and close the old one. This is similar to option above, but we don’t keep the spare around.

**Comment by ironsoccer21** [comment]
Thankyou for your reply.

We'll try using window.gc().
But we have additional questions.

- Does the memory released by running Windows.gc() only apply to objects under the corresponding window object in JavaScript? For example, is the GC executed for other JavaScript objects as well?

- Is it possible to define a common GC execution timing for the application? For example, a way to execute GC for all objects once every hour.

**Comment by ironsoccer21** [comment]
Thank you for your suggestion.

We'll try and test how GC works.

**Comment by ironsoccer21** [comment]
Thank you for your previous response.

Question:
Are there any other ways to resolve memory leaks besides the three measures you provided?

Here are the measures you provided:
Measure 1:
I executed garbage collection at a shorter interval than the web content reload cycle. Comparing the cases with and without garbage collection, I could confirm that memory was actually released in the short term (1-2 hours) by garbage collection. However, when checking the long-term (several days) running results, memory leaks occurred in both cases. Running GC did not resolve the memory leak issue.

Measure 2:
We are displaying web content with limited resources, and having more than two WebViews constantly running for one web content display would reach the resource limit.

Measure 3:
As you pointed out, a blank screen is displayed every time the web content is reloaded, which does not meet our requirements for the product we want to create.

**Comment by LiangTheDev** [comment]
Have you analyzed the page to see whether there is really a memory leak caused by JS code on the page? If we load the same page in Edge or Chrome browser, and keep reloading it, do you also observe memory usage increase?

Detached elements are a usual cause of leaks. See https://blogs.windows.com/msedgedev/2021/12/09/debug-memory-leaks-detached-elements-tool-devtools/ and https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks for more details on how to do that.

If we could not find the root cause of the leak, you might use some combination of the options, like doing GC, and every 1 hour create a new WebView and switch to use that and close the old one.

**Comment by Teletrak** [comment]
H

**Comment by Teletrak** [comment]
I have been experiencing similar problems to ironsoccer21 with a WebView2 implementation that scrapes pages from the same web site. In one run the renderer process memory reached 7GB before the ProcessFailed event reported OutOfMemory.  The ExecuteScript("window.gc()") suggestion works well as a solution in this scenario as the scraper does not re-visit pages, and therefore running GC before navigating to a new page (or every _n_ pages) is perfectly feasible. What I wanted to know though, is whether the call to "window.gc()" is only available in DEBUG builds of WebView2.

**Comment by LiangTheDev** [comment]
window.gc() is available on release builds of WebView2.

**Comment by ironsoccer21** [comment]
Thank you for your reply, LiangTheDev.

In my application, I am not viewing the web content in Edge or Chrome browsers. I am using the WebView2 control within the application to display the web content.

Regarding the HTML file that was displayed in the test where the leak was confirmed, I investigated the detached elements using the method you suggested, but I could not find any detached elements in the relevant HTML file. Therefore, I assume it might be an issue with the WebView2 engine.

For now, I will consider addressing the issue by either performing GC or periodically creating a new WebView, using it, and closing the old one.

Thank you for your assistance.

I apologize for the delayed response, as I was conducting a running test.

**Comment by talldaniel** [comment]
I have the same problem with a 150K lines Blazor App starting around April 2025. 

I updated VS community then and. a fast moving memory leak  repeatedly took out my app, so I eventually updated to VS Enterprise as a temp solution, hoping the bug would be fixed before the trial expired.  
Now, the trial version has expired, so I  just repair Visual Studio every few  days when it starts does it.   I can tell now it is going to happen before it does, because VS gets sluggish.


And inside vs it does warn me, "You must update Webview2."  All attempts to "update' webview2 fail.
Before I figured out to repair it, and after VS enterprise expired, my box would crash once or twice a day, and sometimes more often until I found that repair "fixes" it. (with loss of work usually) 

Chat says repair works because the repair clears all the caches down deep. Who knows.
