### ISSUE TITLE
Want a simple HTML viewer as WebView successor

### ISSUE THREAD

**Issue by PaulTaro** [MicrosoftEdge/WebView2Feedback#3742]
I want a simple HTML viewer in WinUI that always works. I need the viewer for displaying important user information and for online help. I don't want to include a WebView2 runtime in my app and I don't want a bootstrapper.  It's all too complicated for me. After WebView2 initially worked in my app, now nothing works. CoreWebView2 is always null. I tried everything possible without success.

**Comment by victorhuangwq** [comment]
Hi Paul, with regards to the WebView2 runtime, it is required for WebView to work. If you want to do without a bootstrapper, it comes out of the box in Windows 11, and you can also just prompt the user to download in the event that they don't have it (in earlier versions of Windows).

> After WebView2 initially worked in my app, now nothing works. CoreWebView2 is always null. I tried everything possible without success.

Could you provide more context on this, including:
- what's the app you are working on
- which sdk are you using
- what is the error messages that results in "CoreWebView2" being null
- and what have your tried thus far?

**Comment by PaulTaro** [comment]
Hi Victor,

many sincere thanks for the response to my request, which resulted from sheer desperation about my current development situation. You will find the details in this Word document<https://1drv.ms/w/s!Aj8fYVKyG_xrlIc71POHMYODISTZCw?e=sJZoaf>.

Best Regards,
Paul

Von: Victor Huang ***@***.***>
Gesendet: Mittwoch, 30. August 2023 01:21
An: MicrosoftEdge/WebView2Feedback ***@***.***>
Cc: PaulTaro ***@***.***>; Author ***@***.***>
Betreff: Re: [MicrosoftEdge/WebView2Feedback] Want a simple HTML viewer as WebView successor (Issue #3742)


Hi Paul, with regards to the WebView2 runtime, it is required for WebView to work. If you want to do without a bootstrapper, it comes out of the box in Windows 11, and you can also just prompt the user to download in the event that they don't have it (in earlier versions of Windows).

After WebView2 initially worked in my app, now nothing works. CoreWebView2 is always null. I tried everything possible without success.

Could you provide more context on this, including:

  *   what's the app you are working on
  *   which sdk are you using
  *   what is the error messages that results in "CoreWebView2" being null
  *   and what have your tried thus far?

-

**Comment by victorhuangwq** [comment]
I am copying out what Paul sent in his document into a post here for easier reference in the future.

-------
I have 2 card game apps for Windows and Android called KubiTarock and KubiSolitaire. Versions for iOS are in the works.

After the previous licenses for them didn't work out, I introduced an offline and an online version. The offline version is completely free and without cloud access. The online version allows synchronization of scores across multiple devices and platforms (uses Azure DB). KubiTarock also allows interaction with other users in the online version (uses SignalR).

For my existing customers, I have included an information page in the apps where they are introduced to the new licenses and where they can also switch to a version right away. This is an HTML page which in a string. It is therefore imperative that this page is reliably displayed to existing customers.

In addition, users of my apps will see release news, online tutorials and extensive online help as web pages from my domain. Example: https://www.kubiconsult.com/Tarock-Koenigrufen.

The new versions of my apps are ready and already released for Android.

Unfortunately, I can't release the version for Windows for the following reasons:

- The UWP versions can't be produced due to compiler errors when generating native code.

- The WinUI versions can't be released because WebView2 can't display the important user info.

So much for my situation and now for WebView2:

The following Edge components are installed:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/a30c1029-0e4a-4e80-87f5-89d56ba81c51)

While collecting the error information, I now got the surprise that in KubiTarock WebView2 works again and in the other app it does not. The configuration in which WebView2 works uses the Microsoft.Graph and Microsoft.Identity.Client packages in the "GameLibrary" project. They are used to access OneDrive. However, I will not use OneDrive access in the future and remove the two packages. You can see the configuration in the following screenshot:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/886f6b9c-e55c-486f-b826-17b2edd6a4a0)

The configuration in which it does not work (next screenshot) does not use Microsoft.Graph or Microsoft.Identity.Client, nor Microsoft.Web.WebView2. I assume the latter is included in Microsoft.Windows.AppSDK or not?
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/151e23f6-31a6-44e2-91d8-14b154bfb20a)

This causes the error shown in the following screenshot:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/353e8f16-137a-4d08-8e4e-23b4da6df52a)

I have also tried several other configurations, almost always with negative results. I am very confused because I do not know in which packages WebView2 is included and what I can do to make sure at the customer that WebView2 works.

**Comment by LiangTheDev** [comment]
The error code suggests that it is similar issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/447. More details on https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model.

**Comment by PaulTaro** [comment]
A group view with a web viewer inside can be made visible from another thread than the UI thread:
on Windows with Windows.UI.Xaml.Controls.WebView
on Android with  Android.WebKit.WebView
on iOS with UIKit.UIWebView

Only WebView2 does not allow this.

**Comment by PaulTaro** [comment]
I get the same exception when EnsureCoreWebView2Async() runs on the main thread:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/49974414/c4ad302f-f958-4f3b-8944-206ced325eca)

**Comment by PaulTaro** [comment]
Issue closed by mistake.

**Comment by PaulTaro** [comment]
In the meantime my developer situation has eased. After I removed some functions and libraries (Microsoft.Identity.Client, Microsoft.Graph) from my apps that are no longer absolutely necessary and was able to define a suitable "Default.rd.xml" for the rest, my apps can be produced as UWP with native code generation again.
I will therefore defer WinUI versions until WinUI/Net8 meets or exceeds all UWP properties in terms of functionality and performance.
