### ISSUE TITLE
Any reason to update the SDK to 1.0.1938.49?

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftEdge/WebView2Feedback#3747]
I feel silly asking, the release notes only make reference to issues fixed in the runtime, is there much of a reason to update the SDK and deploy a new build of my app if nothing else is being changed?

Generally I do update and deploy, but only if I need a new API or some new feature.

**Comment by victorhuangwq** [comment]
Hey @Danielx64 no worries, that's not a silly question at all. Yes, technically there isn't much need to update for SDK 1.0.1938.49 (to be paired with 116 runtime) because there's no new API promotions. We still release the SDK and the corresponding release notes to let people know about the fixes in the runtime.

**Comment by Danielx64** [comment]
Thank you for confirming what I thought, I think I'll save my effort in updating, testing and pushing out a new build of my app this month.
