### ISSUE TITLE
Dark Mode Language Selection Dropdown UI Bug

### ISSUE THREAD

**Issue by bilalmirza74** [MicrosoftEdge/WebView2Feedback#3791]
UI of the search page on Edge Browser in Dark Mood/Theam
The language Selection Dropdown is not visible Properly
,

![268660089-a2a5cd94-a8f7-4dd1-9765-81f8ca693565](https://github.com/MicrosoftEdge/WebView2Feedback/assets/84387676/40ca5c4f-cc1d-492a-9d65-7b127b60c6aa)

**Comment by victorhuangwq** [comment]
May I ask if this issue is directed at the Microsoft Edge browser, or Microsoft WebView2?

If it's directed at the Edge Browser, click on the three dots, click help and feedback, and then send feedback to file an issue with the Edge Browser team
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/570a7b5f-adb2-4ec2-afb7-df0e33db881f)
