### ISSUE TITLE
Migrating CEF3 application- message loop call?

### ISSUE THREAD

**Issue by reynoldslabware** [MicrosoftEdge/WebView2Feedback#3800]
We are researching migrating a Win32 application using Chromium Embedded Framework version 3 (CEF3) to webview2.
In the CEF3 world there is a function to dispatch some Windows messages. See below for a brief explanation.
What is the equivalent in the WebView2 world?
Thank you.

CefDoMessageLoopWork(), this is meant to be called from an application's own message loop. 

This is from the comment to cef_do_message_loop_work() which is what CefDoMessageLoopWork() calls and gives more information:
// Perform a single iteration of CEF message loop processing. This function is
// used to integrate the CEF message loop into an existing application message
// loop. Care must be taken to balance performance against excessive CPU usage.
// This function should only be called on the main application thread and only
// if cef_initialize() is called with a CefSettings.multi_threaded_message_loop
// value of false (0). This function will not block.

**Comment by ElyssaJyu** [comment]
Hi @reynoldslabware,

In CEF3, as you mentioned, CefDoMessageLoopWork() is used to integrate the CEF message loop into an existing application message loop, especially when using a single-threaded message loop. For Webview2 control, it must be created on a UI thread that uses a message loop, and run on a STA thread. 
To my knowledge, there's no direct equivalent to `CefDoMessageLoopWork` in WebView2, since WebView2 is designed to work seamlessly with the host application's message loop without needing manual intervention.
Here is a document for [Threading Model for WebView2 apps](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model).

**Comment by reynoldslabware** [comment]
Thank you very much for the feedback. I will review the information at the link provided. 
Separately, any chance you can nudge this critical issue forward after 3 weeks?
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3753
Any help is super greatly muchos appreciated! ;-)

**Comment by johna-ms** [comment]
Hi @reynoldslabware I'm following up here. Could you explain more about your scenario? What work are you doing on CefDoMessageLoopWork that cannot be achieved using WebView2?

**Comment by reynoldslabware** [comment]
With CEF3, our application's Windows dispatch loop needed to include a call to CefDoMessageLoopWork to have the CEF3 related Window messages taken care of.  With WebView2 our custom DLL tracks WebView2 widgets. The thought was that we would have to mimick the CefDoMessageLoopWork functionality with a check to dispatch any messages meant for those widgets in our primary windows dispatch logic.

**Comment by johna-ms** [comment]
As ElyssaJyu pointed out above, as long as the WebView2 is created on a UI thread with a message pump, you shouldn't need to explicitly make the WebView2 window process messages.

**Comment by victorhuangwq** [comment]
Closing issue as addressed. Will reopen if needed
