### ISSUE TITLE
Webview2 affected by WebP 0day?

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftEdge/WebView2Feedback#3825]
Hi there,

Is anyone able to confirm if webview2 is affected by this?

https://www.cyberkendra.com/2023/09/webp-0day-google-assign-new-cve-for.html?m=1

https://nvd.nist.gov/vuln/detail/CVE-2023-5129

Cheers

**Comment by leonidukg** [comment]
Webview2 Runtime is updated automatically with MS Edge

**Comment by Danielx64** [comment]
> Webview2 Runtime is updated automatically with MS Edge

Thank you, so on our side we don't need to do anything to protect our application?

**Comment by leonidukg** [comment]
> > Webview2 Runtime is updated automatically with MS Edge
> 
> Thank you, so on our side we don't need to do anything to protect our application?

That's right. Everything is updated automatically.

**Comment by exaiwitmx** [comment]
@leonidukg Does WebView2 use [WebP Image Extension](https://apps.microsoft.com/store/detail/webp-image-extensions/9PG2DK419DRG?hl=en-us&gl=us)? On my computer, it has version 1.0.62011.0 and was installed on 8/16/2023. WebView2 Runtime, on the other hand, has version 117.0.2045.55 installed on 10/5/2023. So, WebView2 Runtime seems to be up-to-date, and WebP Image Extensions seems to be outdated - I assume that, because [Chromium: CVE-2023-4863 Heap buffer overflow in WebP](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-4863) states that there is a newer version 1.0.62681.0 released on 9/12/2023.
Is WebP Image Extension updated automatically with WebView2 runtime?

**Comment by exaiwitmx** [comment]
It is also not completely clear to me whether or not WebView2 depends on WebP Image Extensions.
I suppose that it is not, because it is based on Chromium which directly depends on libwebp, but I'd rather not guess in this case, because it's security relevant.

I've found [hints](https://www.ctrl.blog/entry/windows-webp-appguard.html) that at least the older EdgeHtml based MS Edge (and therefore probably also the older WebView) depends on WebP Image Extensions.

We should also keep in mind that in additon to CVE-2023-4863, there is also CVE-2023-5217 - a vulnerability in VPx. So, the following might also be affected:
- [VP9 Video Extensions](https://apps.microsoft.com/detail/vp9-video-extensions/9N4D0MSMP0PT)
- [Web Media Extensions](https://www.microsoft.com/store/productId/9N5TDP8VCMHS)

**Comment by exaiwitmx** [comment]
I have another question regarding this topic:
Am I right that it is enough that WebView2 _**Runtime**_ is updated?

Or do we have to update WebView2 _**SDK**_ as well?
As far as I know the latter is not updated automatically.

**Comment by victorhuangwq** [comment]
From my understanding, it would be sufficient that the runtime is updated. @LiangTheDev do correct me if I am wrong however

**Comment by LiangTheDev** [comment]
That is correct. Updating Edge Runtime is enough. And those extensions are for edgehtml based Edge, and not relevant for Chromium based Edge WebView2 Runtime.

**Comment by victorhuangwq** [comment]
Closing issue as addressed
