### ISSUE TITLE
How to detect if runtime is installed?

### ISSUE THREAD

**Issue by Bitfiddler** [MicrosoftEdge/WebView2Feedback#421]
We are currently using clickonce to deploy an app that we hope to transition from Winforms to Blazor by using WebView2 as the 'transitioning technology'.

We tried the Runtime installer and it appears to need admin privileges to install.

This means (until the fixed deployment option is available) we would need to rely on the runtime being installed via gpo (or some other central installer tool).  

My question is: I would like to add some code to the app so that on launch it checks if the runtime is installed and notifies the user that 'some functionality may be unavailable' until the runtime is installed, what is the simplest way to check if the runtime is already installed from a winfroms/c# application?

**Comment by bsobor** [comment]
Have you checked this?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#understand-the-webview2-runtime-and-installer-preview

**Comment by cgeier** [comment]
Please keep in mind the following, which is stated in the document @bsobor posted the link to: "Do not ship WebView2 applications in production during the preview." In addition to [GetAvailableCoreWebView2BrowserVersionString](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/webview2-idl#getavailablecorewebview2browserversionstring), which is discussed in that article, the following may be useful.

To see which version of MS Edge is required for a particular version of WebView2, see the [WebView2 Release Notes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes).

Download the latest development build of MS Edge from [Microsoft Edge Insider Channels](https://www.microsoftedgeinsider.com/en-us/download).


***Note:** "Per User" installations don't require Administrator privileges.  The Canary Channel, defaults to a "PerUser" installation. 

### Per User Installation: 
To install **MS Edge Beta** or **MS Edge Dev** as a "Per User" installation instead of "Per Machine" installation, when you receive the "User Account Control" prompt "Do you want to allow this app to make changes to your device?", click "No".  You'll see a MessageBox that says one of the following:

- For **MS Edge Beta**: "Would you like to install Microsoft Edge Beta without administrator privileges?"
![Per User Installation - Beta](https://user-images.githubusercontent.com/34412039/92330589-032ada00-f03e-11ea-8316-1fa0aec30ebc.JPG)


- For **MS Edge Dev**: "Would you like to install Microsoft Edge Dev without administrator privileges?" 
![Per User Installation - Dev](https://user-images.githubusercontent.com/34412039/92330631-569d2800-f03e-11ea-840f-8b8abf516263.JPG)


Click **Yes** to install as "PerUser". 

**Folders** (PerUser Installation):
- **MS Edge Beta**: %LocalAppData%\Microsoft\Edge Beta\Application\msedge.exe
- **MS Edge Dev**: %LocalAppData%\Microsoft\Edge Dev\Application\msedge.exe
- **MS Edge Canary**: %LocalAppData%\Microsoft\Edge SxS\Application\msedge.exe

**Registry Keys** (PerUser Installation):
- **MS Edge Beta**: HKEY_CURRENT_USER\Software\Microsoft\Edge Beta\BLBeacon
- **MS Edge Dev**: HKEY_CURRENT_USER\Software\Microsoft\Edge Dev\BLBeacon
- **MS Edge Canary**: HKEY_CURRENT_USER\Software\Microsoft\Edge SxS\BLBeacon

### Per Machine Installation:
"Per Machine" installations are installed in the 32-bit "Program Files" folder. 

To install **MS Edge Beta** or **MS Edge Dev** as a "Per Machine" installation, when you receive the "User Account Control" prompt "Do you want to allow this app to make changes to your device?", click "Yes".  

**Registry Keys** (PerMachine Installation):
- **MS Edge Beta**: HKEY_CURRENT_USER\Software\Microsoft\Edge\BLBeacon
- **MS Edge Beta**: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe
- **MS Edge Beta**: HKEY_CURRENT_USER\Software\Microsoft\Edge Beta\BLBeacon
- **MS Edge Beta**: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe
- **MS Edge Dev**: HKEY_CURRENT_USER\Software\Microsoft\Edge Dev\BLBeacon
- **MS Edge Dev**:  HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe

***Note:** The values in HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe will be the highest (Per Machine) version installed. If no Beta or Dev versions are installed, these values will be your (non-development) MS Edge version. If you install a Beta version, the values will refer to the Beta version. If you then also install a Dev version. These values will now point to the Dev version.


**Folders** (PerMachine Installation):

On a **64-bit OS**:  %ProgramFiles(x86)% default installation is C:\Program Files (x86)

- **MS Edge**: %ProgramFiles(x86)%\Microsoft\Edge\Application\msedge.exe
- **MS Edge Beta**: %ProgramFiles(x86)%\Microsoft\Edge Beta\Application\msedge.exe
- **MS Edge Dev**: %ProgramFiles(x86)%\Microsoft\Edge Dev\Application\msedge.exe

 On a **32-bit OS**:  %ProgramFiles% default installation is C:\Program Files
- **MS Edge**: %ProgramFiles%\Microsoft\Edge\Application\msedge.exe
- **MS Edge Beta**: %ProgramFiles%\Microsoft\Edge Beta\Application\msedge.exe
- **MS Edge Dev**: %ProgramFiles%\Microsoft\Edge Dev\Application\msedge.exe

***Note**: Since the MS Edge versions: Beta, Dev, and Canary are development builds, it's possible that their registry keys and/or folder locations could be changed. 

**To find the version of msedge.exe**:

- Double-click **msedge.exe** to open browser window. 
- In the address bar type: `edge://version` and press enter.

**Comment by liminzhu** [comment]
> We tried the Runtime installer and it appears to need admin privileges to install.

Yeah like others stated, the installer is per machine only which implies elevation. We do want to look into per user install down the line.

> My question is: I would like to add some code to the app so that on launch it checks if the runtime is installed and notifies the user that 'some functionality may be unavailable' until the runtime is installed, what is the simplest way to check if the runtime is already installed from a winfroms/c# application?

Checking if regkey pv (REG_SZ) exists under HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5} is probably the easiest. We are working on the sample code.

**Comment by dos-ise** [comment]
I have gone with following implementation. What do you think?

```
    private bool WebViewIsInstalled()
    {
      string regKey = @"SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients";
      using (RegistryKey edgeKey = Registry.LocalMachine.OpenSubKey(regKey))
      {
        if (edgeKey != null)
        {
          string[] productKeys = edgeKey.GetSubKeyNames();
          if (productKeys.Any())
          {
            return true;
          }
        }
      }

      return false;
    }
```

**Comment by bddckr** [comment]
`Microsoft.Web.WebView2.Core.dll` is used by both .NET implementations (WPF + WinForms). Inside that dll there's `CoreWebView2Environment.GetAvailableBrowserVersionString` (a static method). It will handle the C++ call for you _while also handling the case of the runtime not existing_!

It throws a specific exception, so you can just do this:
```c#
open Microsoft.Web.WebView2.Core;

try
{
    var version = CoreWebView2Environment.GetAvailableBrowserVersionString();
    // Do something with `version` if needed.
}
catch (WebView2RuntimeNotFoundException exception)
{
    // Handle the runtime not being installed.
    // `exception.Message` is very nicely specific: It (currently at least) says "Couldn't find a compatible Webview2 Runtime installation to host WebViews."
}
```

**Comment by champnic** [comment]
I've opened a doc bug on our backlog to improve the info for GetAvailableBrowserVersionString on .NET. Thanks!
AB#30786323

**Comment by monkeypro** [comment]
The exception seems to have been removed!
https://github.com/MicrosoftEdge/WebView2Feedback/issues/681

**Comment by champnic** [comment]
The docs have been updated to indicate the exception.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring?view=webview2-dotnet-1.0.774.44#exceptions

**Comment by dotMorten** [comment]
I read [that doc](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#detect-if-a-suitable-webview2-runtime-is-already-installed). This seems like a terrible option. Why isn't there a more obvious method that returns a boolean if available? That would be way more discoverable for the developer. Something like `static bool CoreWebView2.IsSupported { get; }`
