### ISSUE TITLE
[Feature]: Update Proposal: Folder Icons in Microsoft Edge Favorites Bar

### ISSUE THREAD

**Issue by Pedro-Estevao** [MicrosoftEdge/WebView2Feedback#4429]
### Describe the feature/enhancement you need

Currently, the folder icons are not aligned with the browser's new minimalist theme, resulting in a visual discrepancy. The proposal is to replace the folder icons with modified versions of the official Edge icon, tailored to the new visual, ensuring a more cohesive and integrated user experience.

![edge_favorite-bar_now](https://github.com/MicrosoftEdge/WebView2Feedback/assets/61397405/033467d2-9590-4c8b-900f-619f9b899a79)

### The scenario/use case where you would use this feature

The usage scenario involves integrating the new folder icons into the favorites bar, providing a visually consistent experience with the rest of the browser. Users can easily identify their favorite folders and navigate the favorites bar more efficiently while enjoying the updated aesthetic of Microsoft Edge.

### How important is this request to you?

Nice to have. There are other ways to tackle this, but having official API support would be beneficial.

### Suggested implementation

Inspired by the new minimalist aesthetic, I took the liberty of editing an image in Photoshop, replacing the folder icons with a modified version of the Edge icon itself, aligned with the new visual. The result was a more cohesive and integrated appearance, which I believe contributes to a more pleasant and consistent user experience.

![edge_folder-icon](https://github.com/MicrosoftEdge/WebView2Feedback/assets/61397405/cec2d210-8343-4647-a44a-5556c5a9cdf9)

![edge_favorite-bar_sugestion](https://github.com/MicrosoftEdge/WebView2Feedback/assets/61397405/7a6e0e9c-c465-4f69-a990-1197358c69c0)

**Comment by victorhuangwq** [comment]
Hi Pedro, thank you for making this feature request, this is actually the Edge WebView2 repository, not the Edge Browser repository. I will forward this feature request and close this issue in the meantime. I recommend you use the send feedback feature to report it instead as well.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/1b9640e0-5ca3-46e7-9037-4f72ef26d9fe)

**Comment by Gishan86** [comment]
They really implemented those new folder icons and I absolutely hate it...

Before the folders clearly stood out. Now you have a bunch of colored fav icons and some minimalistic, bland folders in between. Not a good look. Wish they would switch back to the old ones.

@victorhuangwq Would be nice if you could forward my feedback to the appropriate team. Thanks & happy holidays

**Comment by cburkitt** [comment]
@Gishan86 You are so right. I came here astonished and very disappointed at how bland the new design has become. The text is actually harder to pick out now because the folder icons are text-like.

I'm intrigued as to how these decisions are made. I suspect a handful of people suggested a change while about a billion others were happy with the existing design. After all, does anyone on the Edge team use Windows File Explorer? Yellow folders, very pleasing and familiar.

At the very least, it would be nice to have an option to customise the folder icons.

I will submit feedback, but have low hopes.

**Comment by stevejmartin-uk** [comment]
What the??!
So some 20 year old comes along with a visual accent he would like to see, and now its somehow law??!
No, I do not believe that a single person could possibly hold sway over a bunch of decisions, but its amazing that a small-ish group have managed to alter the experience for the many.

Did they even bother to evaluate feedback and maybe t-score / z-score or perform valid ANOVA testing against this before they introduced such a ludicrous change?

I rather hope someone can either switch this back, or a 3rd party alter this like many of the Windows 11 3rd party reversion tools out there, but for now though, I'm switching back to Chrome as this is too difficult, hopefully Google haven't made the same design decisions - its been 6+ years since I last used it, yup, this was one change too far.

**Comment by Pedro-Estevao** [comment]
> What the??! So some 20 year old comes along with a visual accent he would like to see, and now its somehow law??! No, I do not believe that a single person could possibly hold sway over a bunch of decisions, but its amazing that a small-ish group have managed to alter the experience for the many.
> 
> Did they even bother to evaluate feedback and maybe t-score / z-score or perform valid ANOVA testing against this before they introduced such a ludicrous change?
> 
> I rather hope someone can either switch this back, or a 3rd party alter this like many of the Windows 11 3rd party reversion tools out there, but for now though, I'm switching back to Chrome as this is too difficult, hopefully Google haven't made the same design decisions - its been 6+ years since I last used it, yup, this was one change too far.

Hello, my friend, no decision has been made. This is a suggestions channel. What I sent was a SUGGESTION. It’s obvious that there are processes to validate and MAYBE implement community suggestions. You are free to use whichever application you prefer. Go in peace.

**Comment by hopperelec** [comment]
I don't know why, but to me the new icon makes it look like something has failed to load. I think it looks better than the yellow icon if I look straight at them, but from the corner of my eye (which is how I will usually see them) it just contrasts weirdly with the favicons of pages I've bookmarked.

By the way, I realize this issue is just a proposal (and wasn't even made in the right repo), but it's the top result when Google'ing about this change (hence other people also responding here) so, right now, this seems like the best place to put feedback on the change. If a more official place for feedback on this change is made, both places should link to each other with this issue being archived.

**Comment by stevejmartin-uk** [comment]
> > What the??! So some 20 year old comes along with a visual accent he would like to see, and now its somehow law??! No, I do not believe that a single person could possibly hold sway over a bunch of decisions, but its amazing that a small-ish group have managed to alter the experience for the many.
> > Did they even bother to evaluate feedback and maybe t-score / z-score or perform valid ANOVA testing against this before they introduced such a ludicrous change?
> > I rather hope someone can either switch this back, or a 3rd party alter this like many of the Windows 11 3rd party reversion tools out there, but for now though, I'm switching back to Chrome as this is too difficult, hopefully Google haven't made the same design decisions - its been 6+ years since I last used it, yup, this was one change too far.
> 
> Hello, my friend, no decision has been made. This is a suggestions channel. What I sent was a SUGGESTION. It’s obvious that there are processes to validate and MAYBE implement community suggestions. You are free to use whichever application you prefer. Go in peace.

Fair enough, but you can easily see how this mistake was made, you have created a design earlier in the year and pushed for consideration, and now 8-9 months later, Edge is updated to use a near identical design. I did explain in my previous that it feels that the design team have failed to properly test user views before a global roll-out, which would suggest more attempts by Microsoft to service the needs of the few over those of the many.
