### ISSUE TITLE
RenderProcessExited

### ISSUE THREAD

**Issue by TimWeidner** [MicrosoftEdge/WebView2Feedback#443]
**Description**
The "ProcessFailedKind:" addition is from us, but the RenderProcessExited error is thrown by webview on first load.
In another test Form with just an URL to https://www.microsoft.com/ I get just a blank / empty Form

```
Error Message:
---------------------------

---------------------------
ProcessFailedKind: RenderProcessExited
---------------------------
OK   
---------------------------
```

**Version**
SDK: 0.9.579-prerelease
Runtime: Dev 87.0.637.0
Framework: Winforms
OS: Win10

**Screenshots**
![image](https://user-images.githubusercontent.com/55436069/93307791-b2676e00-f801-11ea-9963-7d2474b20a13.png)

**Comment by champnic** [comment]
Was this working before and broke from an update to Dev?

Can you share the code that's catching and printing that error message? If you remove the error handling, what's the failure stack?

**Comment by TimWeidner** [comment]
It worked on my machine about two and a half weeks ago. Since then the Version of the Browser has changed multiple times as well as the code. I deinstalled all versions of edge and installed the beta version (86.x) and that ain't working either. An update to the most recent version of the webview prerelease changed nothing (which needs 87.x, so i used the dev channel) changed nothing. It even works on the machines of my coworkers and I have no idea what causes this, because if I comment out the error handling and it just fails silently.

```C#
private void WebView_CoreWebView2Ready(object sender, EventArgs e)
{
        webView.CoreWebView2.ProcessFailed += CoreWebView2_ProcessFailed;
}
private void CoreWebView2_ProcessFailed(object sender, CoreWebView2ProcessFailedEventArgs e)
{
        MessageBox.Show(this, "ProcessFailedKind: " + e.ProcessFailedKind);
}
```
![image](https://user-images.githubusercontent.com/55436069/93432805-50bd0780-f8c6-11ea-9856-fba80ca9d694.png)

**Comment by cgeier** [comment]
@TimWeidner Are you compiling as 64-bit (x64 or Any CPU with Prefer 32 bit unchecked) or 32-bit (x86 or Any CPU with Prefer 32 bit checked).

**Comment by TimWeidner** [comment]
Any CPU with Prefer 32 bit unchecked

**Comment by cgeier** [comment]
You can try the what's mentioned in #431, but that may not apply to you. Try this demo: [WebView2Test_v628.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5240107/WebView2Test_v628.zip) . It's just a WebView2 control on a form.

**Comment by TimWeidner** [comment]
Not working at all. Doesn't display the blank page, just the form background.

![image](https://user-images.githubusercontent.com/55436069/93575503-03aa6580-f99a-11ea-88cd-ff18e8673e77.png)

**Comment by TimWeidner** [comment]
Sorry for not responding sooner.

---------------------------
Version Info
---------------------------
MS Edge version: 86.0.622.28 beta
---------------------------
OK   
---------------------------

The Project is using .NET 4.7.2. I am using Windows 10 64-bit.

I have all the specified .dll-Files, but no XML Files in the debug directory.

We have done all the steps you recommended about clearing the packages and (after fixing the nullpointer from the other issue #431) nothing works, just like before doing the steps. So basically the problem still persists

**Comment by TimWeidner** [comment]
My coworker came back from vacation and he has the exact same issue.
So now we have 2 people on the team with this exact error and one who does not have this error at all.
We are not using the same hardware.

**Comment by Flaflo** [comment]
@cgeier @champnic

**Comment by cgeier** [comment]
@TimWeidner 

Please check that your anti-virus isn't blocking/removing the files. If you haven't already done so, please reboot your computer.

Clean the Visual Studio Toolbox (this will remove manually added controls):
- Open Visual Studio
- Open \<project name\>
- **On menu, **View**
- **Solution Explorer**
- Open a Form (such as Form1.cs)
- **On menu, **View**
- **Toolbox**
- Right-click in Toolbox, and select "Reset Toolbox"

Uninstall the Microsoft.Web.WebView2 NuGet package from the project

- Open Visual Studio
- Open \<project name\>
- **On menu, **View**
- **Solution Explorer**
- Right-click \<project name\>
- Select **Manage NuGet Packages...**
- Click **Installed**
- Click **Uninstall**
- Click **OK**

Delete the WebView2 NuGet package files/folders:

- %UserProfile%\.nuget\packages\microsoft.web.webview2\0.9.628-prerelease

Install the Microsoft.Web.WebView2 0.9.628-prerelease NuGet package from the project which will re-download the WebView2 files/folders to `%UserProfile%\.nuget\packages\microsoft.web.webview2\0.9.628-prerelease`

- Open Visual Studio
- Open \<project name\>
- **On menu, **View**
- **Solution Explorer**
- Right-click \<project name\>
- Select **Manage NuGet Packages...**
- Click **Browse**:  Microsoft.Web.WebView2
- Check **Include prerelease**
- Version: **0.9.628-prerelease**
- Click **Install**
- Click **OK**

Uninstall the Microsoft.Web.WebView2 NuGet package from the project again

- Open Visual Studio
- Open \<project name\>
- **On menu, **View**
- **Solution Explorer**
- Right-click \<project name\>
- Select **Manage NuGet Packages...**
- Click **Installed**
- Click **Uninstall**
- Click **OK**

Modify the Microsoft.Web.WebView2.targets files as described in #431  
-  \<project folder\>\packages\Microsoft.Web.WebView2<version>-prerelease\build\Microsoft.Web.WebView2.targets
-  \<project folder\>\packages\Microsoft.Web.WebView2<version>-prerelease\build\native\Microsoft.Web.WebView2.targets

Install the Microsoft.Web.WebView2 0.9.628-prerelease NuGet package to the project which will copy the WebView2 files/folders from `%UserProfile%\.nuget\packages\microsoft.web.webview2\0.9.628-prerelease` to your \<solution folder\> (including the modified Microsoft.Web.WebView2.targets files)

- Open Visual Studio
- Open \<project name\>
- **On menu, **View**
- **Solution Explorer**
- Right-click \<project name\>
- Select **Manage NuGet Packages...**
- Click **Browse**:  Microsoft.Web.WebView2
- Check **Include prerelease**
- Version: **0.9.628-prerelease**
- Click **Install**
- Click **OK**

Are you using Visual Studio? If so, what version? The latest versions are:

- VS 2017: 15.9.27
- VS 2019: 16.7.5

Use "Visual Studio Installer" to install the latest updates. (Type here to search: Visual Studio Installer)

How are you compiling? Command line? Visual Studio? Are you receiving any errors when you compile? Have you specified any additional build parameters? What Configuration and Platform are you compiling for?

- In menu, **Build**
- Select **Configuration Manager**

If you're using Visual Studio to compile, set the output to Diagnostic.

- Open Visual Studio
- Open the demo project
- Click **Tools**
- Select **Options**
- Expand **Projects and Solutions**
- Click **Build and Run**
- Set **MSBuild project build output verbosity**: Diagnostic
- Click **OK**
- On menu, click Build
- Select Clean \<project name\>
- Select Rebuild \<project name\>
- Copy the contents of the Output window to a text file, zip it, and post it here. (Make sure that it doesn't contain any sensitive information)

Please post the Microsoft.Web.WebView2.targets files that your project is using.

-  \<project folder\>\packages\Microsoft.Web.WebView2<version>-prerelease\build\Microsoft.Web.WebView2.targets
-  \<project folder\>\packages\Microsoft.Web.WebView2<version>-prerelease\build\native\Microsoft.Web.WebView2.targets


What version of Windows 10 are you using? The latest version of Windows 10 is v2004.

- Open a cmd window
- reg query "HKLM\Software\Microsoft\Windows NT\CurrentVersion" -v ProductName
- reg query "HKLM\Software\Microsoft\Windows NT\CurrentVersion" -v CurrentBuild
- reg query "HKLM\Software\Microsoft\Windows NT\CurrentVersion" -v ReleaseId

What OS architecture are you using?
- Open a cmd window
- reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" -v PROCESSOR_ARCHITECTURE

There have been numerous updates during this time. Visual Studio updates, MSBuild updates, MS Edge updates Webview2 updates, and maybe even some OS updates. Please make sure you've installed all of the mentioned updates and reboot your computer.

***Note:** It looks like the MS Edge (stable) update occurs when one navigates to `edge://settings/help` or:

- Open MS Edge Chromium
- Click  "..." in upper-right corner
- Click "About Microsoft Edge"

rather than through Windows Updates.

There's some info in #421 that describes where the MS Edge files and registry keys are.

**Other options:**
Run a chkdsk on your computer (or if you have a desktop support person, ask them to run it).

- Open a cmd window as Administrator
- `chkdsk /r %SystemDrive%`
- You'll see the following message: Chkdsk cannot run because the volume is in use by another process. Would you like to schedule this volume to be checked the next time the system restarts? Enter '**Y**'. Reboot your computer.

[Use the System File Checker tool to repair missing or corrupted system files](https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system)

**Comment by TimWeidner** [comment]
> @TimWeidner
> 
> Please check that your anti-virus isn't blocking/removing the files. If you haven't already done so, please reboot your computer.

This line is exactly what resolved this issue.

The reason for our internal problems with Webview is the simple fact that our corporate structure dictated usage of an old version of symantec endpoint protection. It's not that any files were blocked, but it seams like symantec conflicted with webview2s RendererCodeIntegrity. See [The Chrome 78.0 Symentec SEP error](https://knowledge.broadcom.com/external/article/175842). Two people on our team used the registry workaround and another one did not have Symantec installed for whatever reason. It worked fine on his machine, so that perfectly explains that.

So I am guessing some change to the inner workings of edge/webview (in the last month or so) made the webview crash as soon as RendererCodeIntegrity was disabled. This is obvious in hindsight, but figuring out the problem in the first place took us literally the past 2 1/2 weeks plus some time before that (dealing with some other strange behaviour).

So thank you so much for this detailed answer, which made the penny drop). You sir @cgeier are the real MVP. Thank you so much.

I'm going to close this issue now, please feel free to remove the bug label.
