### ISSUE TITLE
[Problem/Bug]: WinUi3 Webview2 Input box in a web page does not get focus and returning to Webview2 does not restaure focus on input box.

### ISSUE THREAD

**Issue by applefanbois** [MicrosoftEdge/WebView2Feedback#4465]
### What happened?

-Create 2 webview2 side by side. 
-Load a page that set the focus in an input box automatically. (This never works)
-Click on an input box in a webpage to make it in focus.
-Then click on the other webview2 or anywhere else (can be a WinUI3 UI element)
-When you click back on the original webview2, the focus will not return to that input box.

This is annoying for our customers that use our app.
They are used to clicking a button on our toolbar to navigate somewhere then they start typing immediately. Now they need to click in the input box every time.

Even if we navigate in the same webview2 to another place, the input box in the page will not get in focus like it did in our old app.

If you read on the internet you can see that the focus does not work correctly in Webview2. It never did. From my experiment the focus events on the webview2 never trigger unless I do a  webView.Focus(FocusState.Programmatic), but even then, the events will fire, but the input box will never get or regain its focus.

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

all of them

### SDK Version

10.0.22621.3233

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 11

### OS Version

10 and 11 + server

### Repro steps

Just use a webview2 and load a page that contains an input box that get the focus automatically.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by johna-ms** [comment]
@applefanbois I will take some time to investigate the original webview2 not getting focus.

As far as a single webview2 not getting focus after interaction with app elements - this is by design. The normal edge browser can do this because the web contents is all a user is expected to interact with. But with a webview2, there could be any other kind of ui. So a webpage taking focus from the app is actually undesirable. I believe you can achieve the behavior your looking for by simply calling MoveFocus from a NavigationCompleted event.

**Comment by johna-ms** [comment]
@applefanbois I'm seeing MoveFocus work just fine with bing.com when modifying our WinUI3 sample app. I'm also seeing that switching focus between 2 adjacent webviews is working fine. Please provide a minimal repro app that showcases the problem so I can help investigate this for you further.

**Comment by applefanbois** [comment]
How can it works if MoveFocus does not even exist for win32/winui3?
Is there something I am missing?

**Comment by johna-ms** [comment]
Sorry you're right there is no MoveFocus like there is in Win32, but I used xaml's UIElement.Focus API (so you can just call webview2.Focus(focusReason)) and that will focus the webview2 control

**Comment by johna-ms** [comment]
Well there must be something we're doing differently because we're getting different results! Maybe it's something to do with the type of input element on a given website? I've been testing with bing.com. If you could provide a repro app with one or both of your focus issues I can help diagnose the issue

**Comment by applefanbois** [comment]
I don't have access to MoveFocus, it does not exist on our SDK, how can you do the same thing if you have a different SDK?

-You must create a button  [Add WebView2]
-When you click on that button, it creates a new webview2 that navigate to bing if you want.
-Type on the keyboard without clicking on the web input box to see if it works.

**Comment by applefanbois** [comment]
-Made a new empty project with just 1 button that add a webview2 when clicked. 
-When the event onNavigationCompleted is triggered, I call webView.Focus(FocusState.Programmatic);
-It works

But the same thing does not work in my project, my project has many layers underneath the webview2. 
It works in my project if I place a breakpoint there and after the debugger stop there, it will work.
I strongly suspect that again, as always that something is wrong with the webview2.
Since my webview is attached to many layers underneath, this has never been tested by Microsoft.
And since I am the only one stupid enough to make a serious app with WinUI3, well, I am the only one who will ever get that problem.

WebView2 is not programmed correctly, proof is that when you move (detach and reattach) a webview to another window, the context menu will stay  attached to the first windows and many bugs will start to appear. WebView2 is not a dynamic component. As soon as you move it around or change its parameters, everything falls apart.

**Comment by applefanbois** [comment]
It semi-works now, but this is far from ideal.

So if webView.Focus(FocusState.Programmatic) is only called from a webView.Focus(FocusState.Programmatic) and nothing else it works... at least once. But going from tab to tab, there is no way to restore focus in the page like real browsers do. Because calling webView.Focus(FocusState.Programmatic); with even a timer at a later time will never works. So you have only 1 shot at it in a very small window of time and that will never ever work again.

My problem was that webView.Focus(FocusState.Programmatic); was called when the page finished loading and when the tab (that I created) called the webView.Focus(FocusState.Programmatic); right after it would not work.

WebView2 has a problem with focus. webView.Focus(FocusState.Programmatic); should set and restore focus to that webview2 at any time I want and it does not. When I switch tab from one webview to another I want to be able to restore focus on input box that was in focus when I changed tab.

It is still better than nothing and thank you John-ms for your time. But please MS fix the problem. WebView2 should have the exact same behaviour as a real browser to be useful for our customers. They enter a lot of data in our app and loosing focus on input box is annoying all day long.

**Comment by johna-ms** [comment]
Ok I'll resolve this issue but also respond to your question.

Regarding going from tab to tab, WebView2 has no concept of tabs so this is an app issue. As I've said, in a local winui3 sample app I can click between WebView2s and focus shifts just fine. I've also tested with setting focus on WebView2 multiple times in succession using webView.Focus and have no issues. So as far as I can tell, the xaml UIElement.Focus API should be sufficient for your needs. If you have a repro app demonstrating any issues with WebView2 focus, I'd be happy to take a look.

As I've also said, WebView2 not setting focus on navigation is by design. WebView2 doesn't have an address bar like the browser, so it does not set focus upon navigation like the browser does.

**Comment by applefanbois** [comment]
I have implemented the concept of tabs (let say buttons).
When we click on a tabs, I show/hide the proper webview2 and then call set webView.Focus(FocusState.Programmatic) on the newly visible webview2.
This does not work and it should.

Even with a delay and executing on main thread webView.Focus(FocusState.Programmatic) it does not work.
It only works when webView.Focus(FocusState.Programmatic) is called from onNavigationCompleted.
