### ISSUE TITLE
[Problem/Bug]: ShowPrintUI(); top of page is missing if page has been scrolled before printing

### ISSUE THREAD

**Issue by gudmundurtor** [MicrosoftEdge/WebView2Feedback#4653]
### What happened?

1. Scroll page down
2. Call ShowPrintUI(); 
3. **Top of page is missing**

Tested with save as pdf.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2478.35

### Framework

WPF

### Operating System

Windows 11

### OS Version

22631.3737

### Repro steps

1. Scroll page down
2. ShowPrintUI(); 
3. **Top of page is missing**

Tested with save as pdf.
Can be reproduced using WebView2WpfBrowser sample

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

[AB#52085240](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/52085240)

**Comment by ajtruckle** [comment]
I also confirm this behaviour. Only today did I update my WebView 2:

- Runtime: 126.0.2592.68
- SDK: 2592.51

I have just downgraded WV2 NuGet package and tried again (SDK 2535.41). Same behaviour.

This is a critical bug IMHO.
@champnic

**Comment by ajtruckle** [comment]
It also happens if you directly save as PDF without showing the UI. The output is still cropped.

**Comment by victorhuangwq** [comment]
@ajtruckle do you have a version number where it was last working?

**Comment by ajtruckle** [comment]
@victorhuangwq Sadly, I do not. But my WV2 sample I have downloaded is an older one (SDK 1671.0)  and just navigated to a website, scrolled down and go to print. Boom … same issue. So, it has either:

* been in WV2 a very long time and only just noticed.
* never worked in WV2.
* caused by the runtime (this I can't test).

Look:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/88edc4a3-b329-4185-b0e1-a78fc0897b85)

I actually think that Edge is not behaving either. If I scroll both to top:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/9afa77a4-d25c-4959-9c6e-25ce2e781605)

**Comment by champnic** [comment]
I suspect a regression in the runtime. Adding the bug to our backlog.

**Comment by monica-ch** [comment]
@gudmundurtor @ajtruckle I'm not able to repro the issue in WebView2/Edge. Are you still seeing the issue on your end? Are there any specific steps to reproduce? Is it happening the same for other Printers like Microsoft Print to PDF?

**Comment by ajtruckle** [comment]
@monica-ch It is not happening any more in my application. So it seems to have fixed itself. Most peculiar!
