### ISSUE TITLE
WebBrowser Control support in Windows 10 post IE11 EOS

### ISSUE THREAD

**Issue by dealsweb** [MicrosoftEdge/WebView2Feedback#474]
What will happen to the legacy applications that are using WebBrowser control after the IE11 EOS and a new update to Windows 10 with Edge Chromium post 3/2021?

Will WebBrowser control continue to work without IE on the operating system? (When I have only Windows 10 with Edge Chromium)

Or

Does the legacy applications needs to forcefully upgrade WebBrowser control to WebView2?

**Comment by champnic** [comment]
Even after the new Microsoft Edge becomes the default inbox browser on Windows 10 I don't think that means IE11 is EOS. IE mode in Edge requires IE binaries to still exist and run, and I haven't heard of any plan to remove WebBrowser support from windows. Please see this for more info:
https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge

That said, our recommendation is to migrate from WebBrowser to WebView2, but currently that decision should be based more on feature set and capabilities, rather than old controls breaking.

**Comment by KyuHeonNoh** [comment]
> 새로운 Microsoft Edge Windows 10의 기본 관리자 브라우저는 IE 11이 EOS에 대해 생각합니다. Edge의 IE 모드를 실행하여 IE를 계속해서 Windows에서 WebBrowser 지원을 활성화할 수 있게 되었습니다. 자세한 내용은 [https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge를 참조하세요.](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge)
> 
> 현재 우리의 권장 사항은 WebView2로 이미 개선되어 있으며 이전에 우수한 기능을 제공하고 있습니다.

IE11 지원 종료 이후에는 IE11 실행시 강제로 Edge 로 실행되는 것으로 나와있는데, IWebBrowser2 를 사용하여 표출된 페이지에서 링크 클릭시 새창으로 열릴 경우, 기존에는 IE 로 새창이 열렸는데, 이 부분이 Edge 새창으로 열리게 되는 것인지 궁금합니다.
