### ISSUE TITLE
[Problem/Bug]: Breaking change in package: The webview2 assemblies are no transitive dependencies anymore

### ISSUE THREAD

**Issue by TFTomSun** [MicrosoftEdge/WebView2Feedback#4743]
### What happened?

The webview2 assemblies are not imported into library projects as transitive dependencies anymore. This happens due to moving the folder netcoreapp3.0 from lib to lib_manual
![image](https://github.com/user-attachments/assets/ca87a892-92f8-4d76-9871-ebf4db1080c5)
Applications that depend on a library that provides the WebView2 reference don't build anymore, due to the missing transitive dependency behavior. 
When referencing the libraries via build targets now, the build targets should be made transitive, by adding a buildTransitive folder to the package with targets that are importing the targets from the build folder. For more information see: https://learn.microsoft.com/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Other

### Operating System

Other

### OS Version

all

### Repro steps

Repo steps:
- create a net6/8 library with the latest microsoft.web.webview2 nuget package as dependency
- create a application which references the library and adds a webview2
-> compile error: The WebView2 types are unknown
-> expected the app builds fine

This bug was introduced with version [1.0.2651.64](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.2651.64). In version https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.2592.51 the transitive dependency behavior of the assemblies were still fine.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

yes this worked before

### Last working version (if regression)

[1.0.2592.51](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.2592.51)

[AB#53267641](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/53267641)

**Comment by jizc** [comment]
Our WPF app is also failing to build with version `1.0.2651.64`. I'm assuming it is due to the same issue.

**Comment by champnic** [comment]
Thanks for reporting this, and sorry you are running into this issue. We've added it to our internal work tracking and are looking into this regression.

**Comment by oggy22** [comment]
Hi @TFTomSun ! Thanks for reporting this issue. We may know the root cause which is some nuget refactoring for C# Winrt projection. However, I am not able to repro the problem on our sample app and I've tried `<TargetFrameworks>net8.0-windows</TargetFrameworks>` and with `<TargetFrameworks>net6.0-windows</TargetFrameworks>`. It would be great if you could provide a min repro (csproj would suffice). Thank you!

**Comment by TFTomSun** [comment]
Did you create a library project as described? You must add the package reference to the library project and then add that library project to a final app. The app itself doesn't get the webview directly referenced, but it should still be able to add a webview there, because the reference comes transitive in through that library project. .... That transitive dependency is broken

**Comment by jizc** [comment]
I can confirm the error only happens in our WPF app if the main assembly doesn't have a direct `PackageReference` to WebView2, just a transitive one via one of our other assemblies. When both assemblies have a `PackageReference` the solution builds correctly.

**Comment by oggy22** [comment]
@TFTomSun thank you for pointing this out about library project. It would be still of great help if you could provide minimal csproj it repros on. Thanks!

**Comment by jizc** [comment]
Minimal repro: https://github.com/jizc/WebView2BugDemo

- Build fails with error MC3074.
- Switch WebView2 NuGet in ControlsLibrary.csproj to version 1.0.2592.51 and see that build succeeds.

**Comment by oggy22** [comment]
Hey @jizc and @TFTomSun ! The bug is fixed as suggested with introducing a copy from `build\Microsoft.Web.WebView2.targets` to `buildTransitive\Microsoft.Web.WebView2.targets` and the SDKs that will be published by the end of September will have the fix. I am sharing our internal SDK builds with you (you just need to rename them back to .nupkg as github doesn't allow nuget files)
[Microsoft.Web.WebView2.1.0.2805-prerelease.zip](https://github.com/user-attachments/files/16789721/Microsoft.Web.WebView2.1.0.2805-prerelease.zip)
[Microsoft.Web.WebView2.1.0.2805.zip](https://github.com/user-attachments/files/16789722/Microsoft.Web.WebView2.1.0.2805.zip)
It would be great if you could confirm that these fix your problem.

Thanks!

**Comment by jizc** [comment]
Confirmed working, thank you! 🎉
