### ISSUE TITLE
In CoreWebView2_WebResourceRequested, e.Request.Uri is of type String instead of System.Uri

### ISSUE THREAD

**Issue by pipalot** [MicrosoftEdge/WebView2Feedback#542]
In the CoreWebView2_WebResourceRequested event, e.Request.Uri is a String, but it would be more logical for it to be of type System.Uri.

In SDK 0.9.579, the property was called e.Request.RequestUri and was of type System.Uri.

In SDK 0.9.628, the property name changed to e.Request.Uri but became a string instead of a System.Uri.

The renaming of the property from RequestUri to Uri was logical, but I am guessing that it was meant to be of type System.Uri.  Or was that by design?

**Version**
SDK: 0.9.628-prerelease

Runtime: Edge WebView2 Runtime
Framework: WinForms
OS: Win10

**Repro Steps**

```
private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
     // e.Request.Uri is of type String instead of System.Uri
}
```

**Comment by champnic** [comment]
This change was By Design. We made changes to move from the .NET HttpRequestMessage types to CoreWebView2WebResourceRequest, which is a projection of the same type from our COM/Win32 API. We needed this because HttpRequestMessage didn't support all the operations we needed (some aspects of it were read-only, for example). We decided not to wrap with System.Uri because we believed most devs would just have to create a uri around a string, and all we did was convert back to string right away anyways. Do you have a scenario where using a System.Uri would be much more convenient, or was this more of a correctness type of ask?
