### ISSUE TITLE
Using 1.0.622.22 doesn't work with Edge 86.0.622.48

### ISSUE THREAD

**Issue by krpano** [MicrosoftEdge/WebView2Feedback#557]
Edge is currently up-to-date on 86.0.622.48.
And Webview2 is using version 1.0.622.22.

According to the release notes it should work, but it doesn't...

Calling CreateCoreWebView2EnvironmentWithOptions fails.

When using Edge Beta or Edge Canary it works, but the idea for shipping would be that the end-user wouldn't need to install anything, just keep Windows up-to-date.

Did I miss something or is this a bug?

**Comment by krpano** [comment]
I've just found out that Edge Stable is not supported for the WebView2... :-(

Sorry, but a 'webview' that needs something pre-installed is not really a webview anymore!
Even with silent installers and so...

I can understand that there are other usage cases or situations where a fixed or separate webview version can be required, but that should be the optional case and not the default one.

Especially now as Edge Chromium in shipped by default with Windows Updates and even is available for Windows 7.
And telling an user that he only needs an up-to-date Windows 10 version is fine and today already well-accepted. 
Compare to OSX, there are really good webview is available out-of-the-box.

As long as the C++ embedding-API itself is upward-compatible, automatic browser-side updates can be a welcome feature and fully okay.

That means please rethink that decision and either allow Edge Stable or ship Webview2 automatically together with Windows updates. Otherwise Webview2 will be not really an alternative to Electron or the old ActiveX Edge/IE Webview. Thanks!

**Comment by drearyrainDeng** [comment]
If I understand correctly, webview2 runtime will be carried and updated with the system in the future to ensure its availability(no need to install separately)
![image](https://user-images.githubusercontent.com/35326823/96805987-6d100f00-1445-11eb-8ae4-02906e805ea4.png)

**Comment by champnic** [comment]
Thanks for the feedback @krpano. As you've noted WebView2 doesn't work with Stable, only Canary, Dev, Beta Edge (for development) and the WebView2 Runtime for development. More details are here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

We realize this isn't a great distribution story at the moment and are doing work to improve the workflow. We're trying to get the experience closer to what happens when a user is missing a needed .NET framework, for example. We are also working with Windows to make sure the runtime is inbox and available on older OSs, but I don't have a timeline for that yet.

If you do choose to deploy the runtime, it will stay up-to-date the same was as the Edge browser does. Neither the browser or the runtime use Windows Update (besides the initial deployment), but instead update on their own on a 6-week cadence (similar to Chrome/Chromium). 

I'm going to close this issue as there are other similar threads, and we have already planned work to improve this soon (and so there's no new work here). Feel free to continue the discussion here if you wish though. Thanks!
