### ISSUE TITLE
Deactivate menu in Web Viewer 2?

### ISSUE THREAD

**Issue by Rainer-S** [MicrosoftEdge/WebView2Feedback#558]
how can I disable the menu / Context menu when I right click.

Beginners please need help

**Comment by ukandrewc** [comment]
There is a derived control here that will do that here: https://github.com/ukandrewc/Webview2.Winforms.DOM
If you define a ContextMenuStrip for the WVBrowser control, it will show that instead of the WebView2 contextmenu.

Other than that there's a native answer here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/507

**Comment by hunkydoryrepair** [comment]
ContextMenuStrip is now readonly on WebView2 and setting it never worked, anyway.

**Comment by ukandrewc** [comment]
It doesn't because ContextMenuStrip is inherited from Control, it's not connected to WebView2.

**Comment by ShaunLoganOracle** [comment]
@Rainer-S Have you tried setting `yourWebView2Control.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;` ? Seems to work for me in 1.0.721-prerelease. I am setting that property before doing `NavigateToString` or setting `Source`.
