### ISSUE TITLE
WebView2 callback messages not received

### ISSUE THREAD

**Issue by CGuthrie72** [MicrosoftEdge/WebView2Feedback#565]
**Description**
As discussed in issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/544#issuecomment-712377348, links that worked previously on 0.9.628-prerelease are now not working on 1.0.674-prerelease.

No code was changed just the NuGet package updated.  I can see a test message being received as per the documentation sample:
Form.WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.chrome.webview.postMessage(window.document.URL);");
However the following no longer results in a message received:
Form.WebView.ExecuteScriptAsync( "document.getElementById('AlertListTaskAnswers').onclick = function(){ window.chrome.webview.postMessage('AlertListTaskAnswers') }" );

Same if I use: Form.WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(...);

More interesting, if I F12 into Dev tools & execute :
document.getElementById('AlertListTaskAnswers').onclick = function(){ window.chrome.webview.postMessage('messageContent')};
then message is then received on click.

So, something seems to have changed between WebView2 versions in setting up the callbacks.

**Version**
SDK: 1.0.674-prerelease
Runtime: Canary, Beta & Dev
Framework: WinForms
OS: Win10

**Repro Steps**

**Additional context**

**Comment by CGuthrie72** [comment]
Debugging further on this, by moving the initialisation & setup code around I have links working again.  So although something has changed within the comms setup within WebView2 between releases it is working again.

**Comment by champnic** [comment]
Glad it's working again! I wonder if it wasn't getting executed because "DocumentCreated" had already happened by the time you called AddScriptToExecuteOnDocumentCreatedAsync? It's possible a refresh or navigation would have also made the function work again, by generating another "DocumentCreated" event. I'm going to close this one as it looks resolved, but let me know if there's anything I'm missing or you would like to see fixed. Thanks!
