### ISSUE TITLE
Password Autofill "Manage" menu opens new window with ERR_INVALID_URL at "edge://settings/addresses"

### ISSUE THREAD

**Issue by dmcgloin** [MicrosoftEdge/WebView2Feedback#585]
It's awesome that WebView2 is supporting Password Autofill. This is great!

**Description**

One issue I noticed is that when the user clicks the "Manage" button from the dropdown list of usernames, it goes to the edge settings page but this page does not load. You see a new window with an error:

> "Hmmm… can't reach this pageIt looks like the webpage at edge://settings/addresses might be having issues, or it may have moved permanently to a new web address.
> ERR_INVALID_URL"

Is this a known issue?

Should the URL it opens instead be: "edge://settings/passwords"?

**Version**

SDK: 1.0.674-prerelease
Runtime: 88.0.683.0 (Official build) canary (64-bit)
Framework: WPF .NET 4.8
OS: Windows 10.0.14393 Build 14393

[AB#30074503](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30074503)

**Comment by champnic** [comment]
@dmcgloin We currently don't allow access to the settings pages, which is why that's failing to navigate. Unfortunately we've also turned off password autofill for now - we didn't want users to be using an app and then all of a sudden be confronted with a dialog saying that Microsoft Edge is now saving their password without their consent. We have plans to improve the experience and re-enable password autofill in the future.

Are you seeing the saved password actually get populated in the password field? For the username, my guess is that it thinks it's an address and is using that to autofill - hence the "Manage" option trying to navigate to "edge://settings/addresses".

**Comment by ukandrewc** [comment]
@champnic Autofill is still enabled for addresses, would be good to get it turned off for next release please ;-)

**Comment by dmcgloin** [comment]
@champnic Thanks for the status update. A little sad to see autofill delayed, but totally understand. Note that for us this was the big improvement over CefSharp. We would delay release without this advantage.

The page where it appeared is here: https://accounts-e2e.intuit.com/protax-signin-oauth.html

Yes, the autofill actually gets populated for me. Screenshot attached.

![Screenshot](https://user-images.githubusercontent.com/457139/98184094-66aa7a00-1ebe-11eb-8992-784c42fdc6a6.png)

Btw, super happy that MS is driving this very big initiative. Very much appreciate the great value you are providing by getting this to production.

**Comment by champnic** [comment]
We appreciate the support! It's good info to have that this could delay your release, I'll add that info to our backlog item and bring it up for re-prioritization to see if there's anything we can do here.

One of the reasons we disabled it was because we didn't have a management experience that was separate from the browser/edge://settings. Would it work for your scenario if we had autofill off by default, you had an API to enable it, but wouldn't have the "Manage" button? There wouldn't be a great workaround for clearing autofill info - currently you'd have to recreate your UserDataFolder, which would wipe out everything (history, cache, etc.).

**Comment by dmcgloin** [comment]
Thanks again, @champnic 

I understand the proposal and I think this would work. The "Manage" button was a nice addition, but absolutely not necessary. I just tried switching our implementation back to the classic IE WPF browser control and see that this is essentially how this behaves anyway. When we moved to CefSharp, our biggest complaint was the loss of autofill support.

So, yeah, this would be perfectly fine. Thank you

**Comment by abhi4u1947** [comment]
@champnic We have also faced the issue that on our web page also its offering the "Manage" button for autofill and when user clicks on it then its opening "edge://settings/addresses" page which opens different window with error.

Hmmm… can't reach this pageIt looks like the webpage at edge://settings/addresses might be having issues, or it may have moved permanently to a new web address.
ERR_INVALID_URL

This must be fixed

**Comment by maurawinstanley** [comment]
Hi all, we are working towards a solution for an autofill setting, please look to the main thread, [https://github.com/MicrosoftEdge/WebView2Feedback/issues/374](here), we would love to hear your feedback.  @abhi4u1947 @dmcgloin thanks for posting this, we have put in a fix for this and the "Manage" button should be disabled now if you are using canary.
