### ISSUE TITLE
[.net core] [WinForms]  AddScriptToExecuteOnDocumentCreatedAsync in CoreWebView2Ready after EnsureCoreWebView2Async not working

### ISSUE THREAD

**Issue by kirsan31** [MicrosoftEdge/WebView2Feedback#597]
**Description**
`AddScriptToExecuteOnDocumentCreatedAsync` in `CoreWebView2Ready` event behave different with 2 variant of initialization: `webView21.Source = new Uri("about:blank");`  - script will work
`webView21.EnsureCoreWebView2Async();` - script will not work

**Version**
SDK: 1.0.674-prerelease
Runtime: canary 88.0.688.0
Framework: Net core 3.1.9, WinForms
OS: Win10

**Repro Steps**
```cs
webView21.CoreWebView2Ready += WebView21_CoreWebView2Ready;
webView21.Source = new Uri("about:blank"); // Work
//_ = webView21.EnsureCoreWebView2Async(); // Not work
//await webView21.EnsureCoreWebView2Async().ConfigureAwait(true); // Not work
```
[WebView2Test.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5481246/WebView2Test.zip)

[AB#30092910](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30092910)

**Comment by champnic** [comment]
Thanks for the report, I've added a bug to our backlog and we'll take a look!

**Comment by champnic** [comment]
We believe this is By Design. When setting the source property, initialization will navigate to "about:blank". When using EnsureCoreWebView2Async there won't be a navigation, thus no DocumentCreated, and so no script will run. You should be able to get the behavior you want by navigating after using EnsureCoreWebView2Async. Let me know if that doesn't work for you and I can reopen. Thanks!
