### ISSUE TITLE
System.NotImplementedException: Unable to cast to 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2ExperimentalEnvironment'

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#630]
**Description**
I'm using the runtime of WebView2 (Evergreen Bootstrapper, the app itself calls GetAvailableCoreWebView2BrowserVersionString at start and downloads the bootstrapper if version string is null) and nuget package 1.0.674-prerelease. App is published as WPF .NET 5.0 x64 single file. I get the following error, when I call `webView.CoreWebView2.CookieManager.GetCookiesAsync` at start right after `WebView_CoreWebView2Ready` event raised. 

`System.NotImplementedException: Unable to cast to 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2ExperimentalEnvironment'. This may happen if you are using an interface not supported by the version of the WebView2 runtime you are using.`

I've installed Edge DEV and Edge Canary but the problem persist. Happens on one computer and on the other not. Any idea what's causing it? How can I figure out the installed WebView2 runtime version? And the version the application needs? So I can at least compare to see which one is older or if both are identical etc.

Just to be clear: The WebView2 control is fully shown and works fine. But accessing the cookiemanager right CoreWebView2 raises its ready event, for some reason throws on one machine and it doesnt on another machine.

**Version**
SDK: `1.0.674-prerelease`
Runtime: Edge default 86.0.622.68 up to Canary 88.0.698.0
Framework: WPF
OS: Windows 10

**Repro Steps**
Sadly I cannot give steps here as it seems to be machine related.

**Screenshots**
![image](https://user-images.githubusercontent.com/14368203/99109760-96a5fb80-25e9-11eb-8e39-1d46e39f03f8.png)

[AB#30898940](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30898940)

**Comment by champnic** [comment]
The default search order for a runtime is WebView2 Runtime > Beta > Dev > Canary - so it's probably picking up the WebView2 Runtime 86.0.622.68 instead of the newer Canary. You are right in thinking that Dev or Canary will have the needed support for that experimental API. To get your app to choose Dev or Canary, you can either:
1. specify the [Browser Executable Folder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=WebView2-dotnet-1.0.674-prerelease) to point to the Dev or Canary install
1. Set the [WEBVIEW2_RELEASE_CHANNEL_PREFERENCE](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.622.22#createcorewebview2environmentwithoptions) environment variable, which can switch the search order from most-stable-first to least-stable-first.
1. Uninstall the WebView2 Runtime so it picks up the Dev/Canary install instead.

**Comment by champnic** [comment]
You can also call `CoreWebView2Environment.GetAvailableBrowserVersionString` after creating the environment to verify which version it found and is using:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring?view=WebView2-dotnet-1.0.674-prerelease

**Comment by Symbai** [comment]
Thanks for the response. Uninstalling the runtime and (verify installed) Canary fixed the exception. Kinda frustrating that the control doesn't verify itself at which runtime it runs.

I mean, if it requires a minimum version of X. It should first check whether the runtime version meets this criteria and if NOT (which seems to be the case here) it should either throw an exception which is more clear. Or it should check if there are other (newer) runtimes to choose such as Beta or Dev or Canary.

It shouldn't leave the troubleshooting to the devs and users to figure it out. Because otherwise using the Evergreen bootstrapper is a guarantee to cause issues. I think there is some room for improvements regarding this. Feel free to close the issue or use it as a tracking issue if you agree with me.

**Comment by champnic** [comment]
I completely agree - I've added this to our backlog to track improving this behavior.

In general this won't happen with the release versions because the runtimes will match, whereas the prerelease packages are always a bit ahead and so can break like this.

**Comment by champnic** [comment]
We have documentation covering this scenario now:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

Thanks!
