### ISSUE TITLE
Webview2 not rendering in VSTO when running multiple instances of the same app

### ISSUE THREAD

**Issue by Tiagovsky** [MicrosoftEdge/WebView2Feedback#655]
**Description**
We are rendering a Webview2 control in an integrated window in Word. Initially, everything renders correctly, but when opening a new instance of Word (for example, by opening a new document), the integrated window does not render the Webview2 control, despite navigation happening. We tracked the navigation by checking the NavigationCompleted event.

We are using the same environment settings, including UserData folder, between all windows.
If we use a different UserData folder every time, everything renders correctly and the bug cannot be reproduced.

This applies to all Office applications.

**Version**
SDK: 1.0.664.37
Runtime: Canary 89.0.707.0
Framework: WinForms
OS: Win10

**Repro Steps**
1. Open Word with a VSTO add-in that renders an integrated window with an Webview2 control that navigates somewhere
2. Open another instance of Word with the same window.
3. Verify that the page does not render in one of the instances

Expected: A page should render in all instances

**Screenshots**
![image](https://user-images.githubusercontent.com/497202/99974224-ef6f5400-2da0-11eb-948b-bb29a54e47ce.png)

**Comment by Tiagovsky** [comment]
Retested today with version 1.0.707.0 of the SDK and instead of showing the control as if it was in design mode, it shows only white. Pressing F12 for example does not open the developer tools, but the Save action of Word.

**Comment by champnic** [comment]
Your first issue is probably the same as #622, which we fixed in 1.0.707-prerelease. However, for the second issue you are probably running into #678 (for which we deprecated that release and are putting out a new SDK package soon). You can try the workarounds mentioned in my comment though: https://github.com/MicrosoftEdge/WebView2Feedback/issues/678#issuecomment-736070507

If that doesn't fix the issue, please let me know and I can reactivate this. Thanks!
