### ISSUE TITLE
.NET - 1.0.707-prerelease WebView2 doesn't load any page when using WebView2 Runtime

### ISSUE THREAD

**Issue by lucapivato** [MicrosoftEdge/WebView2Feedback#678]
**Description**
Doesn't work.

**Version**
WebView2: 1.0.707-prerelease, 1.0664.37.0
Edge: 87.0.664.47
Windows: 10

**Repro Steps**
- New WinForms project
- Add WebView2 NuGet
- Drop WebViewer2 control on form
- Set webView21.Source to "https://google.com" in designer (or in code, doesn't matter)

**Screenshots**

![image](https://user-images.githubusercontent.com/37640802/100266864-83b3f500-2f20-11eb-9213-712292d4e37e.png)

**Comment by jakasi2** [comment]
Identical setup works for me.

Edge Browser 87.0.664.47 64-bit
WebView2 Runtime 87.0.664.47
NuGet Microsoft.WebView2 1.0664.37.0
Windows 10 Home 20H2
Microsoft Visual Studio Community 2019 v16.8.2

**Comment by lucapivato** [comment]
Weird. Also enabled all exceptions in VS but nothing is thrown. Tried all sorts of combinations. Always blank. Will try on a different machine.

**Comment by dmcgloin** [comment]
I've seen this happen starting with 1.0.707-prerelease.
For me, it happens approximately 1 in 4 times.

**Comment by jakasi2** [comment]
I tried 1.0.707-prerelease and it also causes problems. For me it happens all the time.
1.0.674-prerelease and 1.0.664.37 works for me with respect to this glitch.

**Comment by champnic** [comment]
Hey all - thanks for these reports! I believe the issue you're running into is a compatibility bug between the new prerelease package and latest runtime. We've got a fix in the works now, and are potentially going to deprecate 707-prerelease and release a new prerelease package soon. This should only affect the prerelease package.

**Workaround** 
In the meantime, please continue to use 1.0.674-prerelease package, or use Canary/Dev Edge instead of the WebView2 runtime.

**Comment by cppchuff** [comment]
I have tried 1.0.721, 1.0.664 and 1.0.674 in .NET Framework4.6.2 and 4.8. It doesn't load any page. I think it may be caused VS2019. I do the same things according #431, it doesn't work.

**Comment by dmcgloin** [comment]
Still happening for me with 1.0.721-prerelease
