### ISSUE TITLE
Error in GetContentAsync()

### ISSUE THREAD

**Issue by b0dnar** [MicrosoftEdge/WebView2Feedback#683]
Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebResourceResponseReceivedEventArgs'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D1DB483D-6796-4B8B-80FC-13712BB716F4}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

**Comment by pagoe-msft** [comment]
@b0dnar could you provide more clarity on how you came across this exception? Which WebVIew2 package were you using?

**Comment by b0dnar** [comment]
I using Microsoft.Web.WebView2.Core
I wand to get an answer from the site.
I use the following code:
webView.CoreWebView2.WebResourceResponseReceived += (senderO, ev) =>
            {
                if(ev.Response.ReasonPhrase != null)
                {
                    try
                    {
                          var rez = ev.Response.GetContentAsync().GetAwaiter().GetResult();
                          StreamReader reader = new StreamReader(s);
                          string text = await reader.ReadToEndAsync();
                    }
                    catch(Exception e)
                    {
                    }
                }
            };

**Comment by champnic** [comment]
Thanks for the added context. Could you also add what WebView2 Nuget SDK version you have installed, and what version of the browser/runtime you are using?

A QueryInterface failure like this generally indicates a mismatch between the SDK and runtime. The fix is probably to use the Edge Dev/Canary channel.

**Comment by b0dnar** [comment]
I use Nuget 1.0.707-prerelease version WebView2
Version prerelease so use Edge Dev/Canary

**Comment by champnic** [comment]
Thanks! It's possible you are running into #678 which caused us to deprecate the 707 package. Could you try the latest 1.0.721-prerelease SDK and see if it still repros?

The default search order for the runtimes is WebView2 Runtime > Beta > Dev > Canary, so if you have the Runtime installed it might be picking that up instead of Dev or Canary. To use Dev or Canary, you can uninstall the Runtime, or set the environment variable WEBVIEW2_RELEASE_CHANNEL_PREFERENCE to 1. (We are already tracking improvements to make this more straightforward)

**Comment by infiniteloopltd** [comment]
Seeing the same issue on 1.0.2210.55 (WebView2 .NET Interop Wrapper), where calling  GetContentAsync()

`   private async void CoreWebView2_WebResourceResponseReceived2(object? sender, CoreWebView2WebResourceResponseReceivedEventArgs e)
   {
       if (!e.Response.Headers.Contains("Content-Type")) return;
       var contentType = e.Response.Headers.GetHeader("Content-Type");
       if (contentType == "application/json")
       {
           try
           {
               var sContent = await e.Response.GetContentAsync();`

This happens only sometimes, in my case, capturing the result of an AJAX request.
