### ISSUE TITLE
WebView2 vs solution folder name contains '#' character

### ISSUE THREAD

**Issue by Tifred25** [MicrosoftEdge/WebView2Feedback#705]
Hello,

The WebView2 control does not work if the solution folder name contains the "#" character.
No exception is raised but the WebView2 control does not display the web page.

I met this problem with Visual Studio 2019, Windows 10 and WebView2 Control for Windows form in C#. 

If I rename the solution folder  (to remove the '#'), then the WebView2 control works correctly

I searched a long time before finding the origin of the problem, it's why I post this issue :)

**Comment by champnic** [comment]
This is probably related to the UserDataFolder which gets created next to the .exe by default. You can workaround by not having '#' in the name, or by manually specifying a UserDataFolder location:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder

We are already working on making the error more clear when the failure is caused by the UserDataFolder creation.

Thanks for the report, and apologies about the time spent investigating!
