### ISSUE TITLE
Embeddable WebView2?

### ISSUE THREAD

**Issue by aloneguid** [MicrosoftEdge/WebView2Feedback#729]
I've tried webview2 today and after loading a simple html page in my app I ended up with extra 6 processes running, consuming 300mb extra ram and local disk cache of 500mb. I've also read you need to ask users to install this and they need a privileged local account to do that.

There's no way I'm doing it right, otherwise what's the point of having it? All I want is to display a relatively simple html view inside my native app, is this supported?

**Comment by hunkydoryrepair** [comment]
WebView2 uses the Edge-chromium rendering engine, which is not a part of windows. It is updated through Windows Update, so most people will have it unless they uninstalled it, but installing latest version of Edge is more of a pain than installing the WebView2 runtime.

And the rendering engine includes the full javascript v8 engine and WebGL and everything you can do in HTML5. It's big.  But it is actually less overhead than most alternatives, such as CEFSharp.  If you only want to display HTML and not interact with it (follow links, tooltips, animations, etc.) there are probably other rich text controls you could use.

**Comment by aloneguid** [comment]
I will find it impossible to explain to end users with average laptops. 600mb + 1gb disk for a simple app? Not going to fly. It will be a very very long time till it's available via Windows update for certain groups of customers as well.

We were more hoping to get html/CSS renderer with ability to turn off all the bloat not required for desktop applications. Such as JavaScript support is not needed because on desktop you can run something better. Web assembly same. All the networking stuff not needed for running locally etc. So not a rich text view, rather web view but not a web browser. As it stands even Electron is easier to deploy, develop, and performance is almost the same?

**Comment by liminzhu** [comment]
Hi @aloneguid. It sounds like there are two aspects to this. 

We are putting WebView2 Runtime in-box in future Windows versions and planning to have a best-effort push to in-market win10 devices (it's impossible to get everyone on an older OS to get a new component) so that you will no longer need to deploy WebView2 Runtime often. 

In terms of resource consumption, we are always looking at improving perf. If there are more than one app using evergreen WebView2, the DLLs should also get paged into memory once (although the apps will still have other own processes unless they share user data folder for very good security reasons). We currently don't have a plan to support a well-defined stripped-down version that disables a bunch of stuff and consumes less resources. This might be something we'd look long-term, but unlikely in the next couple of months given the current priority. One thing you can do in the mean time is to turn off anything you don't want through edge/chromium browser args (see [WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.664.37#createcorewebview2environmentwithoptions)).

**Comment by douglas-jordan** [comment]
All modern browsers are multi-process with high memory usage, including Edge/WebView2

**Comment by aloneguid** [comment]
I've found and ended up using [Ultralig.ht](https://ultralig.ht/). Suits my needs - high web compatibility, truly embeddable and light on resources. I don't have to use a separate PC per app to accomodate chromium disk/ram/cpu requirements anymore :)
