### ISSUE TITLE
Allow developers to specify the path of WebView2Loader.dll explicitly

### ISSUE THREAD

**Issue by TheSned** [MicrosoftEdge/WebView2Feedback#767]
We have native CLR host application that hosts WPF content and would like to use the WebView2 WPF control. However, because our native CLR host application does the assembly loading manually, the loaded assemblies have a null value for their CodeBase property. This causes problems when CoreWebView2Environment tries to load the native library. I saw a suggestion in #612 about calling the native function `CreateCoreWebView2EnvironmentWithOptions` manually, but even if I do that, I would still need a way to create the Managed CoreWebView2Environment from the returned ICoreWebView2Environment, which we cannot do because there is no public API exposed to do that. I have been able to work around this limitation so far by manually calling LoadLibrary() and then using reflection to set the `CoreWebView2Environment.webView2LoaderLoaded` field, but this shouldn't be necessary and could break if the internals of CoreWebView2Environment ever change.

I would propose another optional parameter be added to `CoreWebView2Environment.CreateAsync()` to specify the path of WebView2Loader.dll, or the base directory where the various architecture variants are located. Alternatively, there could be an option to specify that the native library has already been loaded previously by the caller and not try to load it again.

[AB#31263121](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31263121)

**Comment by mrsteamfist** [comment]
You can by using:
`SetDllDirectory(libraryPath);`
libraryPath is the directory that holds your loader.
To use SetDllDirectory, you must do this:
`[DllImport("kernel32.dll", SetLastError = true)]`
`public static extern bool SetDllDirectory(string lpPathName);`
For more information on DllImport -> https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute?view=net-5.0
For more information on the SetDllDirectory function-> https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setdlldirectorya

**Comment by TheSned** [comment]
Your solution does not solve the problem for 2 reasons:

1. `CoreWebView2Environment.LoadWebView2LoaderDll()` calls `LoadLibrary()` with an absolute path. When an absolute path is used, only that path is searched.
2. In my case, the code doesn't even get to the point where `LoadLibrary()` gets called because it throws a `System.UriFormatException: 'Invalid URI: The URI is empty.'` trying to execute this code: `string directoryName = Path.GetDirectoryName(new Uri(typeof (CoreWebView2Environment).Assembly.CodeBase).LocalPath);`

**Comment by billybooth** [comment]
I wouldn't mind seeing this as well.  It's not critical for us as it is for @TheSned, but we would definitely appreciate some flexibility with respect to the location of the native loaders relative to the WebView2 assembly.  I'm particularly bother bothered by the utilization of the "architecture" directories in the output directory and think that providing the flexibility requested here (particularly specifying the full path of the loader assembly used to create the `CoreWebView2Environment`) would make me really happy.

**Comment by champnic** [comment]
I agree this would be a nice addition. I think the solution of adding the ability to specify that the native library has already been loaded is probably the more straightforward approach. I've added this item to our backlog, thanks!

**Comment by jamesjcurrie** [comment]
I came across this feature request issue while trying to deploy webview2 inside a single Excel XLL file. I have a C# project that contains all my references to WebView2 that gets compiled into a dll which eventually gets packed by Excel DNA with our other project dll's into a single XLL file that we distribute to our users. Since the WebView2Loader.dll is a native dll, Excel DNA can't pack it into the xll. Instead I'm zipping up the runtimes directory as an embedded resource and at runtime, extracting its content to a folder on the user's app data directory. We use this technique for other resource files as well. 

In my first attempt, I was able to get our application working well with WebView2 without packaging the WebView2Loader.dll's at all. But for some of our test machines, we hit runtime errors where the application is looking for those dll's that we didn't pack (we're still unsure of why some machines can find the runtime successfully without WebView2Loader.dll). So now I have the runtimes directory extracted to the same user directory that we are using for the userDataFolder.

` await CoreWebView2Environment.CreateAsync(userDataFolder: envPath)`

I was curious as to if this feature enhancement is being planned for anytime soon and if not, is there documentation on the best approach for overcoming the absolute path of the WebView2Loader another way?

**Comment by CallumCarmicheal** [comment]
Is there any news on this issue as I currently work in a environment where we are unable to ship the dll's in the same folder as the application. Is there any solutions to this problem as of yet?

**Comment by champnic** [comment]
Hey @CallumCarmicheal - We recently shipped this here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.loaderdllfolderpath?view=webview2-dotnet-1.0.1248-prerelease

Please give it a try and let me know if you find any issues. Thanks!
