### ISSUE TITLE
AddHostObjectToScript takes time to execute

### ISSUE THREAD

**Issue by abhijeetnarvekar** [MicrosoftEdge/WebView2Feedback#782]
**Description**
It looks like AddHostObjectToScript is asynchronous, but it doesn't return a Promise<Task>

On invoking ExecuteScriptAsync immediately after AddHostObjectToScript. The functions attached to host object fail to invoke.
On adding a delay they invoke successfully.

Should AddHostObjectToScript should be asynchronous?

**Version**
SDK: WebView2-dotnet-1.0.664.37
Runtime: 87.0.664.66
Framework:  WinForms
OS: Win10

**Repro Steps**
```
namespace WebView2Test
{
    [ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisible(true)]
    public class Bridge
    {
        private Microsoft.Web.WebView2.WinForms.WebView2 webView;
        public Bridge(Microsoft.Web.WebView2.WinForms.WebView2 webView)
        {
            this.webView = webView;
        }
        public string SelectRanges()
        {
         // This should have been invoked when ExecuteScriptAsync was called. But it didn't
            return "Selected";
        }

        public async Task FireSelectRangesAsync()
        {
            webView.CoreWebView2.AddHostObjectToScript("bridge", this);

            // SelectRanges() function does not get called if ExecuteScriptAsync is invoked immeditely.
            // If I add a delay of 500ms then it gets invoked.
            // Should AddHostObjectToScript been asynchronous?

            // Thread.Sleep(500);
            string res = await webView.ExecuteScriptAsync("const bridge = chrome.webview.hostObjects.bridge; bridge.SelectRanges();");
        }
    }
}
```

Additional Questions:
The class object passed to AddHostObjectToScript is a referenced copy or object is cloned?

**Comment by jasonstephen15** [comment]
Hi @abhijeetnarvekar, thanks for the question. I believe you are asking if AddHostObjectToScript needs an await in front of the function, please let me know if I am interpreting this wrong? Have you tried it that way, it looks like it should fix the bug you are facing, without having to use Thread.Sleep().

Regarding your additional question: From the [reference doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=WebView2-dotnet-1.0.721-prerelease): 'Host objects are exposed as host object proxies via window.chrome.webview.hostObjects.{name}. Host object proxies are promises and will resolve to an object representing the host object.'

Please let me know if this is unclear, or I can help otherwise!

**Comment by abhijeetnarvekar** [comment]
Hi @jasonstephen15 I found what's going wrong! Our JavaScript it is. It loads an Iframe after document has loaded. We need to wait for [FrameNavigationComplete](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.framenavigationcompleted?view=WebView2-dotnet-1.0.664.37)
Calling AddHostObjectToScript on FrameNavigationComplete solved the issue for us.

Thanks for the help.

Best
