### ISSUE TITLE
General query on WebView2 Fixed version runtime release

### ISSUE THREAD

**Issue by prabodhmairh** [MicrosoftEdge/WebView2Feedback#793]
I have couple of queries regarding the WebView2 fixed version runtime releases
1. When the newer versions of WebView2 Fixed version runtime get released, will the older version also be available for users to download (via some archive page or something similar)?
2. WebView2 Fixed version runtime is available on distribution page as a package to decompress and use. But this would not create the registry entry as mentioned in this [document](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment).
So if my app depends on this [registry](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment) key to determine if the WebView2 runtime is available on the system, it wouldn't know of the fixed version runtime being present. 
I wanted to validate if my understanding is correct, and if there is going to be an installer based installation for Fixed version runtime as well in future.

**Comment by champnic** [comment]
@prabodhmairh 

1. I don't think we currently have plans to keep an archive of previous Fixed Version runtimes, but @liminzhu should be able to confirm.
2. Correct. The benefit of the evergreen WebView2 Runtime is that it can be shared by all WebView2 apps on the system, thus saving disk space for the user. The benefit of Fixed Version Runtime is that it gives you more control over versioning, at the cost of increased disk space and needing to manage the runtime yourself. If you wanted to use Fixed Version, you would include it in your app package and deploy it yourself, and wouldn't use the registry key. There are no plans to make Fixed Version runtime be installable using an installer.

**Comment by prabodhmairh** [comment]
Thanks @champnic

**Comment by liminzhu** [comment]
> I don't think we currently have plans to keep an archive of previous Fixed Version runtimes, but @liminzhu should be able to confirm.

Yah our current plan is to always hosted most patched version of the latest and second latest release (Fixed Version just GA'ed so it doesn't have a second latest release at the moment). Developer are more than welcomed to cache anything they'd like to keep long-term. Fixed Version is very new so this is what we're running with now. Open to feedback.

**Comment by westinyang** [comment]
> 我对 WebView2 固定版本运行时版本有几个疑问
> 
> 1. 当新版本的 WebView2 固定版本运行时发布时，旧版本是否也可供用户下载（通过一些存档页面或类似的东西）？
> 2. WebView2 固定版本运行时在分发页面上可以作为一个包解压使用。但这不会创建本[文档](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment)中提到的注册表项。
>    因此，如果我的应用程序依赖此[注册表](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment)项来确定 WebView2 运行时是否在系统上可用，它就不会知道存在固定版本运行时。
>    我想验证我的理解是否正确，以及将来是否会有基于安装程序的固定版本运行时安装。

I have archived WebView2 Fixed Version Runtime since the beginning of 2021, and currently I have collected versions 88 ~ 104. I created a repository and uploaded the archived files through Releases, hoping to help everyone, https://github.com/westinyang /WebView2RuntimeArchive

**Comment by liminzhu** [comment]
Hi @westinyang . 

> 当新版本的 WebView2 固定版本运行时发布时，旧版本是否也可供用户下载（通过一些存档页面或类似的东西）？

我们目前没有任何计划增加fixed version存档页面但是如果大家都需要的话会重新考虑。为了帮助我们理解你的使用原因，请问你为什么需要旧的fixed version？

This is a good thread to pile up on this issue. We don't have any current plans but could reconsider when there is more demand. Can you let me know why you want an old fixed version? 

> WebView2 固定版本运行时在分发页面上可以作为一个包解压使用。但这不会创建本[文档](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment)中提到的注册表项。
因此，如果我的应用程序依赖此[注册表](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment)项来确定 WebView2 运行时是否在系统上可用，它就不会知道存在固定版本运行时。

文档中的注册表项是用来确认系统上共享的evergreen webview的。系统上没有共享的fixed version，app需要自己部署自己的fixed version。

The registry is for evergreen WebView2 too, which is shared per system. For fixed version runtime, there isn't a "system" one to check for, you will need to package and deploy the bits with the apps yourself.

**Comment by westinyang** [comment]
@liminzhu

Here are some of my personal reasons why using an older version:

- So far I'm still using CefShape (chromium 49) to develop desktop applications, he is even compatible with xp/win7/win10, although it is an old version, but most websites still work properly now.
- The older the version, the smaller the volume and the smaller the packaged application, which is convenient for distribution to users
- The newer the version, the more restrictive strategies the chromium kernel will have, which may bring more trouble to actual development
- I don't need most of the APIs in the new version. Currently, I only need web page rendering, js interaction, video playback, etc.
- Decided to switch from CefSharp to WebView2 because CefSharp has cut out a lot of features, such as: Notification API, h.264 support, etc.

---

以下是我使用旧版本的一些个人原因：

- 目前我仍在用CefShape (chromium 49) 开发桌面应用，他甚至兼容xp/win7/win10，虽然是老版本，但是现在大部分网站还是可以正常使用的。
- 版本越旧，体积越小，打包的应用越小，方便分发给用户
- 版本越新，chromium内核的限制策略越多，可能会给实际开发带来更多麻烦
- 我不需要新版本中的大部分 API。 目前我只需要网页渲染、js交互、视频播放等。
- 决定从 CefSharp 切换到 WebView2，因为 CefSharp 删减了很多功能，例如：Notification API、h.264 支持等。
