### ISSUE TITLE
Attempting to call EnsureCoreWebView2Async when another user has a WebView2 control active throws COMException on Windows Server 2016

### ISSUE THREAD

**Issue by adam-g1** [MicrosoftEdge/WebView2Feedback#825]
**Description**
In Windows Server 2016, when attempting to initialize a WebView2 instance with another logged in user that has the same application also utilizing WebView2 throws a COMException. This occurs when using the Evergreen installation. When a singular user launches the application twice, no exception is thrown.

I was also able to get this error when using a fixed distribution method, using the same version. This requires that both users launch the application from the same directory. If you copy the application into a new directory and have the users launch the different applications, no exception will be thrown.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebViewTesting.frmWebView2.VB$StateMachine_8_InitializeAsync.MoveNext() in C:\Users\agarr\source\repos\WebViewTesting\WebViewTesting\frmWebView2.vb:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Version**
SDK: 1.0.664.37
Runtime: Evergreen - 87.0.664.75
Framework: Winforms
OS: Windows Server 2016

**Repro Steps**

1. Use the Evergreen installer to install the latest version of WebView2 runtime.
2. Create an application that uses WebView2, set the source to any website.
3. On User A, open the application
    a. The application will load the website
4. Keeping the application loaded and User A logged on, login to User B.
5. On User B, open the test application and click Open WebView2
6. The exception shown above will be thrown.

**Comment by champnic** [comment]
When using the same UserDataFolder (which by default is created under the executable's directory) the runtime will try to reuse existing browser processes (GPU, Browser, Network, etc.) with separate Renderer processes. However, this requires that the environment options passed in to the loader (language, SSO, environment variables, etc.) are the same or it will fail. It possible that's what's happening here, or it could be that the browser processes are not reusable because they are tied to another user.

You can try specifying a different UserDataFolder that's unique for the user (which is why the workaround of using different directories is working):
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.664.37#createcorewebview2environmentwithoptions

**Comment by adam-g1** [comment]
I was able specify the UserDataFolder to a per user directory and was able to verify that it worked. This is what I used to do so, thanks for the help.

```vb
'Create the environment with a user-specific user data folder
Dim env As CoreWebView2Environment = Await CoreWebView2Environment.CreateAsync(userDataFolder:=$".WebView2/{Environment.UserName}")

'Initialize the WebView2 core
Await Me.mBrowser.EnsureCoreWebView2Async(env)
```
