### ISSUE TITLE
How to dock console ?

### ISSUE THREAD

**Issue by Kitiara** [MicrosoftEdge/WebView2Feedback#837]
Is there any way to dock the console ?

**Comment by champnic** [comment]
Hey @Kitiara, could you add some context here? What do you mean by "console" - the developer tools javascript console, a Visual Studio console, other?

**Comment by Kitiara** [comment]
I mean the developer tools. Right now i'm working on the [WebView2Browser](https://github.com/MicrosoftEdge/WebView2Browser) and i couldn't find a single code about the developer tools anywhere including web. What i want to do is to dock the developer tool window by pressing ALT + SHIFT + D [very much like chrome does](https://i.gyazo.com/8133ad2fe570af57bcba21ee80c7e7ed.gif). Maybe i can do that by working on the HWND of the developer tools window. I haven't try that one though.

**Comment by champnic** [comment]
Thanks for the clarification. I think we explicitly disabled docking the dev tools because of the challenges around not being the host app, so there isn't currently a way to dock the console. I would definitely continue investigating if your app can do that. If this is a core part of your app experience and you need a docked console, I can also open a scenario on our backlog, but my hunch is it would be low priority and wouldn't get looked at for a while.

**Comment by Kitiara** [comment]
@champnic I have made some [changes ](https://github.com/Kitiara/WebView2Browser/commit/501f55bb1dc63ca2f136a9d3c0ec34acda7605ad)on my fork and managed to make the docking mechanism work. You have to click on the webview itself and then press `ALT + SHIFT + D` to test it. Note that this key is not working on the window of the dev tools. It's because there is no way of adding `AcceleratorKeyPressed` event for that window and i couldn't alter WndProc either.

Issues:
1. Title bar is not going away. 
2. There is a graphical glitch circling around the window. 

See [screenshot](https://i.gyazo.com/d63af6e2aad7af20ac52dad786dfd5cd.jpg).
