### ISSUE TITLE
Button clicks in WebView2 call methods in C#

### ISSUE THREAD

**Issue by tildebox** [MicrosoftEdge/WebView2Feedback#874]
Hi, is it possible to call a method in C#, after a user clicks a button in WebView2?

Example:
- WebView2 loads html with buttons numbered from 1 to n
- User clicks on a button, e.g. on button 12
- Call C# method Clicked(int buttonNumber) and deliver 12 as paramter

**Comment by champnic** [comment]
Hey @tildebox! Yes, you can send info from JS -> C# host app using Host Objects or window.chrome.webview.postMessage.

**Host object**: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.705.50#Microsoft_Web_WebView2_Core_CoreWebView2_AddHostObjectToScript_System_String_System_Object_

**postMessage/WebMessageReceived**: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webmessagereceived?view=webview2-dotnet-1.0.705.50

For your scenario I would recommend using postMessage because it's simpler. Hope this helps! Let me know if you need more info.

**Comment by hakzhyena** [comment]
Hi,

I am trying to do the exact same thing with C++. Is it possible?

**Comment by champnic** [comment]
@hakzhyena Yes it's possible, and the functions are basically the same:

**Host Object:** https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.902.49#addhostobjecttoscript

**postMessage/WebMessageReceived:** https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.902.49#add_webmessagereceived

Thanks!
