### ISSUE TITLE
Elevating WebView2 from non-admin account creates the msedgewebview2.exe processes as the non-admin user

### ISSUE THREAD

**Issue by Coder666** [MicrosoftEdge/WebView2Feedback#932]
**Description**

When using "Runas" and elevating a WebView2 application from non-admin account, there is an issue whereby the msedgewebview2.exe processes are created as the non-admin user

This causes an access denied 0x80004005 error (presumably because the msedgewebview2.exe processes do not have permission to access the administrator application data)

**Version**
SDK: 1.0.705.50
Runtime: 88.0.705.68    (x64)     
Framework: Win32
OS: Windows 10 20H2 Build 19042.804

**Repro Steps**

Login as a user who does not have administrative privileges

Run the application elevated as an adminstrative user by using "runas"

The application should then call CreateCoreWebView2EnvironmentWithOptions as below:

Set the userDataFolder to a directory within the users application data folder, for example the environment expansion of  "%APPDATA%\MyApplication" i.e "C:\Users\Administrator\AppData\Local\MyApplication"

CreateCoreWebView2EnvironmentWithOptions(
            NULL,
            szAppData,
            NULL,
            Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(this,
                &CMyApp::OnWebView2EnvironmentCreated).Get());

The expected behaviour is that this would work fine and the application would be running on the desktop, with an elevated administrator token.

What actually happens is that the EnvironmentCompletedHandler produces an error code of 0x80004005.

Running process explorer you can see that some "msedgewebview2.exe" processes are started, and they are all running as the standard user rather than the administrator/elevated user.   I believe that this is incorrect behaviour.

[AB#31757028](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31757028)

**Comment by champnic** [comment]
Hey @Coder666, thanks for the bug report! Unfortunately WebView2 isn't well supported with the app running elevated at this time. You will notice some other issues like File Dialogs not being able to be created properly (#802). I've opened this bug on our backlog to take a closer look at this scenario. In the meantime, a workaround could be putting the user data folder into a location writeable by the logged-in user.

**Comment by champnic** [comment]
The browser/runtime processes run at Medium IL (as opposed to admin/High IL) by design, even when the app is elevated. We aren't looking to change that at this time. For your scenario, you'll want to make sure you choose a user data folder for which the runtime will have write permissions. Sorry for the inconvenience!

**Comment by romanan** [comment]
@champnic 2 questions about this:
1) For development, our build environment uses `subst` to map folders into a drive.  The scripts that drive the build are elevated, so this results in the resulting subst'd drive being inaccessible to a non-elevated process.  This is not an end-user problem, but a developer problem, is there any workaround we can use here?

2) For the end-user, will this prevent users from accessing on-disk HTML files that are inaccessible to non-elevated processes even if the user normally has access?  Our application does allow users to load their custom HTML.

**Comment by Coder666** [comment]
> 
> 
> The browser/runtime processes run at Medium IL (as opposed to admin/High IL) by design, even when the app is elevated. We aren't looking to change that at this time. For your scenario, you'll want to make sure you choose a user data folder for which the runtime will have write permissions. Sorry for the inconvenience!


Apologies for the confusion, the issue is not with the processes running at a high IL.

The msedgeview.exe processes run under the *incorrect user account* because COM Cloaking/Proxy Blanketing does not appear to have been implemented in WebView2 (please correct me if I am wrong).

Further explantation:

Standard user:  "test"
Admin user: "administrator"

Log in as "test" and attempt to elevate a webview2 application as the user "administrator".  Note that the main application runs as "administrator" while the msedgeview2.exe applications run as "test".  

The expected behaviour is that msedgeview2.exe would respect the CoInitializeSecurity settings of the main application and execute msedgeview2.exe as "administrator", the integrity level is completly irrelevant.  

The point is that the webview runs under the wrong user account so cannot access the profile.

Is there already a way to use CoInitializeSecurity or a Proxy Blanket in order to run the sandboxed processes from the correct account?

**Comment by champnic** [comment]
Ah, sorry for the misunderstanding and thanks for the added info! I'll follow-up with the team on this bug.

**Comment by champnic** [comment]
@Coder666 I followed up with the team on this one and this is the response I got:
"COM security is not involved. We are not using COM to create medium IL msedgewebview2.exe process, nor is Chromium browser code all running inside a COM context that could impersonate the caller."

My understanding is that this would be very difficult or impossible for us to do, so I'm going to close this again. Apologies for the whiplash on this issue. The recommended workaround remains the same - to make sure the User Data Folder that is created/used has write permissions for the logged in user.

@romanan For 1) you would need to ensure that the subst drives are accessible by the logon user even if created while elevated, or otherwise ensure that it has write access. For 2) the WebView2 will generally follow the model of the browser, so if you see those files being accessible by the browser than WebView2 should be able to load them fine. I don't think it has as strict restrictions because generally it just need to read the HTML files rather than write to them.

**Comment by Coder666** [comment]
I have a question regarding Microsoft's suggested workaroud which I hope you can answer:

The workaround will allow a low privileged user read/write permissions to the webview2 data folder, while the main webview application runs elevated.

Could we get some clarification on the security risks of this?

Example scenario:  The low privileged user modifies files in the data folder to causing *untrusted* javascript ICoreWebView2WebMessageReceivedEventArgs callbacks into the elevated C++ code

**Comment by romanan** [comment]
Another workaround option I've discovered is to use the Windows compatibility mode properties panel to set msedgewebview2.exe to "Run as administrator".  This is probably only useful as a development tool or if WebView2 is deployed as a Fixed version.

**Comment by LiangTheDev** [comment]
@Coder666, WebView host app should not trust anything from the web content, whether running medium IL or high IL. The web content runs remote code and can't be trusted. As the message is received and processed in the app process, which IL we run process to host the web contents doesn't matter.
We do run web content in sandboxed process with untrusted IL so that it could not cause too much damage if there is a bug allowing remote content to compromise the local process and run attacker's native code.
When a process runs high IL, if something got hacked, the damage is high. That's why we generally want to avoid running process as high IL.
FWIW, there are also some other security best practice as well, and them are documented at https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/security

**Comment by Coder666** [comment]
Thanks for your input.  It seems that the workaround is in direct conflict with the security advice.  

For anyone else experiencing this bug, we fixed the issue ourselves by moving our application to use the [CEF library](https://bitbucket.org/chromiumembedded/cef/src/master/).  Migrating to CEF only took two days, and now the process runs elevated as the correct user.

**Comment by Urmeli0815** [comment]
@LiangTheDev I understand the intent of this de-elevation. But at the same time you then have an elevated app running a WebView control which writes possibly sensitive data into a less secure folder? Isn't this also a security concern?

**Comment by LiangTheDev** [comment]
@Urmeli0815, you are right that there is also a security concern there. Running WebView elevated has high risk of potentially getting exploited by remote code from internet while running WebView as medium IL has risk of potential exploit from local processes running on the device. We are more concerned about remote exploitation than applications already running on the device and therefore the design. As the WebView host application should not trust anything coming WebView. Separating anything related to WebView in a separate context actually makes it easier for the app to mitigate risks.

On Windows, it is always a risk for files written by elevated processes. By default, the files written by elevated processes are read/writable by medium IL normal processes and readable by non app container low IL processes. So, if an untrusted process runs on the device, there is a risk to the system. That's the thinking behind Windows Store Apps where they run in App Containers and by default these untrusted apps don't have access to files not written by the apps themselves.

**Comment by Urmeli0815** [comment]
@LiangTheDev Thank you for the thorough explanation. I understand the security aspects of running as a non-elevated user. The problem I see is that, from the perspective of the host app, it can be any other user than the one running my app.

If it would be the same user, but de-elevated, the problem wouldn't manifest like that.

But I don't know if this is technically possible, it seems to surprisingly difficult. There is a way described here by Raymond Chen: https://devblogs.microsoft.com/oldnewthing/20190425-00/?p=102443
but I'm not sure if this could apply as there would need to be an unelevated process of the admin user already running.

**Comment by LiangTheDev** [comment]
Yes, running as different user is a concern. Yes, it is very difficult to create a "de-elevated" process, even for the same user. The compromise is to run the WebView2 part as the current interactive user. It is the current interactive user that is using the app anyway. This does require the app intentionally choose a WebView2 user data folder that is writable by the current interactive user, so kind of requiring app to opt-in for this arrangement.
An alternative design would be the run the app and its UI as normal user and provide the parts that requires elevation as a service/COM server for the app to access.
