### ISSUE TITLE
Can COM Assemblies used with Webview2 for webpage interaction ?

### ISSUE THREAD

**Issue by syncmasterkk** [MicrosoftEdge/WebView2Feedback#975]
An assembly with
[
Guid(""),
ProgId(""),
ClassInterface(),
ComDefaultInterface(typeof(InterfaceName)),
ComSourceInterfaces(typeof(InterfaceName2)),
ComVisible(true)
]

Can this type of assembly used in WebView2 to interact with webpages and webpages calling methods from this assembly ?

**Comment by champnic** [comment]
Hey @syncmasterkk - Could you expand on your question a bit? Are you trying to load an assembly that will call into a running WebView2 control? Or are you trying to expose aspects of the assembly in some way to the WebView2 pages?

You may want to look at our docs and see if that answers your question:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.705.50#Microsoft_Web_WebView2_Core_CoreWebView2_AddHostObjectToScript_System_String_System_Object_

**Comment by syncmasterkk** [comment]
Yes, Im trying to use a COM assembly in WinForm app that will use webview2 control to load webpages. In which the webapp being accessed in webview2 will need to use the COM methods/events/Interfaces. 
I looked at the document you shared, it helps a bit.

**Comment by champnic** [comment]
Gotcha. You can expose the COM object directly to WebView2 if it already supports IDispatch through AddHostObjectToScript. Otherwise you can wrap the COM functionality in a .NET object as described in the link, or can use other messaging like postMessage/[WebMessageReceived ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webmessagereceived?view=webview2-dotnet-1.0.705.50)and [ExecuteScriptAsync ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptasync?view=webview2-dotnet-1.0.705.50#Microsoft_Web_WebView2_Core_CoreWebView2_ExecuteScriptAsync_System_String_)to create the interop between your COM object and the webpage.

I'm going to mark this item as Closed because I don't think there's work on our team here, but please continue the discussion if you have further questions!

**Comment by syncmasterkk** [comment]
Thanks. I was initially planned to use PostMessage and WebMessageReceived. But, when read thro the documentation, made more sense to expose the assembly itself. So, i can broadly access the intricate functions/Methods that could be used as well.

Thanks again.
