### ISSUE TITLE
Add Ons or Extensions with WebView2

### ISSUE THREAD

**Issue by douglas-jordan** [MicrosoftEdge/WebView2Feedback#98]
Are browser addons/extensions disabled and or cannot be installed when running WebView2?
I have searched the command line options and this "--disable-component-extensions-with-background-pages" is part of the options when using WebView2 but not when running Edge from the desktop icon (dev) (seen with process explorer).  Note I do not have any command line arguments specified when creating the environment.

Is there an option or way to install or enable AddOns/Extensions when using WebView2?

[AB#27228257](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27228257)

**Comment by pagoe-msft** [comment]
Hi douglas-jordan,

Thank you for your feedback! We currently do not support extensions in WebView2. Is this a feature you would like to see in further iterations of WebView2?

**Comment by douglas-jordan** [comment]
> Hi douglas-jordan,
> 
> Thank you for your feedback! We currently do not support extensions in WebView2. Is this a feature you would like to see in further iterations of WebView2?

Yes definitely, not sure why you would not.  I can see no extension support being an issue as the customer expectation is to be able to do whatever can be done in a typical browser.   Thanks.

**Comment by pagoe-msft** [comment]
Hi douglas-jordan,

As a developer, would you like to ship an application that includes an extension that is available on Edge? Or, would you like users of your application to be able to download an extension in the WebView the same way they could on their normal browser?

**Comment by douglas-jordan** [comment]
> Hi douglas-jordan,
> 
> As a developer, would you like to ship an application that includes an extension that is available on Edge? Or, would you like users of your application to be able to download an extension in the WebView the same way they could on their normal browser?

It has been our experience in the past that the customer always wants what you don't have and there are some extensions that are a must have. We do not plan to BYO Edge or include extensions, but given the use of modern technology, the users will want extensions.

The user should be able to load their own extensions or use others already available the same way as a typical browser.

**Comment by pagoe-msft** [comment]
Got it! We most likely won't have extension support for our first official release, but it is something we are looking into. If you can, could you describe what you are building with WebView2?

**Comment by douglas-jordan** [comment]
> Got it! We most likely won't have extension support for our first official release, but it is something we are looking into. If you can, could you describe what you are building with WebView2?

We have an existing software suite which supports display of URLs for automated presentation/signage and has supported IE with the WebBrowser Control and has long needed a modern way to render URLs.  We have already released out to customers with Edge WebView2 support for field testing with positive results and continue to await an Edge release which supports an up to date SDK.

**Comment by FireCubeStudios** [comment]
I too would like users to download extensions support in web
view 2

**Comment by JoshuaWeber** [comment]
@FireCubeStudios We are evaluating what supporting extension in WebView2 would look like. Can you help me understand what your app using WebView2 is doing, and how you see extensions being used in your app?

**Comment by FireCubeStudios** [comment]
I actually have 2 apps that can use this.

one is a simple web browser and adding support for extensions would be good for a web browser. especially since not having extensions support can be a no dealer for many people


in the other app I can utilize the translator, Grammarly and maybe the dark mode extension because the webview2 is being used for a lot of typing.

**Comment by KidCoconuts** [comment]
For similar reasons to @FireCubeStudios , I'd like to see extension support also

**Comment by PassivePicasso** [comment]
I opened up a similar request on the samples repo.
https://github.com/MicrosoftEdge/WebView2Samples/issues/39

it would be helpful for communications software which often require extensions to function completely, as browsers can't handle activities such as screen sharing currently.

**Comment by FireCubeStudios** [comment]
in addition to this adding ipfs protocol support which requires an extension and isnt built in by browsers /webview

**Comment by darianmiller** [comment]
> @FireCubeStudios We are evaluating what supporting extension in WebView2 would look like. Can you help me understand what your app using WebView2 is doing, and how you see extensions being used in your app?

I'd like to use the LastPass browser extension within WebView2 as a custom browser but using commercial extensions such as LastPass.

**Comment by dhoelzl** [comment]
Our purpose for this would be using native messaging in WebView2. This would be a uniform way of communication between (almost) any web browser on (almost) any platform with a native application. Otherwise an extra implementation over window.chrome.webview.postMessage would be required for WebView2.

**Comment by danielismo** [comment]
Hi! I As a developer, would like to ship an application that includes an extension that is available on Edge. Is It possible right now?  Or any workaround? I developed my app but i need to deploy It with an Oracle extension.

Thanks in advance.

**Comment by Kay-Burchardt** [comment]
Hi, I'm a developer for SAP Business Client. We are also very interested in the support of extensions in the WebView2. For instance, one of our customers, a leading automobile maker, would like to use SAP Business Client with the integrated WebView2, but is currently unable to do so, because he needs a specific 3rd party browser extension.

**Comment by benark** [comment]
+1 for extension support with WebView2. We are converting over our apps that rely on an embedded browser component to WebView2 and our staff are longing for support for their essential extensions like LastPass.

**Comment by olegchensky** [comment]
Example: It is not possible to use saved Geo-Locations on the WebView2 Start. It will be always used current location. Only after switch it in Sensors the fixed location will be accepted (bug?).
In this case we want to use some Extensions like "Location Guard" which solved this problem.

**Comment by julianbutt** [comment]
> Hi, I'm a developer for SAP Business Client. We are also very interested in the support of extensions in the WebView2. For instance, one of our customers, a leading automobile maker, would like to use SAP Business Client with the integrated WebView2, but is currently unable to do so, because he needs a specific 3rd party browser extension.

+1 for this too - As a SAP customer we also are really interested in this feature. Specific functionality that we use (via a SAPGUI integration) requires a browser extension in a WebView2 window.  With Internet Explorer coming to EoL this year the switch to Edge based browsers will become a requirement and therefore leave a gap in functionality for us.

**Comment by jdnarvaez** [comment]
We would also like to be able to leverage extensions in WebView2 (mainly for redirecting web content on Citrix to a client device).

**Comment by apurvabhansali** [comment]
+1 for extensions.  We have an application that wants to display a page from our server and this page will prompt the user for biometric authentication.  Using our extension and native messaging app, we are able to capture the biometric template and send to our server for authentication.  Our preference would be that the extension is installed in the browser and the webview2 would use the browser installed extensions by default.

**Comment by AndrewMore1** [comment]
+1 for extensions.  In my use case I'm opening the DevTools, and there are debugging tools for AngularJS that are available as extensions that I cannot get access to in the WebView2 control.

**Comment by taylore-msft** [comment]
> I opened up a similar request on the samples repo.
> https://github.com/MicrosoftEdge/WebView2Samples/issues/39
> 
> it would be helpful for communications software which often require extensions to function completely, as browsers can't handle activities such as screen sharing currently.

I’m doing research about how we can implement support for extensions in Webview2.

After reading your comments from this thread, thread [306](https://github.com/MicrosoftEdge/WebView2Feedback/issues/306), and doing research on the Cisco Jabber SDK extension, it seems like you’re envisioning a process where WebView2 developers can programmatically add extensions to webviews so certain extensions are available to end-users by default, rather than giving end-users the ability to install extensions onto the webviews themselves?"

**Comment by jdnarvaez** [comment]
> > I opened up a similar request on the samples repo.
> > https://github.com/MicrosoftEdge/WebView2Samples/issues/39
> > it would be helpful for communications software which often require extensions to function completely, as browsers can't handle activities such as screen sharing currently.
> 
> @PassivePicasso I’m doing research about how we can implement support for extensions in Webview2.
> 
> After reading your comments from this thread, thread [306](https://github.com/MicrosoftEdge/WebView2Feedback/issues/306), and doing research on the Cisco Jabber SDK extension, it seems like you’re envisioning a process where WebView2 developers can programmatically add extensions to webviews so certain extensions are available to end-users by default, rather than giving end-users the ability to install extensions onto the webviews themselves. Is this correct?

I do think it would be extremely beneficial if developers could programmatically add them, but I'm unsure if I think that should be the *only* way extensions are surfaced when using WebView2.

**Comment by PassivePicasso** [comment]
> > I opened up a similar request on the samples repo.
> > https://github.com/MicrosoftEdge/WebView2Samples/issues/39
> > it would be helpful for communications software which often require extensions to function completely, as browsers can't handle activities such as screen sharing currently.
> 
> @PassivePicasso I’m doing research about how we can implement support for extensions in Webview2.
> 
> After reading your comments from this thread, thread [306](https://github.com/MicrosoftEdge/WebView2Feedback/issues/306), and doing research on the Cisco Jabber SDK extension, it seems like you’re envisioning a process where WebView2 developers can programmatically add extensions to webviews so certain extensions are available to end-users by default, rather than giving end-users the ability to install extensions onto the webviews themselves. Is this correct?

Yes that's correct.  I do think it would be ideal if this were designed in a way that wouldn't prevent application developers from allowing end users to add and remove extensions by providing the necessary user interfaces.

**Comment by douglas-jordan** [comment]
The only item I can think of for an API to address extensions for our application would be to allow enable/disable of installing or deleting extensions and an interface to remove or disable specific extensions.  In our application the user would load whatever they need and we could provide a webview to allow them to go to the URL of choice to load the extensions.

**Comment by apurvabhansali** [comment]
Why not address it like IE11 with ActiveX.  If the ActiveX is installed in IE11 then the WebBrowser control rendered pages can access the ActiveX.  Likewise, if a user installs the extension in Edge Chromium then make it installed in WebView2.  Our site does MFA authentication and needs our extension and native messaging app to talk to hardware on the PC.  We have detection logic in our page to check for our extension and if it is not installed we prompted to user to click a link to the chrome store from where he can install it.  Following my suggestion would allow for the same flow even if the page is rendered in a WebView2.  A developer may not know what extensions need to be installed.

Take the case of a .Net app that implements SAML for login and redirects the SAML to the IDP's login page.  This could be any IDP (like our site) and the developer of the .Net app would not know to install OKTA's extension or ours or any other IDP.  It would be up to the user of the system to install that into Edge Chromium for the IDP he is using.  This works right now if the .net app uses WebBrowser control and the IDP provides and ActiveX for IE11.

I do understand the suggestion where it would be nice for the developer to force installation of an extension he knows he wants, so maybe a way where the default is to use all edge chromium installed extensions with a mechanism for a developer with a specific use to override that and specify exactly what extensions they want.

**Comment by taylore-msft** [comment]
@darianmiller, @benark, @olegchensky for your comments related to Last Pass and Geolocation are you looking for developers to be able to programmatically add these extensions to Webviews so they are available to end-users by default or for end-users to be able to install and use these extensions? We are evaluating both scenarios to see which one is more pressing. (there is likely a progression from the developer scenario to the end-user scenario because the end-user scenario requires additional UI)

**Comment by darianmiller** [comment]
@taylore-msft: adding the ability to programmatically add extensions would be the priority.  Thanks!

**Comment by benark** [comment]
Being able to programmatically install/add an extension, specifically Last Pass in our scenario, would be the priority and exceptionally useful.

**Comment by PassivePicasso** [comment]
> @darianmiller, @benark, @olegchensky, for your comments related to Last Pass and Geolocation are you looking for developers to be able to programmatically add these extensions to Webviews so they are available to end-users by default or for end-users to be able to install and use these extensions? We are evaluating both scenarios to see which one is more pressing. (there is likely a progression from the developer scenario to the end-user scenario because the end-user scenario requires additional UI)

I Just want to mention that in my scenario, I would specifically not want to allow end users to add extensions at this time. Our situation may change, but currently we don't want the end user to have access to such a feature.

**Comment by apurvabhansali** [comment]
Our scenario is completely the opposite.  We have to have the ability for the user to install the extension.   In our scenario, we are not the developer of the app, the developer would be a 3rd party that wants to allow SAML login (e.g. would be PulseSecure VPN client, webex/zoom desktop client, citrix client, etc.  If these clients ultimately move to webview2 (most of these use WebBrowser control right now), then if they redirect to our service or any other 3rd party SSO provider for SAML login, then that the extension for that 3rd party needs to be installed manually by the user.  

If you want to see the scenario in action, you can see it here on our youtube channel.  Again, this works today, because PulseSecure VPN client (shown in the video) uses WebBrowser control which uses the ActiveX controls installed by the user in IE11.  I would think this will be an important scenario to cover.

https://youtu.be/OLbf9HkBEzg

**Comment by lucasyvas** [comment]
The priority seems like it should be programmatic management of installed extensions.

It is both easier to add as a first step and makes no assumption on user experience, since the author of the WebView2 based app can create a UI for the user to manage extensions that matches the app's requirements.

It might be nice to offer an out of the box way for the end user to manage extensions, but it should be possible to disable this default experience in favour of providing your own.

**Comment by taylore-msft** [comment]
We are designing our implementation for extensions in WebView2 and would like the community's feedback on these questions and design thoughts.

1. Based on the customer evidence gathered, we know the developer community wants extensions from the store and non-store crx extension files to be supported in WebView2. Is anyone looking to support unpacked extensions in WebView2?

2.  Since the browser UI is different from the UI in WebView2, ensuring that ALL browser extensions are compatible with the WebView2 UI will take time. Therefore, besides debugging extensions (React Dev Tools, Angular JS), extensions webview devs want to programmatically install for end-users (Last Pass, Grammarly, Dark Mode, Translator), and the other extensions mentioned previously, we want to hear about which additional extensions should be prioritized.
          - @AndrewMore1, could you list the specific Angular extension you want support for?

3. Should we make it possible for webview developers to install extensions to specific webview instances, or should all extensions installed by developers apply to all webview instances within a native app?

4. We are planning on creating the API  functions listed below to give webview developers a programmatic way to manage extensions, and as mentioned by @lucasyvas, WebView2 developers can use these methods to build an extension management page for the end-user if they desire:
   - “enable_extension” 
   - “disable_extension” 
   - "site_access"
   - "Allow access to file urls"
   - "Collect errors"

@danielismo I couldn't find the Oracle ESSO extension you mentioned on the Microsoft Store or Chrome Store. Do you know if this extension is bundled with the Oracle ESSO software (More info on extension bundling [Alternate method to distribute extensions - Microsoft Edge Development | Microsoft Docs](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options))?

5.  Does anyone else have a use case where they want an extension in WebvView2, but on the browser, this extension is normally bundled with software?

**Comment by lucasyvas** [comment]
>3. Should we make it possible for webview developers to install extensions to specific webview instances, or should all extensions installed by developers apply to all webview instances within a native app?

Excellent questions. With absolutely zero evidence, I'd wager it's more critical to support the global use case where all are enabled in every webview. This seems to align more closely to a traditional browsing experience.

That said, I have worked with Electron in the past a fair bit and it can both be better for security and performance if you are able to designate extensions on a webview/session basis there, so I can see that as being a nice feature even if it doesn't make an initial release.

**Comment by m1keam** [comment]
@taylore-msft 

> 2. Since the browser UI is different from the UI in WebView2, ensuring that ALL browser extensions are compatible with the ;WebView2 UI will take time. Therefore, besides debugging extensions (React Dev Tools, Angular JS), extensions webview devs want to programmatically install for end-users (Last Pass, Grammarly, Dark Mode, Translator), and the other extensions mentioned previously, we want to hear about which additional extensions should be prioritized.

We like some others above need the ability to load extensions programmatically, access a native messaging host to talk to our devices and preferably access from the webstore, see https://chrome.google.com/webstore/detail/topaz-sigplusextlite-back/dhcpobccjkdnmibckgpejmbpmpembgco.  This supports specific application workflows.
As the developer of the solution we can bear responsibility for insuring the UI for our customers.

**Comment by steingat** [comment]
Here is our use case:
Google supports Context aware access in both edge and chrome and requires the Endpoint verification plugin be installed to enforce policies.  We have a outlook plugin that uses SAML Authentication to authenticate to google via Webview2.

We would want the ability to force install extensions via a GPO (Or registry edit) for the Endpoint verification plugin.

**Comment by JT-Potato** [comment]
Our use case:
uBlock Origin or some other form of ad-blocker to remove ads from remote web content

**Comment by frinkfree** [comment]
Using WebView2, we need the Imprivata OneSign chrome extension for dual authentication.

**Comment by netlocks** [comment]
I also wish to use this extension https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi/related

**Comment by netlocks** [comment]
I also wish to use this extension https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi/related

**Comment by FireCubeStudios** [comment]
I need this for my browser app

**Comment by muznyo** [comment]
Yes please, I want extensions too!

**Comment by bilou47190** [comment]
Idem, je cherche aussi à mettre les extensions, surtout adblock.

**Comment by tomgao365** [comment]
I am a front-end developer, for example https://github.com/tauri-apps/tauri is using webview2.
 vue.js developers need Vue.js devtools

**Comment by apurvabhansali** [comment]
@taylore-msft  Is there an update on how the implementation of extensions in WebView2 is being done and the timeframe?  Today we encountered the case for allowing users to select the extensions that WebView2 will use like IE11 does with ActiveX w/IWebBrowser2.  

We are the developer of a SAML Identity Provider (IDP).  We configured our Office365/AzureAD tenant to do Federated SAML authentication with IDP for login.  Our IDP uses our own extension to do biometric authentication allowing you to do biometric authentication to login to Office365.  From office365.com loaded in the Edge browser, we have no issue, this works fine.  But when using Teams or Outlook, the Teams or Outlook app will invoke a WebView2 control and redirect to our IDP for authentication.  Here our extension is not loaded and authentication can not be done using the biometric.  

Have you guys thought about this more and how would this be solved?  We are not the developer of Teams or Outlook (obviously) so if extensions can only be loaded programmatically by the app developer, then we have no way of having this SAML Authentication work with WebView2 based apps.  Do the same thing using an app that uses IWebBrowser2 and it works fine (using our ActiveX control loaded in IE11).

**Comment by mjpalazzo** [comment]
Please provide a date when WebView2 will support extensions. Thank you!

**Comment by Viaro-Brayan-Aguirre** [comment]
Please we need  this feature. This enables a lot of posibilites!

**Comment by brz** [comment]
Any updates on this matter?

**Comment by david-ps** [comment]
@champnic Can you please provide an update on this issue?

**Comment by champnic** [comment]
@nishitha-burman or @Syul968 should have more insight on the current status.

**Comment by ZanzyTHEbar** [comment]
wouldbe nice to use react dev tools extension for developing webView2-based applications with frameworks like `tauri`

**Comment by lundmikkel** [comment]
We would like to use extensions to help the developer experience. We have an Angular app shown in a webview, but we can't use any browser extensions to facilitate development, e.g. [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) or [Angular DevTools](https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh).

**Comment by AdPipino** [comment]
I would like to use extensions to apply Dark Mode and Translate Pages without having to reload them.
Translate Web Pages - https://github.com/FilipePS/Traduzir-paginas-web
Turn Off the Lights™ - https://www.turnoffthelights.com

**Comment by kirillPshenychnyi** [comment]
Is there any ETA available? CefSharp and DotNetBrowser [claim to support extensions already](https://dev.to/dotnetbrowser/chrome-extensions-in-net-web-view-controls-11lm). But CefSharp is really buggy and DotNetBrowser is not free.

I need Windows Accounts extension.

**Comment by llehn** [comment]
> Is there any ETA available? CefSharp and DotNetBrowser [claim to support extensions already](https://dev.to/dotnetbrowser/chrome-extensions-in-net-web-view-controls-11lm). But CefSharp is really buggy and DotNetBrowser is not free.
> 
> I need Windows Accounts extension.

Windows Logins are already supported, use this:

````
coreWebView2Environment = await CoreWebView2Environment.CreateAsync(
    webView2Path,    
    userDataFolder,
    new(allowSingleSignOnUsingOSPrimaryAccount: true));

**Comment by nishitha-burman** [comment]
Hello,

The [experimental extensions APIs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#experimental-features) are now available to try. Please let us know if you have any feedback.

Thanks!

**Comment by Tom21200** [comment]
> Hello,
> 
> The [experimental extensions APIs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#experimental-features) are now available to try. Please let us know if you have any feedback.
> 
> Thanks!

Hello, I would like to know how to download this version of webview2 to allow extensions in my webview2 control, but I can't see the version "WebView2 .NET 1.0.1988-prerelease" anywhere in NuGet, I have the version "1.0.1901.177", is there something to do? Thanks

**Comment by Tom21200** [comment]
Hello, I don't think I should post this here but, I do not know how to use this to make my WebView2 control work in vb.net, so far I have "CoreWebView2BrowserExtension.EnableAsync(true)" but it doesn't work because of something or I don't know I'm a bit lost. Thanks

**Comment by champnic** [comment]
To use these APIs you'll need the SDK version 1.0.1988-prerelease+, and a runtime version 117.0.1988.0 or newer. The Microsoft Edge Canary or Dev channels should be new enough:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

**Comment by jmdurant** [comment]
This is great! Was wondering if anyone could do a howto or tutorial on how
to bundle a web view based application with an extension.  Thanks!

**Comment by champnic** [comment]
@jmdurant We do have some example code here:
https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2APISample/ScenarioExtensionsManagement.cpp

And API Design Doc here:
https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/Extensions.md

Although it looks like the sample app is missing some files so I'm doubtful it currently works. I've opened a bug on our side to fix that. But in the meantime you should be able to look at the source code to get a sense of how to use the APIs.

**Comment by codewithshehraz** [comment]
This issue was initially reported to enable external extensions in WebView 2. However, it was closed in conjunction with another request that focused on allowing developers to enable Chrome extensions during development. For this purpose, the Extensions API was provided. Unfortunately, the two issues were mixed up, leading to the closure of the original request. I am still curious whether we can enable external extensions in our plugin app, or if developers are required to explicitly allow this functionality.
