### ISSUE TITLE
How do we get WebView2 instance from CoreWebView2Controller?

### ISSUE THREAD

**Issue by chaitanyajun12** [MicrosoftEdge/WebView2Feedback#987]
I have instantiated `WebView2` via `CoreWebView2Controller` API, but I'm able to acccess only `CoreWebView2` instance only. How can I access `WebView2` instance? Is there a way?

**Comment by david-risney** [comment]
You cannot get a WebView2 from a CoreWebView2 or CoreWebView2Controller.

The WebView2 controls are UI framework specific and there are different versions for WPF, WinForms, and WinUI. They create their own CoreWebView2Controller in order to integrate with their UI framework. The CoreWebView2Controller has no knowledge of if its being used by a WebView2 control or being used directly. The WebView2 controls don't currently support being created on a preexisting CoreWebView2Controller.

**Comment by chaitanyajun12** [comment]
So, the only way to create WebView2 is directly creating the WebView2 instance only as I understand.
What is the use of CoreWebView2Controller being exposed outside? Is there any scenario this can be used?

The way I was planning to create earlier was to,
 - Create CoreWebView2Environment
 - Create CoreWebView2Controller
 - Since this creates CoreWebView2, thought of accessing WebView2 for setting on the WPF component.

But, now I'm not understanding how we can use the above classes. Please correct if my understanding is correct or not.

**Comment by david-risney** [comment]
You cannot use CoreWebView2Controller and a WebView2 control at the same time. You use one or the other.

If you use a WebView2 control then you create the WebView2 control via XAML or however depending on your UI framework. You can use the EnsureCoreWebView2Async method to have the CoreWebView2 property explicitly initialized. Optionally if you want to customize your CoreWebView2Environment you can create one and pass it in to the EnsureCoreWebView2Async method. We have [getting started guides ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf) for WPF, WinForms, and WinUI that should cover how to do this.

Or if you use CoreWebView2Controller, you first create a CoreWebView2Environment, use CreateAsync to create a CoreWebView2Controller which has an initialized CoreWebView2 property containing your CoreWebView2. In this case you are responsible for hooking up the CoreWebView2Controller to any sort of UI, input, or accessibility via the custom control mechanism of whatever UI framework you are using or directly using Windows HWNDs or composition objects.

**Comment by chaitanyajun12** [comment]
Got it. Regards to, 

`In this case you are responsible for hooking up the CoreWebView2Controller to any sort of UI, input, or accessibility via the custom control mechanism of whatever UI framework you are using or directly using Windows HWNDs or composition objects.`

Is there any sample application which shows how to inflate CoreWebView2 from CoreWebView2Controller on WPF UI?

**Comment by david-risney** [comment]
There is not. Instead of a sample showing how to hook up the CoreWebView2Controller to WPF we have built and will continue improving the WPF WebView2 control which does that.

**Comment by champnic** [comment]
I'm going to close this issue as I think it's been answered and there isn't further work on us here. Please feel free to continue the discussion and ask more questions!

**Comment by duncangroenewald** [comment]
@david-risney - I am puzzled by the response that there is no example of using CoreWebView2Controller on its own as there appear to be many things that WebView2 does not support.  For example according to the documentation for WebView2 (WinForms)

_AcceleratorKeyPressed dispatches when an accelerator key is pressed and **before** it gets handled by the [WebView2](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2?view=webview2-dotnet-1.0.705.50). You can write a custom handler to suppress handling by the Webview by doing e.Handled = true;._

And the key word is **BEFORE** - however there appears to be no equivalent for WPF, or WinUI - so it seems that it is not possible to capture key strokes BEFORE they get handled by WebView2 in anything other than WinForms.  In this case one would expect to be able to use the lower level API to achieve the same outcome.

**Comment by david-risney** [comment]
There are examples of using CoreWebView2Controller on its own but only in Win32 where there is no UI framework. If there are issues with or features missing from one of the WebView2 controls then please open a new issue about it and we'll take a look. Thanks!

**Comment by champnic** [comment]
@duncangroenewald AcceleratorKeyPressed is exposed through the KeyDown event in WPF and Winforms. There's currently a potential bug with KeyDown in WinUI that we're investigating.

**Comment by duncangroenewald** [comment]
Check WPF because I don't think KeyDown works for that either.  Currently I am using CoreWebView2Controller to create the WebView2 in a WPF app and using the AcceleratorKeyPressed which is working as expected.  Gave up on both WinUI and WPF as KeyDown is never getting called as far as I can determine.

**Comment by champnic** [comment]
@zhuhaichao518 Can you please verify that WPF KeyDown is working as expected?
@duncangroenewald Could you please open a new issue to track that? What framework, WebView2 SDK version, and WebView2 Runtime version are you using? Thanks!

**Comment by duncangroenewald** [comment]
OK I will double check that it is not working and raise an issue.  I am using the Fixed version but will need to check which version it is.

**Comment by zhuhaichao518** [comment]
@duncangroenewald could you please try out the latest [WPF sample code](https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2WpfBrowser/MainWindow.xaml.cs)? I have tried it under runtime version 108.0.1462.54 and it seems _WebView_KeyDown_ function can be triggered correctly by accelerator keys.

**Comment by duncangroenewald** [comment]
We are using the Fixed version 108.0.1462.46.x64 but I will try the latest version .76 Cheers From: zhuhaichao518Sent: Saturday, 7 January 2023 10:44 AMTo: MicrosoftEdge/WebView2FeedbackCc: Duncan Groenewald; MentionSubject: Re: [MicrosoftEdge/WebView2Feedback] How do we get WebView2 instance from CoreWebView2Controller? ***@***.*** could you please try out the latest WPF sample code? I have tried it under runtime version 108.0.1462.54 and it seems WebView_KeyDown function can be triggered correctly by accelerator keys.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by duncangroenewald** [comment]
we are using Fixed version 108.0.1462.46.x64 but I will try with the latest v .76

Cheers

**Comment by duncangroenewald** [comment]
BTW CoreWebView2.ServerCertificateErrorDetected does not seem to be available in some versions either.  I think in the WInUI 3 version - which I believe is bundled with the Windows App SDK.  

I have to say it's all very confusing - too many SDK's and versions.
